import type {
  DecisionIntent,
  EduNode,
  LearningPath,
  MapCluster,
  TelegramCommand,
  Workflow,
} from "./types";

const DISCLAIMER =
  "OrbitX education is research and product guidance, not financial advice. On-chain data can be delayed or incomplete. You can lose money. Never share a seed phrase.";

function node(partial: Omit<EduNode, "published"> & { published?: boolean }): EduNode {
  return { published: true, ...partial };
}

export const SAFETY_DISCLAIMER = DISCLAIMER;

export const SEARCH_PLACEHOLDERS = [
  "How do I find smart money?",
  "How do I launch a token?",
  "How do I use the DEX?",
  "How do I claim fees?",
  "How do I trade through Telegram?",
  "What is MCP?",
  "How do I research a wallet?",
];

export const EDU_NODES: EduNode[] = [
  node({
    id: "what-is-orbitx",
    kind: "guide",
    title: "What is OrbitX?",
    slug: "what-is-orbitx",
    category: "research",
    description: "The non-custodial on-chain operating system — trade, launch, research, social, and play in one place.",
    difficulty: "beginner",
    estimatedMinutes: 6,
    icon: "orbit",
    href: "/app",
    status: "live",
    what: "OrbitX is a non-custodial Solana platform. Your wallet signs every action. OrbitX never holds keys. Surfaces include OrbitX DEX, Trade, Intel, Launchpad, Telegram, Agent MCP, City, Play, Social, Predictions, NFT Market, and Bagwork.",
    why: "New users bounce between scanners, launchpads, and chats. OrbitX puts discovery, research, execution, and creation on one map so you can see how the pieces connect.",
    when: "Start here before your first swap, launch, or MCP session — especially if you only know one OrbitX URL.",
    steps: [
      { title: "Open the Hub", body: "Go to /app. That deck is the live catalog of public OrbitX surfaces.", hotspot: "Hub grid" },
      { title: "Pick a job, not an app", body: "Trade, research, launch, automate, or play. Education paths below map jobs to the real routes.", hotspot: "Learning paths" },
      { title: "Connect a wallet only when you act", body: "Browsing Intel, DEX lists, and Education does not require a wallet. Signing a swap, launch, or claim does.", hotspot: "Phantom / Jupiter Wallet" },
      { title: "Treat data as research", body: DISCLAIMER, hotspot: "Safety" },
    ],
    features: ["Non-custodial signing", "Public hub catalog", "DEX + Intel + Launchpad + MCP", "City / OS / Play / Social"],
    useCases: ["First visit orientation", "Explaining OrbitX to a teammate", "Finding the live route for a job"],
    related: ["getting-started", "ecosystem-map", "orbitx-dex"],
    prerequisites: [],
    next: ["getting-started", "connect-wallet"],
    demo: "none",
    tags: ["intro", "hub", "ecosystem"],
  }),
  node({
    id: "getting-started",
    kind: "guide",
    title: "Getting started",
    slug: "getting-started",
    category: "research",
    description: "A 10-minute loop: hub, education path, one research tool, one live surface.",
    difficulty: "beginner",
    estimatedMinutes: 10,
    icon: "flag",
    href: "/education",
    status: "live",
    what: "The shortest path from zero to a working OrbitX session without inventing features.",
    why: "A giant ecosystem is useless if the first click is the wrong desk.",
    when: "Any first session on phone or desktop.",
    steps: [
      { title: "Stay in Education", body: "Use search or a path card. Do not skip to a random DEX chart until you know what you are looking at." },
      { title: "Open Hub", body: "/app lists live apps. Admin-only desks (Terminal, KOL Tracker, X MCP) stay hidden unless you are the owner." },
      { title: "Open one live tool", body: "Beginners: OrbitX DEX or Intel. Creators: Launchpad. Builders: Agent MCP + Shop." },
      { title: "Mark the lesson complete", body: "Progress is stored in this browser. Sign-in sync can be added later without changing lesson IDs." },
    ],
    features: ["Path cards", "Tool index", "Local progress"],
    useCases: ["First day", "Mobile onboarding"],
    related: ["what-is-orbitx", "connect-wallet", "basic-trading-workflow"],
    prerequisites: ["what-is-orbitx"],
    next: ["connect-wallet", "ecosystem-map"],
    demo: "workflow",
    tags: ["onboarding", "mobile"],
  }),
  node({
    id: "connect-wallet",
    kind: "guide",
    title: "Connecting your wallet",
    slug: "connecting-your-wallet",
    category: "trading",
    description: "Phantom (and other Solana wallets) sign locally. OrbitX never sees your seed.",
    difficulty: "beginner",
    estimatedMinutes: 5,
    icon: "wallet",
    href: "/trade",
    status: "live",
    what: "Wallet connect on Trade, DEX, Launchpad, Telegram link, and Agent MCP uses public addresses only. Trades and launches are signed in the wallet UI.",
    why: "Every real action — buy, sell, launch, fee claim, MCP burn access — needs a signer.",
    when: "Right before you swap, launch, claim fees, or link Telegram / MCP — not while you are only reading Education.",
    steps: [
      { title: "Install a Solana wallet", body: "Phantom is the common path. Hardware wallets work where the wallet adapter supports them." },
      { title: "Connect on the surface you will use", body: "Trade uses /trade. DEX uses /ORBITX_DEX. Launchpad uses /orbitxlaunch. Telegram uses /telegram after /login in DM." },
      { title: "Read the wallet prompt", body: "If you did not expect a signature, reject it. OrbitX will not complete a swap without that signature." },
      { title: "Never paste a seed into OrbitX", body: "Any site asking for a seed phrase is not OrbitX education. Stop." },
    ],
    features: ["Non-custodial", "Per-surface connect", "Reject unexpected prompts"],
    useCases: ["First swap", "Launch", "Telegram link"],
    related: ["orbitx-dex", "trade-app", "telegram-bot"],
    prerequisites: ["what-is-orbitx"],
    next: ["basic-trading-workflow", "orbitx-dex"],
    demo: "dex",
    tags: ["wallet", "phantom", "safety"],
  }),
  node({
    id: "ecosystem-map",
    kind: "guide",
    title: "Understanding the OrbitX ecosystem",
    slug: "understanding-the-orbitx-ecosystem",
    category: "research",
    description: "How DEX, Intel, Launchpad, Telegram, MCP, City, Play, and Social actually relate.",
    difficulty: "beginner",
    estimatedMinutes: 8,
    icon: "map",
    href: "/education",
    status: "live",
    what: "OrbitX is a mesh, not a single page. Discovery often starts on DEX or Intel, execution on Trade/DEX/Telegram, creation on Launchpad, automation on Agent MCP, and community on Social / City / Play.",
    why: "Users bounce because they think the scanner is the whole product.",
    when: "After the intro, before you commit to a path.",
    steps: [
      { title: "Trade cluster", body: "OrbitX DEX, Trade, Intel scan, charts, portfolio." },
      { title: "Intelligence cluster", body: "Intel desk, On-Chain world, whales/KOL desk, wallet tracker." },
      { title: "Launch cluster", body: "Launchpad create lanes, claim fees, token pages, anti-vamp at launch time." },
      { title: "Automation cluster", body: "Telegram @theorbitxmcpbot, Agent MCP, OrbitX AI, Shop burns for timed MCP access." },
    ],
    features: ["Live public catalog", "Owner-only desks labeled desk"],
    useCases: ["Choosing a path", "Explaining OrbitX"],
    related: ["what-is-orbitx", "token-scanner", "orbitx-mcp"],
    prerequisites: ["what-is-orbitx"],
    next: ["basic-trading-workflow"],
    demo: "none",
    tags: ["map", "overview"],
  }),
  node({
    id: "basic-trading-workflow",
    kind: "guide",
    title: "Basic trading workflow",
    slug: "basic-trading-workflow",
    category: "trading",
    description: "Discover → research → risk → execute → track. No promised edge.",
    difficulty: "beginner",
    estimatedMinutes: 9,
    icon: "flow",
    href: "/education/workflow/discovery-to-trade",
    status: "live",
    what: "A repeatable loop using live OrbitX tools. Execution is always a wallet signature on DEX, Trade, or Telegram (linked DM).",
    why: "Jumping straight to buy size is how people skip holder and mint checks.",
    when: "Before your first live swap on OrbitX.",
    steps: [
      { title: "Discover", body: "DEX screener, Intel trending, or Telegram /screen." },
      { title: "Research", body: "Token page + Intel scan: contract, liquidity, holders." },
      { title: "Risk", body: "Mint/freeze, bundles, clone/anti-vamp signals. Data is not a guarantee." },
      { title: "Execute", body: "DEX or Trade. Set slippage yourself. Confirm in the wallet." },
      { title: "Track", body: "Trade portfolio or Intel portfolio — balances from chain, not a promise of PnL." },
    ],
    features: ["Linked workflow", "Real routes only"],
    useCases: ["First trade", "Checklist"],
    related: ["orbitx-dex", "token-scanner", "trade-execution"],
    prerequisites: ["connect-wallet"],
    next: ["orbitx-dex", "token-scanner"],
    demo: "workflow",
    tags: ["workflow", "safety"],
  }),
  node({
    id: "orbitx-dex",
    kind: "tool",
    title: "OrbitX DEX",
    slug: "orbitx-dex",
    category: "trading",
    subcategory: "execution",
    description: "Scanner, tape, charts, and Jupiter-routed swaps on /ORBITX_DEX.",
    difficulty: "beginner",
    estimatedMinutes: 12,
    icon: "dex",
    href: "/ORBITX_DEX",
    status: "live",
    what: "The production DEX app. Token lists, scanner, pulse, wallet desk, research, tools, alerts, leaderboard, store, metadata editor, and per-token trade panels. Swaps route through Jupiter; you sign in your wallet.",
    why: "One surface for discovery and execution without leaving OrbitX.",
    when: "Finding a mint, reading a chart, or placing a buy/sell you are willing to sign.",
    steps: [
      { title: "Open DEX", body: "Go to /ORBITX_DEX. This is the live market desk, not a mock.", hotspot: "DEX shell" },
      { title: "Find a token", body: "Search or open a pair. Paste a mint when you already have a CA.", hotspot: "Search" },
      { title: "Read the panel", body: "Price, liquidity, and chart widgets are third-party + indexer feeds. They can lag.", hotspot: "Token panel" },
      { title: "Set size and slippage", body: "You choose amount and slippage. Price impact is shown when the quote exists — it is not a profit forecast.", hotspot: "Trade ticket" },
      { title: "Sign the swap", body: "Phantom (or connected wallet) must approve. Reject anything you did not start.", hotspot: "Wallet prompt" },
      { title: "Check history", body: "Confirmed swaps appear in wallet / portfolio views after the chain confirms.", hotspot: "Portfolio" },
    ],
    features: ["Jupiter routing", "Scanner & pulse", "Wallet desk", "Alerts", "Metadata tools"],
    useCases: ["Spot buy/sell", "Chart + tape", "Token metadata updates"],
    related: ["trade-app", "token-scanner", "trade-execution"],
    prerequisites: ["connect-wallet"],
    next: ["trade-execution", "token-discovery"],
    demo: "dex",
    tags: ["dex", "jupiter", "swap", "slippage"],
  }),
  node({
    id: "trade-app",
    kind: "tool",
    title: "Trade",
    slug: "trade",
    category: "trading",
    description: "Phantom buy & sell desk at /trade — home, desk, portfolio, wallets.",
    difficulty: "beginner",
    estimatedMinutes: 8,
    icon: "trade",
    href: "/trade",
    status: "live",
    what: "A focused execution app: /trade desk, token pages, portfolio, wallet manager, leaderboard. Complements DEX rather than replacing Intel research.",
    why: "When you already have a mint and want a clean buy/sell ticket.",
    when: "After research, or when Telegram/MCP sent you a Sign link that lands in the browser wallet flow.",
    steps: [
      { title: "Open Trade", body: "/trade home, then Desk or a /trade/token/:mint page." },
      { title: "Connect", body: "Same non-custodial connect as DEX." },
      { title: "Quote then sign", body: "Size in SOL or percent of bag. Confirm in wallet." },
    ],
    features: ["Desk", "Portfolio", "Wallet manager", "Leaderboard"],
    useCases: ["Fast ticket", "Position check"],
    related: ["orbitx-dex", "telegram-bot"],
    prerequisites: ["connect-wallet"],
    next: ["trade-execution"],
    demo: "dex",
    tags: ["trade", "phantom"],
  }),
  node({
    id: "token-discovery",
    kind: "guide",
    title: "Token discovery",
    slug: "token-discovery",
    category: "research",
    description: "Where new Solana names actually show up on OrbitX today.",
    difficulty: "beginner",
    estimatedMinutes: 7,
    icon: "radar",
    href: "/ORBITX_DEX",
    status: "live",
    what: "DEX lists, Intel trending, Telegram /screen and /search, MCP orbitx_search / screen tools. No guaranteed 'alpha feed'.",
    why: "Discovery without context is just noise.",
    when: "Start of a session when you do not already have a CA.",
    steps: [
      { title: "DEX or Intel trending", body: "Use /ORBITX_DEX or /intel/trending — velocity lists, not endorsements." },
      { title: "Telegram pulse", body: "In a public group, /screen or drop a ticker. Groups stay public; buys stay wallet-gated." },
      { title: "Save the mint", body: "Always copy the contract address. Tickers collide." },
    ],
    features: ["Screener", "Trending", "Telegram search"],
    useCases: ["Session start"],
    related: ["orbitx-dex", "token-scanner", "telegram-bot"],
    prerequisites: ["what-is-orbitx"],
    next: ["token-research", "token-scanner"],
    demo: "scanner",
    tags: ["discovery", "screener"],
  }),
  node({
    id: "token-research",
    kind: "guide",
    title: "Token research",
    slug: "token-research",
    category: "research",
    description: "Read a mint like a report: contract, liquidity, holders, then wallets.",
    difficulty: "trader",
    estimatedMinutes: 11,
    icon: "search",
    href: "/intel/scan",
    status: "live",
    what: "Intel scan + DEX token page + Telegram /token /xray /research. Compose a picture; do not treat a score as certainty.",
    why: "Tickers lie. Mints and holder graphs do not care about the meme.",
    when: "After you have a CA, before size.",
    steps: [
      { title: "Open the mint", body: "/intel/scan/:mint or DEX token page." },
      { title: "Contract & authorities", body: "Mint/freeze still active? Metadata mutable? That is risk, not a trade signal." },
      { title: "Liquidity", body: "Where is LP? Can it be pulled? Feeds can lag." },
      { title: "Holders", body: "Concentration and fresh wallets. See Holder analysis." },
    ],
    features: ["Intel scan", "DEX token", "Telegram xray"],
    useCases: ["Pre-trade checklist"],
    related: ["token-scanner", "holder-analysis", "wallet-research"],
    prerequisites: ["token-discovery"],
    next: ["token-scanner", "holder-analysis"],
    demo: "scanner",
    tags: ["research", "forensics"],
  }),
  node({
    id: "token-scanner",
    kind: "tool",
    title: "Token Scanner",
    slug: "token-scanner",
    category: "research",
    subcategory: "forensics",
    description: "Intel scanner — overview, contract, liquidity, holders, rug/clone risk.",
    difficulty: "trader",
    estimatedMinutes: 14,
    icon: "scan",
    href: "/intel/scan",
    status: "live",
    what: "Live at /intel/scan and /intel/scan/:mint. Pulls safety + forensics + token APIs into one desk (risk engine 0–100 → A–F). DEX also has /ORBITX_DEX/scanner for OG-style scans. Neither is a buy recommendation.",
    why: "You need a single place to inspect a mint before you size a swap.",
    when: "Any time you have a CA you did not create yourself.",
    steps: [
      { title: "Find your token", body: "Paste a mint into Intel scan or open it from trending.", hotspot: "Mint field" },
      { title: "Analyze the token", body: "Overview: name, liquidity, market data from public aggregators — can be wrong or late.", hotspot: "Overview" },
      { title: "Check holders", body: "Concentration, top wallets, obvious bundles. See Holder analysis.", hotspot: "Holders" },
      { title: "Check wallets", body: "Click through to /intel/wallet/:address for a tracked wallet snapshot.", hotspot: "Wallet" },
      { title: "Make your decision", body: "If mint/freeze, LP, or holder picture is unclear, the educational answer is: do not size up. That is not financial advice — it is process.", hotspot: "Risk" },
      { title: "Execute", body: "Only if you still want exposure: DEX or Trade with a size you can afford to lose.", hotspot: "Trade" },
    ],
    features: ["Contract", "Liquidity", "Holders", "Clone/rug heuristics", "Wallet drill-down"],
    useCases: ["Unknown CA", "Clone check", "Pre-launch lookalike"],
    related: ["holder-analysis", "wallet-research", "smart-money", "orbitx-dex"],
    prerequisites: ["token-research"],
    next: ["holder-analysis", "wallet-research"],
    demo: "scanner",
    tags: ["scanner", "intel", "forensics"],
  }),
  node({
    id: "wallet-research",
    kind: "guide",
    title: "Wallet research",
    slug: "wallet-research",
    category: "onchain",
    description: "Track a Solana address: holdings, flows, and labels — never a guaranteed copy-trade.",
    difficulty: "trader",
    estimatedMinutes: 10,
    icon: "wallet",
    href: "/intel/wallet",
    status: "live",
    what: "Intel wallet tracker /intel/wallet/:address, DEX /ORBITX_DEX/wallet, On-Chain world wallet pin, Telegram /wallet. Labels (KOL vs random) only when the directory or indexer confirms them.",
    why: "Tokens are stories. Wallets are behavior.",
    when: "After holders, or when someone drops a 'smart wallet' without proof.",
    steps: [
      { title: "Paste the address", body: "Intel wallet page or On-Chain Track field." },
      { title: "Holdings", body: "SOL and token balances from chain/RPC. Empty means empty or indexer delay — not a hidden bag." },
      { title: "Flows", body: "Counterparties when the indexer has them. Do not invent USD." },
      { title: "Do not copy blindly", body: "Wallet tracking is not auto-execution unless you sign." },
    ],
    features: ["Holdings", "Flows", "On-Chain pin"],
    useCases: ["Holder drill-down", "KOL check"],
    related: ["token-scanner", "smart-money", "on-chain"],
    prerequisites: ["token-scanner"],
    next: ["smart-money", "holder-analysis"],
    demo: "wallet",
    tags: ["wallet", "on-chain"],
  }),
  node({
    id: "holder-analysis",
    kind: "guide",
    title: "Holder analysis",
    slug: "holder-analysis",
    category: "research",
    description: "Who owns supply, how fresh they are, and why concentration matters.",
    difficulty: "trader",
    estimatedMinutes: 8,
    icon: "users",
    href: "/intel/scan",
    status: "live",
    what: "Holder tables live inside Intel scan and DEX token intel. Use them to see concentration — not to predict price.",
    why: "A 40% top-10 with linked wallets is a different object than a distributed float.",
    when: "During token research, before size.",
    steps: [
      { title: "Open holders", body: "On the scan or token page, open the holders tab." },
      { title: "Top wallets", body: "Click through to wallet research for behavior." },
      { title: "Fresh vs seasoned", body: "New wallets funding from the same source is a research flag, not a crime proof." },
    ],
    features: ["Top holders", "Wallet links"],
    useCases: ["Rug heuristics", "Bundle suspicion"],
    related: ["token-scanner", "wallet-research"],
    prerequisites: ["token-scanner"],
    next: ["smart-money"],
    demo: "scanner",
    tags: ["holders", "distribution"],
  }),
  node({
    id: "smart-money",
    kind: "guide",
    title: "Smart money",
    slug: "smart-money",
    category: "research",
    description: "Whale / KOL desks on Intel and DEX. Directory labels only — no fake Ansem tags.",
    difficulty: "trader",
    estimatedMinutes: 9,
    icon: "whale",
    href: "/intel/whales",
    status: "live",
    what: "/intel/whales and /ORBITX_DEX/kol show whale alerts and labeled KOL wallets from OrbitX's official directory. Unlabeled wallets stay unlabeled. Copy-tracking is informational.",
    why: "People fake KOL calls. OrbitX only labels wallets it actually assigns.",
    when: "When you want flow context after holders.",
    steps: [
      { title: "Open whales / KOL", body: "Intel whales or DEX KOL scanner." },
      { title: "Trust the directory", body: "If a famous name is not in the official KOL list, Education will not promote it." },
      { title: "Still sign yourself", body: "Following a wallet is not auto-buy." },
    ],
    features: ["Whale alerts", "Official KOL directory", "DEX KOL desk"],
    useCases: ["Flow context"],
    related: ["wallet-research", "on-chain", "orbitx-dex"],
    prerequisites: ["wallet-research"],
    next: ["on-chain", "trade-execution"],
    demo: "wallet",
    tags: ["kol", "whales"],
  }),
  node({
    id: "trade-execution",
    kind: "guide",
    title: "Trade execution",
    slug: "trade-execution",
    category: "trading",
    description: "Quotes, slippage, impact, signature, confirmation. You are the signer.",
    difficulty: "trader",
    estimatedMinutes: 8,
    icon: "bolt",
    href: "/ORBITX_DEX",
    status: "live",
    what: "DEX and Trade build a Jupiter quote, you set slippage, you sign. Telegram /buy currently returns a Sign link (auto-sign paused). Failed txs and MEV are market reality.",
    why: "Execution is where money moves. Education stops at process.",
    when: "After research, with a size you can lose.",
    steps: [
      { title: "Quote", body: "Amount in SOL or % of bag. Wait for a quote. No quote = do not guess." },
      { title: "Slippage & impact", body: "Higher slippage increases fill chance and sandwich risk. OrbitX does not pick this for you." },
      { title: "Sign", body: "Wallet popup. Verify mint and amount." },
      { title: "Confirm", body: "Wait for chain confirmation. Portfolio updates after the indexer sees it." },
    ],
    features: ["Jupiter", "Slippage control", "Wallet signature"],
    useCases: ["Buy", "Sell"],
    related: ["orbitx-dex", "trade-app", "telegram-trading"],
    prerequisites: ["orbitx-dex", "connect-wallet"],
    next: ["telegram-trading"],
    demo: "dex",
    tags: ["execution", "slippage"],
  }),
  node({
    id: "on-chain",
    kind: "tool",
    title: "On-Chain world",
    slug: "on-chain",
    category: "onchain",
    description: "Live Solana command center at /on-chain — 250 trending coins, 3D galaxy, events, tx tape, wallet intelligence.",
    difficulty: "trader",
    estimatedMinutes: 10,
    icon: "globe",
    href: "/on-chain",
    status: "live",
    what: "Public living terminal: ticker, live events, breakdown, world/map/orbitx views, recent/OrbitX/whale/KOL tx tabs, wallet track. Empty indexer shows INDEXING DELAY — Education will not invent fills.",
    why: "See chain activity and OrbitX-related flow in one chrome.",
    when: "Watching live flow, pinning a wallet, or teaching someone the mesh.",
    steps: [
      { title: "Open /on-chain", body: "Desktop: trending feed, 3D galaxy, token depth. Mobile: World / Feed / Events / Tx / Wallet." },
      { title: "Read idle honestly", body: "Dashes and INDEXING DELAY mean the indexer has not confirmed data." },
      { title: "Track a wallet", body: "Paste an address in Wallet intelligence." },
    ],
    features: ["Live events", "World map", "Tx tabs", "Wallet pin"],
    useCases: ["Live watch", "Wallet pin"],
    related: ["wallet-research", "smart-money"],
    prerequisites: ["ecosystem-map"],
    next: ["wallet-research"],
    demo: "wallet",
    tags: ["on-chain", "indexer"],
  }),
  node({
    id: "launchpad",
    kind: "tool",
    title: "OrbitX Launchpad",
    slug: "launchpad",
    category: "launch",
    description: "Launch a token on /orbitxlaunch — pump lane or custom Token-2022 lane.",
    difficulty: "creator",
    estimatedMinutes: 14,
    icon: "rocket",
    href: "/orbitxlaunch",
    status: "live",
    what: "Create at /orbitxlaunch/create. Pump lane uses pump.fun style curve. Custom lane mints Token-2022 with transfer fee, metadata, optional Raydium pool. Flat launch fee in SOL (live-priced, promo may be $0). Trading fee 0.45% with 98.7% creator / 1.3% platform at claim.",
    why: "Launch without leaving OrbitX, with anti-vamp checks at create time.",
    when: "You are ready to pay the launch fee and sign a mint transaction.",
    steps: [
      { title: "Choose a lane", body: "/orbitxlaunch/create — Custom or Pump. Read the fee copy on that screen." },
      { title: "Name, symbol, supply, decimals", body: "These hit chain. You do not get a mulligan on mint supply." },
      { title: "Metadata & authorities", body: "Image, description, mint/freeze revoke options. Custom lane can revoke in the launch tx." },
      { title: "Anti-vamp", body: "Look-alike launches can be blocked or have fee authority redirected. That is live launch behavior, not a later toggle." },
      { title: "Sign launch", body: "One (or few) wallet signatures. Failed launch = check the error, do not spam." },
      { title: "Monitor", body: "/orbitxlaunch/token/:mint after it exists." },
    ],
    features: ["Pump lane", "Custom Token-2022", "Anti-vamp", "Registry"],
    useCases: ["First mint", "Fee-on-transfer token"],
    related: ["creating-a-token", "claiming-fees", "anti-vamp"],
    prerequisites: ["connect-wallet"],
    next: ["creating-a-token", "claiming-fees"],
    demo: "launch",
    tags: ["launchpad", "token-2022", "pump"],
  }),
  node({
    id: "creating-a-token",
    kind: "guide",
    title: "Creating a token",
    slug: "creating-a-token",
    category: "launch",
    description: "Name, symbol, supply, decimals, metadata, authorities — then sign.",
    difficulty: "creator",
    estimatedMinutes: 12,
    icon: "coin",
    href: "/orbitxlaunch/create",
    status: "live",
    what: "The create wizards collect identity, art, and authority choices, then build the real mint transaction.",
    why: "Wrong decimals or unrevoked mint authority is a permanent chain fact.",
    when: "After you understand fees and anti-vamp.",
    steps: [
      { title: "Prepare art & copy", body: "Image and description become metadata. Custom lane writes on-chain metadata." },
      { title: "Supply & decimals", body: "Decide before you sign. This is not a UI preference." },
      { title: "Authorities", body: "Mint and freeze: keep or revoke. Understand what you keep." },
      { title: "Launch", body: "Sign. Then open the token page and claim desk." },
    ],
    features: ["Metadata", "Authorities", "Optional LP"],
    useCases: ["Custom mint", "Pump mint"],
    related: ["launchpad", "launch-configuration"],
    prerequisites: ["launchpad"],
    next: ["launch-configuration", "claiming-fees"],
    demo: "launch",
    tags: ["create", "metadata"],
  }),
  node({
    id: "launch-configuration",
    kind: "guide",
    title: "Launch configuration",
    slug: "launch-configuration",
    category: "launch",
    description: "Fees, pool options, and security settings that actually exist on the wizards.",
    difficulty: "creator",
    estimatedMinutes: 8,
    icon: "sliders",
    href: "/orbitxlaunch/create/custom",
    status: "live",
    what: "Custom lane: transfer-fee bps (new launches 45 bps), optional Raydium CPMM, optional LP burn, vanity OBX mint when the UI offers it. Pump lane: pump.fun curve; OrbitX split applies at claim time.",
    why: "Config is the difference between a toy mint and a fee-bearing one.",
    when: "On the create screens, before you click launch.",
    steps: [
      { title: "Read the live fee line", body: "Do not memorize this page — the wizard shows current launch fee in SOL." },
      { title: "Pool", body: "Optional Raydium on custom lane if the wizard exposes it." },
      { title: "Security", body: "Revoke mint/freeze if that is your intent." },
    ],
    features: ["Transfer fee", "Optional pool", "Revokes"],
    useCases: ["Custom launch"],
    related: ["launchpad", "creating-a-token"],
    prerequisites: ["creating-a-token"],
    next: ["launching", "claiming-fees"],
    demo: "launch",
    tags: ["config", "fees"],
  }),
  node({
    id: "launching",
    kind: "guide",
    title: "Launching",
    slug: "launching",
    category: "launch",
    description: "Sign the mint, confirm the registry row, open the token page.",
    difficulty: "creator",
    estimatedMinutes: 6,
    icon: "rocket",
    href: "/orbitxlaunch/create",
    status: "live",
    what: "The launch transaction is the product. Registry powers Home feed, anti-vamp, and Claim.",
    why: "If the tx fails, there is no token. If it lands, you manage from /orbitxlaunch/token/:mint.",
    when: "Final click on create.",
    steps: [
      { title: "Review", body: "Name, symbol, fee, authorities." },
      { title: "Sign", body: "Wallet." },
      { title: "Open token", body: "/orbitxlaunch/token/:mint" },
    ],
    features: ["On-chain mint", "Registry"],
    useCases: ["Go live"],
    related: ["managing-a-launch", "claiming-fees"],
    prerequisites: ["launch-configuration"],
    next: ["managing-a-launch"],
    demo: "launch",
    tags: ["launch"],
  }),
  node({
    id: "managing-a-launch",
    kind: "guide",
    title: "Managing a launch",
    slug: "managing-a-launch",
    category: "launch",
    description: "Token page, profile, portfolio, metadata updates after the mint exists.",
    difficulty: "creator",
    estimatedMinutes: 7,
    icon: "wrench",
    href: "/orbitxlaunch",
    status: "live",
    what: "Post-launch: /orbitxlaunch/token/:mint, profile, portfolio, DEX metadata tool /ORBITX_DEX/metadata (Token Manager). You can only change what authorities still allow.",
    why: "Launch is not the end of the product.",
    when: "After a confirmed mint.",
    steps: [
      { title: "Token page", body: "Chart and holders from live market feeds." },
      { title: "Metadata", body: "If still mutable, use Token Manager / DEX metadata." },
      { title: "Fees", body: "Claim desk — next lesson." },
    ],
    features: ["Token page", "Metadata", "Portfolio"],
    useCases: ["Post-launch ops"],
    related: ["claiming-fees", "orbitx-dex"],
    prerequisites: ["launching"],
    next: ["claiming-fees"],
    demo: "launch",
    tags: ["manage"],
  }),
  node({
    id: "claiming-fees",
    kind: "guide",
    title: "Claiming creator fees",
    slug: "claiming-fees",
    category: "launch",
    description: "Exact claim path at /orbitxlaunch/claim — same wallet that created the token.",
    difficulty: "creator",
    estimatedMinutes: 10,
    icon: "coins",
    href: "/orbitxlaunch/claim",
    status: "live",
    what: "Pump lane: PumpPortal collectCreatorFee — one signature can claim across that wallet's pump coins; OrbitX skims 1.3% in the same tx. Custom lane: withdraw withheld Token-2022 fees, then swap to SOL with the same split. Anti-vamp copies may send fees to platform, not the copycat.",
    why: "Fees do not auto-appear in your SOL balance until you claim.",
    when: "After trades have accrued fees on a token you created.",
    steps: [
      { title: "Connect the creator wallet", body: "Wrong wallet = empty claim. Use the same pubkey that launched.", hotspot: "Connect" },
      { title: "Open Claim", body: "/orbitxlaunch/claim", hotspot: "Claim desk" },
      { title: "Read claimable", body: "Pump shows vault PDA balance. Custom shows withheld fees. If zero, there is nothing to invent.", hotspot: "Balance" },
      { title: "Sign claim", body: "One (or chained) signature. Platform 1.3% is skimmed atomically as documented.", hotspot: "Sign" },
      { title: "Confirm SOL", body: "Check the wallet after confirmation — not a screenshot of hoped-for PnL.", hotspot: "Wallet" },
    ],
    features: ["Pump claim", "Custom withheld withdraw", "98.7 / 1.3 split"],
    useCases: ["Creator payout"],
    related: ["launchpad", "creating-a-token"],
    prerequisites: ["launching"],
    next: ["launchpad"],
    demo: "claim",
    tags: ["fees", "claim"],
  }),
  node({
    id: "anti-vamp",
    kind: "guide",
    title: "Anti-Vamp",
    slug: "anti-vamp",
    category: "launch",
    description: "Originality checks at launch. The /vamp portal is owner-preview; launch-time checks are live.",
    difficulty: "creator",
    estimatedMinutes: 5,
    icon: "shield",
    href: "/orbitxlaunch/create",
    status: "live",
    what: "Launch wizards run anti-vamp checks. Look-alikes can be blocked or have fee authority set to the platform wallet so copycat fees fund buybacks. The standalone /vamp page is owner-preview, not a public tool.",
    why: "Clone launches hurt original creators.",
    when: "During create, if the UI flags a match.",
    steps: [
      { title: "Launch with original identity", body: "Name/ticker/art that collide can trip the check." },
      { title: "Read the block", body: "If launch is blocked, that is the product working." },
    ],
    features: ["Launch-time check", "Fee redirect on copies"],
    useCases: ["Honest launch"],
    related: ["launchpad"],
    prerequisites: ["creating-a-token"],
    next: ["launching"],
    demo: "launch",
    tags: ["anti-vamp"],
  }),
  node({
    id: "telegram-bot",
    kind: "tool",
    title: "Telegram bot",
    slug: "telegram-bot",
    category: "automation",
    description: "Official @theorbitxmcpbot — public groups, wallet-gated DMs.",
    difficulty: "beginner",
    estimatedMinutes: 12,
    icon: "send",
    href: "/telegram",
    status: "live",
    what: "Public groups: intel cards, /token /chart /scan /xray /research /search /screen /wallet /shop. DMs: /login on orbitx.world/telegram, then /buy /sell /trade /launch /tweet /post. Auto-sign is paused — Sign links open the browser wallet.",
    why: "Research in the group chat; never imply the bot silently spent SOL.",
    when: "You already live in Telegram, or you want cards without opening DEX.",
    steps: [
      { title: "Open the bot", body: "t.me/theorbitxmcpbot or /telegram on the site." },
      { title: "Groups are public", body: "Drop a CA. /buy in a group will tell you to DM /login." },
      { title: "Link in DM", body: "/login then connect Jupiter Wallet on /telegram." },
      { title: "Trade with Sign", body: "/buy CA 0.05 sol or buy $1 $ORBITX — then approve in the wallet." },
    ],
    features: ["Public intel", "DM trading", "Shop", "Grok media commands"],
    useCases: ["Group research", "Mobile sign flow"],
    related: ["telegram-trading", "telegram-commands", "orbitx-mcp"],
    prerequisites: ["connect-wallet"],
    next: ["telegram-trading", "telegram-commands"],
    demo: "telegram",
    tags: ["telegram", "bot"],
  }),
  node({
    id: "telegram-trading",
    kind: "guide",
    title: "Telegram trading",
    slug: "telegram-trading",
    category: "automation",
    description: "DM /buy /sell after /login. Sign in the browser wallet. Auto-sign is off.",
    difficulty: "trader",
    estimatedMinutes: 8,
    icon: "send",
    href: "/telegram",
    status: "live",
    what: "Linked DMs can prepare Jupiter buys/sells. You still sign. Groups stay intel-only for spending.",
    why: "Mobile speed without giving the bot custody.",
    when: "After /me shows a linked wallet.",
    steps: [
      { title: "Confirm link", body: "/me in DM." },
      { title: "Buy", body: "/buy CA 0.1 sol or /buy $1 — follow Sign." },
      { title: "Sell", body: "/sell CA 50% (default 100% if omitted)." },
      { title: "Access time", body: "Timed bot access via /burn and /access when that product path is enabled on your account." },
    ],
    features: ["Prepare buy/sell", "Sign link", "Percent sells"],
    useCases: ["Mobile execution"],
    related: ["telegram-bot", "trade-execution"],
    prerequisites: ["telegram-bot"],
    next: ["telegram-commands"],
    demo: "telegram",
    tags: ["telegram", "buy", "sell"],
  }),
  node({
    id: "telegram-commands",
    kind: "guide",
    title: "Telegram commands",
    slug: "telegram-commands",
    category: "automation",
    description: "The live command list shipped by @theorbitxmcpbot — not a fantasy slash menu.",
    difficulty: "beginner",
    estimatedMinutes: 10,
    icon: "list",
    href: "/telegram",
    status: "live",
    what: "Group: /start /help /cmds /ask /token /chart /scan /xray /research /search /screen /wallet /shop /call … DM adds /login /buy /sell /launch /tweet /post /orbitx /credits /burn /access /reset.",
    why: "People invent commands. This lesson only lists what the bot registers.",
    when: "When /help is not enough and you want examples.",
    steps: [
      { title: "Type /cmds", body: "Live catalog in Telegram." },
      { title: "Intel first", body: "/token CA, /chart, /xray before any /buy." },
      { title: "DM for money", body: "/login then spend commands." },
    ],
    features: ["Registered commands only"],
    useCases: ["Cheat sheet"],
    related: ["telegram-bot"],
    prerequisites: ["telegram-bot"],
    next: ["orbitx-mcp"],
    demo: "telegram",
    tags: ["commands"],
  }),
  node({
    id: "orbitx-mcp",
    kind: "tool",
    title: "OrbitX MCP",
    slug: "orbitx-mcp",
    category: "developer",
    subcategory: "automation",
    description: "Agent MCP at /agent — Claude, ChatGPT, Grok with OrbitX tools.",
    difficulty: "advanced",
    estimatedMinutes: 16,
    icon: "cpu",
    href: "/agent",
    status: "live",
    what: "MCP is a tool bridge: the model calls OrbitX tools (search, token, screen, chart, research, prepare buy/sell, launch, shop, burn access). You still sign wallet actions. Access can require burning $ORBITX for timed seats via Shop.",
    why: "Research and workflow from the assistant you already use, without pasting CAs into random plugins.",
    when: "After you understand DEX/Intel, when you want an agent in the loop — not as a magic trader.",
    steps: [
      { title: "What MCP is", body: "Model Context Protocol: structured tools, not a hidden exchange." },
      { title: "Connect", body: "Open /agent, follow Claude / ChatGPT / Grok connector docs on that page." },
      { title: "Auth", body: "orbitx_auth_link / auth_status — paste codes only on OrbitX." },
      { title: "Research tools", body: "orbitx_search, orbitx_get_token, orbitx_screen_*, orbitx_dex_chart, orbitx_research, orbitx_xray." },
      { title: "Trading workflows", body: "orbitx_prepare_buy / prepare_sell then you sign. No silent fills." },
      { title: "Access", body: "orbitx_mcp_access_buy / confirm / status — burn packages from Shop." },
    ],
    features: ["Claude / ChatGPT / Grok", "Research tools", "Prepare-then-sign", "Burn access"],
    useCases: ["Desk copilot", "Launch assist"],
    related: ["mcp-basics", "mcp-advanced", "shop"],
    prerequisites: ["what-is-orbitx", "connect-wallet"],
    next: ["mcp-basics", "shop"],
    demo: "mcp",
    tags: ["mcp", "agent", "developer"],
  }),
  node({
    id: "mcp-basics",
    kind: "guide",
    title: "MCP basics",
    slug: "mcp-basics",
    category: "developer",
    description: "Level 1–3: what it is, connecting, available tool families.",
    difficulty: "advanced",
    estimatedMinutes: 10,
    icon: "cpu",
    href: "/agent",
    status: "live",
    what: "Beginner-friendly MCP: you attach OrbitX as a server. Tools are namespaced orbitx_* and x_*. Telegram MCP does not execute buys.",
    why: "People think MCP is a trading bot. It is a tool list plus your signatures.",
    when: "First Agent page visit.",
    steps: [
      { title: "Open /agent", body: "Pick a client." },
      { title: "Call orbitx_menu", body: "The branded menu lists live families." },
      { title: "Stay on research until linked", body: "Buys require auth + wallet + access policy." },
    ],
    features: ["Menu", "Auth", "Read tools"],
    useCases: ["First connect"],
    related: ["orbitx-mcp", "mcp-advanced"],
    prerequisites: ["orbitx-mcp"],
    next: ["mcp-advanced"],
    demo: "mcp",
    tags: ["mcp"],
  }),
  node({
    id: "mcp-advanced",
    kind: "guide",
    title: "MCP advanced workflows",
    slug: "mcp-advanced-workflows",
    category: "developer",
    description: "Levels 4–6: research loops, prepare-trade, launch, agents.",
    difficulty: "advanced",
    estimatedMinutes: 12,
    icon: "cpu",
    href: "/agent",
    status: "live",
    what: "Chain search → token → xray → prepare_buy. Launch via orbitx_execute_launch (still a wallet openUrl/sign). Grok/X posting is desk-gated (X MCP is owner visibility).",
    why: "Power users want loops, not one-off tools.",
    when: "After MCP basics and a linked wallet.",
    steps: [
      { title: "Research loop", body: "search → get_token → research/xray." },
      { title: "Trade loop", body: "prepare_buy → Sign in wallet → confirm tools if shown." },
      { title: "Launch loop", body: "launch_config → execute_launch." },
      { title: "Access", body: "Burn packages if the tool is blocked on time." },
    ],
    features: ["Chained tools", "Launch", "Access burns"],
    useCases: ["Agent desk"],
    related: ["orbitx-mcp", "shop", "launchpad"],
    prerequisites: ["mcp-basics"],
    next: ["shop"],
    demo: "mcp",
    tags: ["mcp", "advanced"],
  }),
  node({
    id: "shop",
    kind: "tool",
    title: "Shop",
    slug: "shop",
    category: "automation",
    description: "Credits and $ORBITX burn access at /shop.",
    difficulty: "advanced",
    estimatedMinutes: 6,
    icon: "bag",
    href: "/shop",
    status: "live",
    what: "Buy credits with SOL and burn $ORBITX packages for timed MCP/bot access. Burns are on-chain; access expiry is product policy.",
    why: "MCP and some bot paths are gated on verified burns, not a screenshot.",
    when: "When a tool says access required.",
    steps: [
      { title: "Open /shop", body: "Read the live package amounts on that page — Education will not freeze numbers that can change." },
      { title: "Sign the burn/buy", body: "Wallet." },
      { title: "Check status", body: "MCP access_status or Telegram /access." },
    ],
    features: ["Credits", "Burn access"],
    useCases: ["Unlock MCP time"],
    related: ["orbitx-mcp", "telegram-bot"],
    prerequisites: ["connect-wallet"],
    next: ["orbitx-mcp"],
    demo: "mcp",
    tags: ["shop", "burn"],
  }),
  node({
    id: "orbitx-ai",
    kind: "tool",
    title: "OrbitX AI",
    slug: "orbitx-ai",
    category: "automation",
    description: "Wallet-gated AI super app at /ai.",
    difficulty: "trader",
    estimatedMinutes: 7,
    icon: "spark",
    href: "/ai",
    status: "live",
    what: "In-app AI that can use OrbitX tools. Responses can be wrong. Not financial advice.",
    why: "A chat surface inside the product, distinct from Telegram /ask and MCP clients.",
    when: "When you want OrbitX-context chat without leaving the site.",
    steps: [
      { title: "Open /ai", body: "Connect if gated." },
      { title: "Ask for research, not guarantees", body: "Treat answers as drafts." },
    ],
    features: ["In-app chat", "Tool use"],
    useCases: ["Quick brief"],
    related: ["orbitx-mcp", "telegram-bot"],
    prerequisites: ["what-is-orbitx"],
    next: ["orbitx-mcp"],
    demo: "none",
    tags: ["ai"],
  }),
  node({
    id: "intel-desk",
    kind: "tool",
    title: "Intel",
    slug: "intel",
    category: "research",
    description: "Crypto intelligence command center at /intel.",
    difficulty: "trader",
    estimatedMinutes: 8,
    icon: "eye",
    href: "/intel",
    status: "live",
    what: "Home plus scan, trade desk, portfolio, trending, whales, sentiment, launch studio, wallet tracker.",
    why: "Research HQ separate from DEX chrome.",
    when: "Deep work on a mint or wallet.",
    steps: [
      { title: "Open /intel", body: "Pick scan, trending, or whales." },
      { title: "Stay honest about feeds", body: "Sentiment proxies and scores are models." },
    ],
    features: ["Scan", "Trending", "Whales", "Sentiment", "Portfolio"],
    useCases: ["Research session"],
    related: ["token-scanner", "smart-money"],
    prerequisites: ["ecosystem-map"],
    next: ["token-scanner"],
    demo: "scanner",
    tags: ["intel"],
  }),
  node({
    id: "city",
    kind: "tool",
    title: "OrbitX City",
    slug: "city",
    category: "games",
    description: "3D city demo at /Orbitxcity.",
    difficulty: "beginner",
    estimatedMinutes: 5,
    icon: "city",
    href: "/Orbitxcity",
    status: "live",
    what: "Playable 3D city surface. It is a world demo, not a hidden DEX.",
    why: "Spatial overview of the brand world.",
    when: "Exploring the ecosystem visually.",
    steps: [{ title: "Open /Orbitxcity", body: "WebGL required for the 3D path." }],
    features: ["3D world"],
    useCases: ["Tour"],
    related: ["os", "play"],
    prerequisites: [],
    next: ["os"],
    demo: "none",
    tags: ["city"],
  }),
  node({
    id: "os",
    kind: "tool",
    title: "OrbitX OS",
    slug: "os",
    category: "games",
    description: "Desktop launcher shell at /os.",
    difficulty: "beginner",
    estimatedMinutes: 4,
    icon: "os",
    href: "/os",
    status: "live",
    what: "Visual OS that deep-links into live modules. Not a separate backend.",
    why: "A launcher metaphor for the same apps.",
    when: "If you prefer an OS desktop to the Hub grid.",
    steps: [{ title: "Open /os", body: "Use tiles to jump into DEX, launchpad, social, play." }],
    features: ["Launcher tiles"],
    useCases: ["Desktop metaphor"],
    related: ["city", "what-is-orbitx"],
    prerequisites: [],
    next: ["city"],
    demo: "none",
    tags: ["os"],
  }),
  node({
    id: "play",
    kind: "tool",
    title: "Play",
    slug: "play",
    category: "games",
    description: "Games, missions, pass, inventory at /play.",
    difficulty: "beginner",
    estimatedMinutes: 6,
    icon: "play",
    href: "/play",
    status: "live",
    what: "Gaming hub: character, progression, battle pass, inventory, multiplayer stubs. Economy is studio/local until fully wired to chain — Education will not claim on-chain item ownership unless the live page does.",
    why: "Play-to-progress inside OrbitX.",
    when: "You want missions / pass, not a swap.",
    steps: [{ title: "Open /play", body: "Home loadout, then progression or pass." }],
    features: ["Missions", "Pass", "Inventory"],
    useCases: ["Missions"],
    related: ["bagwork", "city"],
    prerequisites: [],
    next: ["bagwork"],
    demo: "none",
    tags: ["play", "games"],
  }),
  node({
    id: "predictions",
    kind: "tool",
    title: "Predictions",
    slug: "predictions",
    category: "prediction",
    description: "YES / NO markets at /predictions.",
    difficulty: "trader",
    estimatedMinutes: 6,
    icon: "dice",
    href: "/predictions",
    status: "live",
    what: "Prediction markets with YES/NO style positions. Treat as speculative. Rules live on the predictions UI — do not invent payout math here.",
    why: "A separate market type from spot DEX.",
    when: "You want event markets, not a token chart.",
    steps: [{ title: "Open /predictions", body: "Read the market rules on that page before you size." }],
    features: ["YES/NO markets"],
    useCases: ["Event speculation"],
    related: ["orbitx-dex"],
    prerequisites: ["connect-wallet"],
    next: ["orbitx-dex"],
    demo: "none",
    tags: ["predictions"],
  }),
  node({
    id: "nft-market",
    kind: "tool",
    title: "NFT Market",
    slug: "nft-market",
    category: "games",
    description: "Mint and trade at /nft.",
    difficulty: "creator",
    estimatedMinutes: 7,
    icon: "image",
    href: "/nft",
    status: "live",
    what: "Explore, drops, activity, create, collections, coin-style NFT trade pages. Minting requires a connected wallet and the live create flow.",
    why: "NFT lane beside token launchpad.",
    when: "Minting or browsing OrbitX NFTs.",
    steps: [
      { title: "Explore", body: "/nft" },
      { title: "Create", body: "/nft/create — follow on-screen mint steps." },
    ],
    features: ["Explore", "Create", "Collections"],
    useCases: ["Mint", "Browse"],
    related: ["launchpad"],
    prerequisites: ["connect-wallet"],
    next: ["launchpad"],
    demo: "none",
    tags: ["nft"],
  }),
  node({
    id: "bagwork",
    kind: "tool",
    title: "Bagwork",
    slug: "bagwork",
    category: "games",
    description: "Earn USDC for tasks at /bagwork.",
    difficulty: "beginner",
    estimatedMinutes: 5,
    icon: "bag",
    href: "/bagwork",
    status: "live",
    what: "Task board for USDC work. Payouts follow whatever the live Bagwork page states — Education will not invent bounty amounts.",
    why: "Earn lane separate from trading.",
    when: "You want tasks, not charts.",
    steps: [{ title: "Open /bagwork", body: "Read available tasks and wallet requirements there." }],
    features: ["Tasks", "My work"],
    useCases: ["Earn"],
    related: ["play"],
    prerequisites: ["connect-wallet"],
    next: ["play"],
    demo: "none",
    tags: ["bagwork", "earn"],
  }),
  node({
    id: "social",
    kind: "tool",
    title: "Social",
    slug: "social",
    category: "social",
    description: "Feed, spaces, communities at /orbitx-social.",
    difficulty: "beginner",
    estimatedMinutes: 6,
    icon: "users",
    href: "/orbitx-social",
    status: "live",
    what: "Live social app. Legacy /hq/* URLs redirect here (except owner moderation). Spaces, profiles, chat — public by design.",
    why: "Community next to trading, not a separate company.",
    when: "Posting, spaces, or following traders.",
    steps: [{ title: "Open /orbitx-social", body: "Feed first; spaces when you want live audio." }],
    features: ["Feed", "Spaces", "Profiles"],
    useCases: ["Community"],
    related: ["telegram-bot"],
    prerequisites: [],
    next: ["telegram-bot"],
    demo: "none",
    tags: ["social", "spaces"],
  }),
  node({
    id: "support",
    kind: "tool",
    title: "Support",
    slug: "support",
    category: "social",
    description: "Tickets and chat at /support.",
    difficulty: "beginner",
    estimatedMinutes: 3,
    icon: "life",
    href: "/support",
    status: "live",
    what: "In-app support center. Also Telegram @orbitxwrld for community, not as a trading hotline.",
    why: "Product issues vs market losses — support cannot reverse a signed swap.",
    when: "Account, bug, or access problems.",
    steps: [{ title: "Open /support", body: "File a ticket with the surface and signature if a tx failed." }],
    features: ["Tickets"],
    useCases: ["Bugs", "Access"],
    related: ["what-is-orbitx"],
    prerequisites: [],
    next: ["what-is-orbitx"],
    demo: "none",
    tags: ["support"],
  }),
  node({
    id: "academy-dex",
    kind: "academy",
    title: "Master the OrbitX DEX",
    slug: "dex",
    category: "trading",
    description: "Full DEX academy: connect, find, read, buy, sell, slippage, portfolio.",
    difficulty: "beginner",
    estimatedMinutes: 18,
    icon: "dex",
    href: "/ORBITX_DEX",
    status: "live",
    what: "A guided tour of the live DEX only.",
    why: "DEX is the densest public surface.",
    when: "You chose the Trader path or the DEX tool card.",
    steps: [
      { title: "What it is", body: "Production DEX app on /ORBITX_DEX." },
      { title: "Connect", body: "Wallet adapter in the DEX chrome." },
      { title: "Find", body: "Search / screener / token URL." },
      { title: "Read", body: "Chart + stats are feeds." },
      { title: "Buy / sell", body: "Quote, slippage, sign." },
      { title: "Portfolio", body: "After confirms." },
    ],
    features: ["Full DEX tour"],
    useCases: ["Academy"],
    related: ["orbitx-dex", "trade-execution"],
    prerequisites: ["connect-wallet"],
    next: ["orbitx-dex"],
    demo: "dex",
    tags: ["academy", "dex"],
  }),
  node({
    id: "academy-launch",
    kind: "academy",
    title: "Launch your token",
    slug: "launch",
    category: "launch",
    description: "Launchpad academy from prepare → claim.",
    difficulty: "creator",
    estimatedMinutes: 20,
    icon: "rocket",
    href: "/orbitxlaunch",
    status: "live",
    what: "Visual path through the live launchpad.",
    why: "Creators skip claim and authorities.",
    when: "Creator path.",
    steps: [
      { title: "Prepare", body: "Identity + art." },
      { title: "Configure", body: "Supply, decimals, authorities, fees." },
      { title: "Launch", body: "Sign." },
      { title: "Claim", body: "/orbitxlaunch/claim." },
    ],
    features: ["End-to-end creator"],
    useCases: ["Academy"],
    related: ["launchpad", "claiming-fees"],
    prerequisites: ["connect-wallet"],
    next: ["launchpad"],
    demo: "launch",
    tags: ["academy", "launch"],
  }),
  node({
    id: "academy-telegram",
    kind: "academy",
    title: "Trade through Telegram",
    slug: "telegram",
    category: "automation",
    description: "Bot academy: public intel, DM login, sign-to-swap.",
    difficulty: "trader",
    estimatedMinutes: 15,
    icon: "send",
    href: "/telegram",
    status: "live",
    what: "Everything the official bot actually registers.",
    why: "Fake command lists get people stuck.",
    when: "Telegram path.",
    steps: [
      { title: "Public intel", body: "Groups." },
      { title: "Login", body: "DM + /telegram." },
      { title: "Sign trades", body: "Auto-sign paused." },
    ],
    features: ["Official commands"],
    useCases: ["Academy"],
    related: ["telegram-bot", "telegram-commands"],
    prerequisites: ["telegram-bot"],
    next: ["telegram-commands"],
    demo: "telegram",
    tags: ["academy", "telegram"],
  }),
  node({
    id: "academy-mcp",
    kind: "academy",
    title: "OrbitX MCP",
    slug: "mcp",
    category: "developer",
    description: "Six-level MCP academy from definition to agents.",
    difficulty: "advanced",
    estimatedMinutes: 22,
    icon: "cpu",
    href: "/agent",
    status: "live",
    what: "Progressive unlock: definition → connect → tools → research → trading workflows → access/agents.",
    why: "MCP looks like magic until you see prepare-then-sign.",
    when: "Power user / developer path.",
    steps: [
      { title: "Level 1", body: "What MCP is." },
      { title: "Level 2", body: "Connecting /agent." },
      { title: "Level 3", body: "Tool families." },
      { title: "Level 4", body: "Research." },
      { title: "Level 5", body: "Prepare trade." },
      { title: "Level 6", body: "Access burns + launch tools." },
    ],
    features: ["Leveled"],
    useCases: ["Academy"],
    related: ["orbitx-mcp", "mcp-advanced"],
    prerequisites: ["orbitx-mcp"],
    next: ["mcp-basics"],
    demo: "mcp",
    tags: ["academy", "mcp"],
  }),
];

export const LEARNING_PATHS: LearningPath[] = [
  {
    id: "beginner",
    slug: "beginner",
    title: "Start here",
    kicker: "Beginner",
    description: "What OrbitX is, wallets, the ecosystem, and a safe first research → quote loop.",
    cta: "Start learning",
    tone: "beginner",
    nodes: ["what-is-orbitx", "getting-started", "connect-wallet", "ecosystem-map", "basic-trading-workflow", "orbitx-dex", "token-discovery"],
  },
  {
    id: "trader",
    slug: "trader",
    title: "Become an OrbitX trader",
    kicker: "Trader",
    description: "Discovery, scanner, holders, wallets, smart money, execution, Telegram, MCP.",
    cta: "Start trading",
    tone: "trader",
    nodes: ["token-discovery", "token-research", "token-scanner", "wallet-research", "holder-analysis", "smart-money", "orbitx-dex", "trade-execution", "telegram-trading", "orbitx-mcp"],
  },
  {
    id: "creator",
    slug: "creator",
    title: "Launch on OrbitX",
    kicker: "Creator",
    description: "Launchpad, configuration, launch, manage, claim fees, anti-vamp.",
    cta: "Learn to launch",
    tone: "creator",
    nodes: ["launchpad", "creating-a-token", "launch-configuration", "launching", "managing-a-launch", "claiming-fees", "anti-vamp"],
  },
  {
    id: "power",
    slug: "power",
    title: "Master OrbitX",
    kicker: "Power user",
    description: "On-chain world, MCP, AI, shop burns, advanced Telegram, agent workflows.",
    cta: "Go advanced",
    tone: "power",
    nodes: ["on-chain", "smart-money", "orbitx-mcp", "mcp-basics", "mcp-advanced", "shop", "orbitx-ai", "telegram-commands"],
  },
];

export const WORKFLOWS: Workflow[] = [
  {
    id: "discovery-to-trade",
    slug: "discovery-to-trade",
    title: "From discovery → trade",
    description: "A visual loop across live OrbitX tools. Nothing here is a profit promise.",
    stages: [
      { id: "discover", title: "Discover", body: "DEX lists, Intel trending, Telegram /screen.", nodeId: "token-discovery", href: "/ORBITX_DEX" },
      { id: "research", title: "Research", body: "Token page + Intel scan.", nodeId: "token-research", href: "/intel/scan" },
      { id: "holders", title: "Check holders", body: "Concentration and linked wallets.", nodeId: "holder-analysis", href: "/intel/scan" },
      { id: "wallets", title: "Check wallets", body: "Holdings and flows.", nodeId: "wallet-research", href: "/on-chain" },
      { id: "smart", title: "Check smart money", body: "Official KOL / whale desks only.", nodeId: "smart-money", href: "/intel/whales" },
      { id: "risk", title: "Analyze risk", body: "Mint, freeze, LP, clone flags — not certainty.", nodeId: "token-scanner", href: "/intel/scan" },
      { id: "watch", title: "Watch", body: "On-chain live tape if the indexer is live.", nodeId: "on-chain", href: "/on-chain" },
      { id: "execute", title: "Execute", body: "DEX or Trade. You sign.", nodeId: "trade-execution", href: "/ORBITX_DEX" },
      { id: "track", title: "Track", body: "Portfolio after confirmation.", nodeId: "trade-app", href: "/trade/portfolio" },
    ],
  },
];

export const DECISION_INTENTS: DecisionIntent[] = [
  { id: "new-token", prompt: "I want to find a new token.", result: "Token discovery", nodeIds: ["token-discovery", "orbitx-dex", "intel-desk"] },
  { id: "wallets-buying", prompt: "I want to see what wallets are buying.", result: "Wallet intelligence", nodeIds: ["wallet-research", "smart-money", "on-chain"] },
  { id: "launch", prompt: "I want to launch a token.", result: "Launchpad", nodeIds: ["launchpad", "creating-a-token", "claiming-fees"] },
  { id: "trade-fast", prompt: "I want to trade quickly.", result: "DEX / Telegram bot", nodeIds: ["orbitx-dex", "trade-app", "telegram-trading"] },
  { id: "ai-help", prompt: "I want AI to help me.", result: "MCP + OrbitX AI", nodeIds: ["orbitx-mcp", "orbitx-ai", "telegram-bot"] },
  { id: "suspicious", prompt: "I want to investigate a suspicious token.", result: "Token forensics", nodeIds: ["token-scanner", "holder-analysis", "anti-vamp"] },
];

export const TELEGRAM_COMMANDS: TelegramCommand[] = [
  { command: "/start", scope: "group", does: "OrbitX desk — coins, charts, Grok, shop.", example: "/start" },
  { command: "/cmds", scope: "group", does: "Desk + live tool catalog.", example: "/cmds" },
  { command: "/token", scope: "group", does: "Premium token intel card.", example: "/token <CA>" },
  { command: "/chart", scope: "group", does: "Live DexScreener + OrbitX DEX chart card.", example: "/chart <CA>" },
  { command: "/scan", scope: "group", does: "Safety + forensics overlay.", example: "/scan <CA>" },
  { command: "/xray", scope: "group", does: "Bundles, whales, mint/freeze.", example: "/xray <CA>" },
  { command: "/research", scope: "group", does: "Utility brief — no hopium.", example: "/research <CA>" },
  { command: "/search", scope: "group", does: "Find a token by ticker / CA.", example: "/search ORBITX" },
  { command: "/screen", scope: "group", does: "Trending Solana pulse.", example: "/screen" },
  { command: "/wallet", scope: "group", does: "Wallet holdings snapshot.", example: "/wallet <address>" },
  { command: "/shop", scope: "group", does: "MCP seats + buy-and-burn shop.", example: "/shop" },
  { command: "/login", scope: "dm", does: "Link your OrbitX wallet via orbitx.world/telegram.", example: "/login" },
  { command: "/buy", scope: "dm", does: "Prepare a token buy — Sign in browser wallet.", example: "/buy <CA> 0.05 sol" },
  { command: "/sell", scope: "dm", does: "Prepare a sell (default 100%).", example: "/sell <CA> 50%" },
  { command: "/launch", scope: "dm", does: "Launch / create token (linked).", example: "/launch" },
  { command: "/orbitx", scope: "dm", does: "Buy $ORBITX (linked).", example: "/orbitx" },
  { command: "/reset", scope: "dm", does: "Unlink and start as a fresh user.", example: "/reset" },
];

export const MAP_CLUSTERS: MapCluster[] = [
  {
    id: "trade",
    label: "Trade",
    nodes: [
      { id: "dex", label: "DEX", href: "/ORBITX_DEX", nodeId: "orbitx-dex" },
      { id: "trade", label: "Trade", href: "/trade", nodeId: "trade-app" },
      { id: "scanner", label: "Token Scanner", href: "/intel/scan", nodeId: "token-scanner" },
      { id: "charts", label: "Charts", href: "/ORBITX_DEX" },
      { id: "portfolio", label: "Portfolio", href: "/trade/portfolio", nodeId: "trade-app" },
      { id: "feed", label: "Trading feed", href: "/ORBITX_DEX" },
    ],
  },
  {
    id: "intel",
    label: "Intelligence",
    nodes: [
      { id: "forensics", label: "Token forensics", href: "/intel/scan", nodeId: "token-scanner" },
      { id: "wallets", label: "Wallet forensics", href: "/on-chain", nodeId: "wallet-research" },
      { id: "holders", label: "Holder analysis", nodeId: "holder-analysis" },
      { id: "smart", label: "Smart money", href: "/intel/whales", nodeId: "smart-money" },
      { id: "risk", label: "Risk analysis", href: "/intel/scan", nodeId: "token-scanner" },
      { id: "onchain", label: "On-chain data", href: "/on-chain", nodeId: "on-chain" },
    ],
  },
  {
    id: "launch",
    label: "Launch",
    nodes: [
      { id: "pad", label: "Launchpad", href: "/orbitxlaunch", nodeId: "launchpad" },
      { id: "create", label: "Token creation", href: "/orbitxlaunch/create", nodeId: "creating-a-token" },
      { id: "t22", label: "Token-2022", href: "/orbitxlaunch/create/custom", nodeId: "launch-configuration" },
      { id: "meta", label: "Metadata", href: "/ORBITX_DEX/metadata", nodeId: "managing-a-launch" },
      { id: "auth", label: "Authorities", nodeId: "creating-a-token" },
      { id: "vamp", label: "Anti-Vamp", nodeId: "anti-vamp" },
      { id: "fees", label: "Creator fees", href: "/orbitxlaunch/claim", nodeId: "claiming-fees" },
    ],
  },
  {
    id: "auto",
    label: "Automation",
    nodes: [
      { id: "tg", label: "Telegram bot", href: "/telegram", nodeId: "telegram-bot" },
      { id: "mcp", label: "MCP", href: "/agent", nodeId: "orbitx-mcp" },
      { id: "ai", label: "AI", href: "/ai", nodeId: "orbitx-ai" },
      { id: "agents", label: "Agents", href: "/agent", nodeId: "orbitx-mcp" },
      { id: "shop", label: "Shop / burns", href: "/shop", nodeId: "shop" },
    ],
  },
  {
    id: "social",
    label: "Social",
    nodes: [
      { id: "social", label: "Communities", href: "/orbitx-social", nodeId: "social" },
      { id: "spaces", label: "Spaces", href: "/orbitx-social", nodeId: "social" },
      { id: "profiles", label: "Profiles", href: "/orbitx-social", nodeId: "social" },
      { id: "support", label: "Support", href: "/support", nodeId: "support" },
    ],
  },
  {
    id: "play",
    label: "Play",
    nodes: [
      { id: "predict", label: "Predictions", href: "/predictions", nodeId: "predictions" },
      { id: "games", label: "Play studio", href: "/play", nodeId: "play" },
      { id: "nft", label: "NFT market", href: "/nft", nodeId: "nft-market" },
      { id: "bag", label: "Bagwork", href: "/bagwork", nodeId: "bagwork" },
      { id: "city", label: "City", href: "/Orbitxcity", nodeId: "city" },
    ],
  },
];

export const MAP_EDGES: [string, string][] = [
  ["scanner", "wallets"],
  ["wallets", "smart"],
  ["smart", "dex"],
  ["dex", "tg"],
  ["pad", "fees"],
  ["mcp", "shop"],
  ["forensics", "risk"],
];

const BY_ID = Object.fromEntries(EDU_NODES.map((n) => [n.id, n]));
const BY_SLUG = Object.fromEntries(EDU_NODES.map((n) => [n.slug, n]));

export function getNode(id: string): EduNode | undefined {
  return BY_ID[id];
}

export function getNodeBySlug(slug: string): EduNode | undefined {
  return BY_SLUG[slug];
}

export function eduHref(n: Pick<EduNode, "kind" | "slug">): string {
  if (n.kind === "tool") return `/education/tools/${n.slug}`;
  if (n.kind === "academy") return `/education/academy/${n.slug}`;
  if (n.kind === "workflow") return `/education/workflow/${n.slug}`;
  return `/education/guides/${n.slug}`;
}

export function findNode(kind: EduNode["kind"], slug: string): EduNode | undefined {
  return EDU_NODES.find((n) => n.published && n.kind === kind && n.slug === slug);
}

export function publishedNodes(): EduNode[] {
  return EDU_NODES.filter((n) => n.published);
}

export function tools(): EduNode[] {
  return publishedNodes().filter((n) => n.kind === "tool" || n.kind === "academy");
}

export function getPath(slug: string): LearningPath | undefined {
  return LEARNING_PATHS.find((p) => p.slug === slug);
}

export function getWorkflow(slug: string): Workflow | undefined {
  return WORKFLOWS.find((w) => w.slug === slug);
}

export const CATEGORY_FILTERS: { id: "all" | EduNode["category"]; label: string }[] = [
  { id: "all", label: "All" },
  { id: "trading", label: "Trading" },
  { id: "research", label: "Research" },
  { id: "onchain", label: "On-chain" },
  { id: "launch", label: "Launch" },
  { id: "automation", label: "Automation" },
  { id: "social", label: "Social" },
  { id: "prediction", label: "Prediction" },
  { id: "games", label: "Games" },
  { id: "developer", label: "Developer" },
];
