import type { ComponentType } from "react";
import {
  BellRing,
  Brain,
  Briefcase,
  Building2,
  Code2,
  Film,
  Link2,
  Mic,
  Radio,
  Rocket,
  Shield,
  ShieldCheck,
  Signal,
  Smartphone,
  Sparkles,
  Twitter,
  Crosshair,
  Palette,
} from "lucide-react";
import { OWNER_DESK_HREF, OWNER_DESK_PATH } from "@/lib/ownerDesk";

export interface AdminAppDef {
  key: string;
  to: string;
  label: string;
  caption: string;
  eyebrow: string;
  description: string;
  group: "desks" | "ops" | "spaces";
  icon: ComponentType<{ className?: string }>;
  /** Hub icon gradient */
  tone: string;
  iconBg: string;
  emoji?: string;
}

/** All owner-only admin apps. Visible on /app only for audifyx@gmail.com. */
export const ADMIN_APPS: AdminAppDef[] = [
  // ── Platform desks ──
  {
    key: "owner-desk",
    to: OWNER_DESK_HREF,
    label: "Owner Desk",
    caption: "Global ops",
    eyebrow: "Platform HQ",
    description: "Users, moderation, analytics, settings, and every owner ops section.",
    group: "desks",
    icon: Shield,
    tone: "#F0C75E",
    iconBg: "linear-gradient(135deg, #F0C75E, #B8860B)",
    emoji: "🛡️",
  },
  {
    key: "launchpad-desk",
    to: `/orbitxlaunch/${OWNER_DESK_PATH}`,
    label: "Launchpad Desk",
    caption: "Tokens & fees",
    eyebrow: "OrbitX Launch",
    description: "Feature/hide tokens, fee desk, Launch V2 / Bagworking moderation, and fee jobs.",
    group: "desks",
    icon: Rocket,
    tone: "#60A5FA",
    iconBg: "linear-gradient(135deg, #60A5FA, #1D4ED8)",
    emoji: "🚀",
  },
  {
    key: "onchain-proof",
    to: "/onchain",
    label: "On-chain proof",
    caption: "Verify + costs",
    eyebrow: "Blockchain first",
    description: "Verify signatures on Solana, rebuild the memo index, and open the owner cost desk.",
    group: "ops",
    icon: Link2,
    tone: "#60A5FA",
    iconBg: "linear-gradient(135deg, #60A5FA, #1D4ED8)",
    emoji: "🔗",
  },
  {
    key: "bagwork-admin",
    to: "/bagwork/admin",
    label: "Bagwork Admin",
    caption: "Tasks & USDC",
    eyebrow: "Earn desk",
    description: "Create tasks, set USDC prices, review submissions, mark paid.",
    group: "desks",
    icon: Briefcase,
    tone: "#D4AF37",
    iconBg: "linear-gradient(135deg, #D4AF37, #8B6914)",
    emoji: "💼",
  },
  {
    key: "hq-mod",
    to: `/hq/${OWNER_DESK_PATH}`,
    label: "HQ Moderation",
    caption: "Social desk",
    eyebrow: "OrbitX HQ",
    description: "Moderate social HQ content, reports, and community ops.",
    group: "desks",
    icon: ShieldCheck,
    tone: "#A78BFA",
    iconBg: "linear-gradient(135deg, #A78BFA, #5B21B6)",
    emoji: "⚖️",
  },
  {
    key: "intel-desk",
    to: `${OWNER_DESK_HREF}/intel`,
    label: "Intel Admin",
    caption: "Crypto intel",
    eyebrow: "/intel",
    description: "Intelligence admin for crypto intel surfaces.",
    group: "desks",
    icon: Crosshair,
    tone: "#34D399",
    iconBg: "linear-gradient(135deg, #34D399, #047857)",
    emoji: "🎯",
  },
  {
    key: "dex-desk",
    to: `/ORBITX_DEX/${OWNER_DESK_PATH}`,
    label: "DEX Desk",
    caption: "DEX owner",
    eyebrow: "OrbitX DEX",
    description: "Owner desk inside the DEX sub-app.",
    group: "desks",
    icon: Shield,
    tone: "#2F80FF",
    iconBg: "linear-gradient(135deg, #2F80FF, #0037A3)",
    emoji: "📈",
  },

  // ── Ops apps ──
  {
    key: "mobile-app",
    to: "/mobile-app",
    label: "Mobile App",
    caption: "iOS & Android",
    eyebrow: "Native",
    description: "Manage native app rollout and install messaging.",
    group: "ops",
    icon: Smartphone,
    tone: "#22D3EE",
    iconBg: "linear-gradient(135deg, #22D3EE, #0E7490)",
    emoji: "📱",
  },
  {
    key: "reminders",
    to: "/reminders",
    label: "Space Reminders",
    caption: "Push + email",
    eyebrow: "Notifications",
    description: "Reminder delivery and timing for scheduled spaces.",
    group: "ops",
    icon: BellRing,
    tone: "#FBBF24",
    iconBg: "linear-gradient(135deg, #FBBF24, #B45309)",
    emoji: "🔔",
  },
  {
    key: "auto-tweet",
    to: "/auto-tweet",
    label: "Auto-Tweet",
    caption: "Go-live posting",
    eyebrow: "X / Twitter",
    description: "Automatic posting when spaces go live.",
    group: "ops",
    icon: Twitter,
    tone: "#38BDF8",
    iconBg: "linear-gradient(135deg, #38BDF8, #0369A1)",
    emoji: "🐦",
  },
  {
    key: "podcasts",
    to: "/podcasts",
    label: "Podcast Publisher",
    caption: "RSS distribution",
    eyebrow: "Audio",
    description: "Publish sessions into podcast feeds.",
    group: "ops",
    icon: Mic,
    tone: "#E879F9",
    iconBg: "linear-gradient(135deg, #E879F9, #A21CAF)",
    emoji: "🎙️",
  },
  {
    key: "clip-export",
    to: "/clip-export",
    label: "Clip → Video",
    caption: "Social exports",
    eyebrow: "Media",
    description: "Turn clips into export-ready videos.",
    group: "ops",
    icon: Film,
    tone: "#34D399",
    iconBg: "linear-gradient(135deg, #34D399, #065F46)",
    emoji: "🎬",
  },
  {
    key: "white-label",
    to: "/white-label",
    label: "White Label",
    caption: "Brand config",
    eyebrow: "Brand",
    description: "White-label / brand configuration for the suite.",
    group: "ops",
    icon: Palette,
    tone: "#F472B6",
    iconBg: "linear-gradient(135deg, #F472B6, #9D174D)",
    emoji: "🎨",
  },
  {
    key: "enterprise",
    to: "/enterprise",
    label: "Enterprise",
    caption: "Compliance",
    eyebrow: "HIPAA + SSO",
    description: "Enterprise and compliance-oriented settings.",
    group: "ops",
    icon: Building2,
    tone: "#FB923C",
    iconBg: "linear-gradient(135deg, #FB923C, #C2410C)",
    emoji: "🏢",
  },
  {
    key: "dev-portal",
    to: "/dev-portal",
    label: "Developer Portal",
    caption: "API & webhooks",
    eyebrow: "Builders",
    description: "API docs, webhooks, and marketplace tools.",
    group: "ops",
    icon: Code2,
    tone: "#818CF8",
    iconBg: "linear-gradient(135deg, #818CF8, #3730A3)",
    emoji: "⚙️",
  },

  // ── Spaces & AI ──
  {
    key: "discovery",
    to: "/discovery",
    label: "Live Spaces",
    caption: "Discovery feed",
    eyebrow: "Spaces",
    description: "Browse and manage live audio spaces.",
    group: "spaces",
    icon: Radio,
    tone: "#22D3EE",
    iconBg: "linear-gradient(135deg, #22D3EE, #155E75)",
    emoji: "📡",
  },
  {
    key: "shows",
    to: "/shows",
    label: "Shows",
    caption: "Series",
    eyebrow: "Podcast-style",
    description: "Manage shows and episode scheduling.",
    group: "spaces",
    icon: Radio,
    tone: "#A78BFA",
    iconBg: "linear-gradient(135deg, #A78BFA, #5B21B6)",
    emoji: "📻",
  },
  {
    key: "ai-assistant",
    to: "/ai-assistant",
    label: "AI Assistant",
    caption: "Transcripts",
    eyebrow: "Spaces AI",
    description: "Transcription, notes, and post-session assistance.",
    group: "spaces",
    icon: Brain,
    tone: "#4ADE80",
    iconBg: "linear-gradient(135deg, #4ADE80, #166534)",
    emoji: "🧠",
  },
  {
    key: "host-copilot",
    to: "/host-copilot",
    label: "Host Copilot",
    caption: "Live coaching",
    eyebrow: "Spaces AI",
    description: "Live guidance tools for space hosts.",
    group: "spaces",
    icon: Sparkles,
    tone: "#FBBF24",
    iconBg: "linear-gradient(135deg, #FBBF24, #92400E)",
    emoji: "✨",
  },
  {
    key: "simulcast",
    to: "/simulcast",
    label: "Simulcast",
    caption: "Broadcast",
    eyebrow: "Multi-platform",
    description: "Multi-platform broadcast workflows.",
    group: "spaces",
    icon: Signal,
    tone: "#F472B6",
    iconBg: "linear-gradient(135deg, #F472B6, #9D174D)",
    emoji: "📶",
  },
];

export const ADMIN_APP_GROUPS = [
  { id: "desks" as const, label: "Platform desks", description: "Owner desks across Launchpad, Bagwork, HQ, Intel, and DEX." },
  { id: "ops" as const, label: "Ops apps", description: "Mobile, publishing, brand, enterprise, and developer tools." },
  { id: "spaces" as const, label: "Spaces & AI", description: "Live spaces, shows, and host AI tools." },
];
