import type { WorldBlockConfig } from "./types";

/**
 * OrbitX NYC — Milestone 1 playable city block.
 * One crossroads with HQ, Meme Market, Launch Arena, Trading Floor,
 * Social Hub, and Advertising District billboards.
 */
export const NYC_DEMO_BLOCK: WorldBlockConfig = {
  cityId: "nyc",
  name: "OrbitX City · Midtown Block",
  spawn: { x: 0, y: 0, z: 8 },
  bounds: { minX: -28, maxX: 28, minZ: -28, maxZ: 28 },
  districts: [
    {
      id: "hq",
      cityId: "nyc",
      kind: "hq",
      name: "OrbitX HQ",
      description: "Main headquarters and world entry plaza.",
      center: { x: 0, y: 0, z: -14 },
      size: { width: 16, depth: 12 },
    },
    {
      id: "meme",
      cityId: "nyc",
      kind: "meme_market",
      name: "Meme Market",
      description: "Discover and buy real meme coins from virtual storefronts.",
      center: { x: -14, y: 0, z: 0 },
      size: { width: 14, depth: 14 },
    },
    {
      id: "launch",
      cityId: "nyc",
      kind: "launch",
      name: "Launch Arena",
      description: "Live token launches powered by OrbitX Launchpad.",
      center: { x: 14, y: 0, z: 0 },
      size: { width: 14, depth: 14 },
    },
    {
      id: "trading",
      cityId: "nyc",
      kind: "trading",
      name: "Trading Floor",
      description: "Live charts, market activity, trader energy.",
      center: { x: 0, y: 0, z: 14 },
      size: { width: 16, depth: 12 },
    },
    {
      id: "social",
      cityId: "nyc",
      kind: "social",
      name: "Social District",
      description: "Communities and conversations.",
      center: { x: -14, y: 0, z: 14 },
      size: { width: 12, depth: 10 },
    },
    {
      id: "ads",
      cityId: "nyc",
      kind: "advertising",
      name: "Advertising District",
      description: "Project billboards and sponsored skyline.",
      center: { x: 14, y: 0, z: 14 },
      size: { width: 12, depth: 10 },
    },
  ],
  buildings: [
    {
      id: "b-hq",
      districtId: "hq",
      kind: "hq",
      name: "OrbitX HQ",
      position: { x: 0, y: 0, z: -16 },
      size: { width: 10, height: 14, depth: 8 },
      color: "#0a1628",
      accent: "#17ff4d",
      interaction: "hq",
      label: "HQ",
    },
    {
      id: "b-market",
      districtId: "meme",
      kind: "market",
      name: "Meme Market",
      position: { x: -16, y: 0, z: -2 },
      size: { width: 9, height: 7, depth: 9 },
      color: "#12101a",
      accent: "#ff4d9a",
      interaction: "marketplace",
      label: "MARKET",
    },
    {
      id: "b-shop-a",
      districtId: "meme",
      kind: "shop",
      name: "Token Boutique",
      position: { x: -16, y: 0, z: 10 },
      size: { width: 5, height: 5, depth: 5 },
      color: "#151820",
      accent: "#3de7ff",
      interaction: "marketplace",
      label: "SHOP",
    },
    {
      id: "b-launch",
      districtId: "launch",
      kind: "launch_arena",
      name: "Launch Arena",
      position: { x: 16, y: 0, z: -2 },
      size: { width: 10, height: 9, depth: 10 },
      color: "#140f08",
      accent: "#f5c542",
      interaction: "launch",
      label: "LAUNCH",
    },
    {
      id: "b-floor",
      districtId: "trading",
      kind: "trading_floor",
      name: "Trading Floor",
      position: { x: 0, y: 0, z: 18 },
      size: { width: 12, height: 8, depth: 8 },
      color: "#081418",
      accent: "#3de7ff",
      interaction: "trading",
      label: "TRADE",
    },
    {
      id: "b-social",
      districtId: "social",
      kind: "social_hub",
      name: "Social Hub",
      position: { x: -16, y: 0, z: 20 },
      size: { width: 7, height: 6, depth: 7 },
      color: "#10141c",
      accent: "#a78bfa",
      interaction: "community",
      label: "SOCIAL",
    },
    {
      id: "b-adtower",
      districtId: "ads",
      kind: "ad_tower",
      name: "Ad Tower",
      position: { x: 18, y: 0, z: 18 },
      size: { width: 5, height: 16, depth: 5 },
      color: "#0c0c14",
      accent: "#17ff4d",
      interaction: "billboard",
      label: "ADS",
    },
  ],
  billboards: [
    {
      id: "bb-1",
      position: { x: -8, y: 5, z: -10 },
      rotationY: Math.PI / 6,
      width: 6,
      height: 3.2,
      title: "ORBITX",
      subtitle: "Trade the metaverse",
      accent: "#17ff4d",
      projectName: "OrbitX",
    },
    {
      id: "bb-2",
      position: { x: 8, y: 4.5, z: -8 },
      rotationY: -Math.PI / 5,
      width: 5.5,
      height: 3,
      title: "MEME MARKET",
      subtitle: "Real coins · real wallets",
      accent: "#ff4d9a",
      projectName: "Meme Market",
    },
    {
      id: "bb-3",
      position: { x: 12, y: 6, z: 10 },
      rotationY: Math.PI * 0.85,
      width: 5,
      height: 2.8,
      title: "LAUNCH LIVE",
      subtitle: "Create on OrbitX Launchpad",
      accent: "#f5c542",
      projectName: "Launch Arena",
    },
    {
      id: "bb-4",
      position: { x: -10, y: 5.5, z: 12 },
      rotationY: -Math.PI * 0.7,
      width: 5.2,
      height: 2.9,
      title: "SCANNER",
      subtitle: "Origin intel before you ape",
      accent: "#3de7ff",
      projectName: "OrbitX Scanner",
    },
  ],
  zones: [
    {
      id: "z-hq",
      kind: "hq",
      label: "OrbitX HQ",
      hint: "Enter headquarters · world map & profile",
      position: { x: 0, y: 0, z: -10 },
      radius: 4.5,
      buildingId: "b-hq",
    },
    {
      id: "z-market",
      kind: "marketplace",
      label: "Meme Market",
      hint: "Browse live OrbitX tokens",
      position: { x: -16, y: 0, z: 4 },
      radius: 5,
      buildingId: "b-market",
    },
    {
      id: "z-launch",
      kind: "launch",
      label: "Launch Arena",
      hint: "Open OrbitX Launchpad",
      position: { x: 16, y: 0, z: 4 },
      radius: 5,
      buildingId: "b-launch",
    },
    {
      id: "z-trade",
      kind: "trading",
      label: "Trading Floor",
      hint: "Live market tape & charts",
      position: { x: 0, y: 0, z: 12 },
      radius: 5,
      buildingId: "b-floor",
    },
    {
      id: "z-social",
      kind: "community",
      label: "Social Hub",
      hint: "Communities & conversations",
      position: { x: -16, y: 0, z: 16 },
      radius: 4,
      buildingId: "b-social",
    },
  ],
};

/** Simple AABB colliders derived from buildings (expanded footprint). */
export function buildingColliders(block: WorldBlockConfig) {
  return block.buildings.map((b) => ({
    minX: b.position.x - b.size.width / 2 - 0.4,
    maxX: b.position.x + b.size.width / 2 + 0.4,
    minZ: b.position.z - b.size.depth / 2 - 0.4,
    maxZ: b.position.z + b.size.depth / 2 + 0.4,
  }));
}
