-- OrbitX Curve (EVM) — bonding-curve markets + trade ledger.
-- Backs the keyless curve launches from contracts/evm/OrbitXCurve.sol.
-- Launched tokens still land in public.orbitx_tokens (launch_type = 'evm-curve');
-- these tables add curve-specific market state and a per-trade history.

create table if not exists public.orbitx_curve_markets (
  token_address      text primary key,
  chain              text not null,
  factory_address    text not null,
  creator_wallet     text not null,
  name               text,
  symbol             text,
  fee_bps            integer,
  creator_fee_bps    integer,
  virtual_native     numeric,
  graduation_native  numeric,
  real_native        numeric default 0,
  token_reserve      numeric,
  price_x1e18        numeric,
  graduated          boolean not null default false,
  launch_tx          text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index if not exists idx_orbitx_curve_markets_chain on public.orbitx_curve_markets(chain);
create index if not exists idx_orbitx_curve_markets_creator on public.orbitx_curve_markets(creator_wallet);
create index if not exists idx_orbitx_curve_markets_graduated on public.orbitx_curve_markets(graduated);

create table if not exists public.orbitx_curve_trades (
  id             bigint generated by default as identity primary key,
  token_address  text not null references public.orbitx_curve_markets(token_address) on delete cascade,
  chain          text not null,
  trader_wallet  text not null,
  side           text not null check (side in ('buy','sell')),
  native_amount  numeric not null,
  token_amount   numeric not null,
  price_x1e18    numeric,
  tx_hash        text not null,
  block_time     timestamptz,
  created_at     timestamptz not null default now()
);
create unique index if not exists uq_orbitx_curve_trades_tx on public.orbitx_curve_trades(tx_hash, side);
create index if not exists idx_orbitx_curve_trades_token on public.orbitx_curve_trades(token_address);
create index if not exists idx_orbitx_curve_trades_trader on public.orbitx_curve_trades(trader_wallet);

alter table public.orbitx_curve_markets enable row level security;
alter table public.orbitx_curve_trades  enable row level security;

-- Public, on-chain data: readable by everyone; inserts allowed from the client
-- (mirrors how orbitx_tokens is written on launch). Tighten to service-role-only
-- once an indexer backfills these tables from chain events.
drop policy if exists "public read curve markets" on public.orbitx_curve_markets;
create policy "public read curve markets" on public.orbitx_curve_markets for select using (true);
drop policy if exists "public insert curve markets" on public.orbitx_curve_markets;
create policy "public insert curve markets" on public.orbitx_curve_markets for insert with check (true);
drop policy if exists "public update curve markets" on public.orbitx_curve_markets;
create policy "public update curve markets" on public.orbitx_curve_markets for update using (true) with check (true);

drop policy if exists "public read curve trades" on public.orbitx_curve_trades;
create policy "public read curve trades" on public.orbitx_curve_trades for select using (true);
drop policy if exists "public insert curve trades" on public.orbitx_curve_trades;
create policy "public insert curve trades" on public.orbitx_curve_trades for insert with check (true);
