-- Performance fixes applied via Supabase advisor (2026-06-21)
-- 1) Add covering indexes for 210 foreign keys lacking them (faster joins/filters/deletes)
-- 2) Optimize 589 RLS policies: wrap auth.<fn>()/current_setting() in (select ...)
--    so they are evaluated once per query instead of once per row.
-- Both changes were generated from catalog state and applied idempotently.
-- See generated statements in repo history / advisor output.
CREATE INDEX IF NOT EXISTS ix_abuse_flags_user_id ON public.abuse_flags (user_id);
CREATE INDEX IF NOT EXISTS ix_admin_audit_log_admin_user_id ON public.admin_audit_log (admin_user_id);
CREATE INDEX IF NOT EXISTS ix_admin_data_sources_updated_by ON public.admin_data_sources (updated_by);
CREATE INDEX IF NOT EXISTS ix_admin_moderation_queue_reporter_id ON public.admin_moderation_queue (reporter_id);
CREATE INDEX IF NOT EXISTS ix_admin_moderation_queue_assigned_to ON public.admin_moderation_queue (assigned_to);
CREATE INDEX IF NOT EXISTS ix_admin_moderation_queue_resolved_by ON public.admin_moderation_queue (resolved_by);
CREATE INDEX IF NOT EXISTS ix_admin_roles_granted_by ON public.admin_roles (granted_by);
CREATE INDEX IF NOT EXISTS ix_admin_tasks_created_by ON public.admin_tasks (created_by);
CREATE INDEX IF NOT EXISTS ix_affiliates_user_id ON public.affiliates (user_id);
CREATE INDEX IF NOT EXISTS ix_alpha_callout_upvotes_user_id ON public.alpha_callout_upvotes (user_id);
CREATE INDEX IF NOT EXISTS ix_alpha_callouts_user_id ON public.alpha_callouts (user_id);
CREATE INDEX IF NOT EXISTS ix_alpha_discussions_parent_id ON public.alpha_discussions (parent_id);
CREATE INDEX IF NOT EXISTS ix_announcements_created_by ON public.announcements (created_by);
CREATE INDEX IF NOT EXISTS ix_app_settings_updated_by ON public.app_settings (updated_by);
CREATE INDEX IF NOT EXISTS ix_audio_room_participants_user_id ON public.audio_room_participants (user_id);
CREATE INDEX IF NOT EXISTS ix_audio_rooms_host_id ON public.audio_rooms (host_id);
CREATE INDEX IF NOT EXISTS ix_audit_logs_admin_id ON public.audit_logs (admin_id);
CREATE INDEX IF NOT EXISTS ix_bookmark_collections_user_id ON public.bookmark_collections (user_id);
CREATE INDEX IF NOT EXISTS ix_bookmarks_post_id ON public.bookmarks (post_id);
CREATE INDEX IF NOT EXISTS ix_callouts_user_id ON public.callouts (user_id);
CREATE INDEX IF NOT EXISTS ix_chat_messages_user_id ON public.chat_messages (user_id);
CREATE INDEX IF NOT EXISTS ix_chat_tracked_wallets_added_by ON public.chat_tracked_wallets (added_by);
CREATE INDEX IF NOT EXISTS ix_clip_likes_user_id ON public.clip_likes (user_id);
CREATE INDEX IF NOT EXISTS ix_communities_owner_id ON public.communities (owner_id);
CREATE INDEX IF NOT EXISTS ix_community_bans_user_id ON public.community_bans (user_id);
CREATE INDEX IF NOT EXISTS ix_community_feature_events_feature_id ON public.community_feature_events (feature_id);
CREATE INDEX IF NOT EXISTS ix_community_feature_events_actor_id ON public.community_feature_events (actor_id);
CREATE INDEX IF NOT EXISTS ix_community_feature_settings_feature_id ON public.community_feature_settings (feature_id);
CREATE INDEX IF NOT EXISTS ix_community_feature_settings_updated_by ON public.community_feature_settings (updated_by);
CREATE INDEX IF NOT EXISTS ix_community_holder_rules_created_by ON public.community_holder_rules (created_by);
CREATE INDEX IF NOT EXISTS ix_community_holder_verification_log_user_id ON public.community_holder_verification_log (user_id);
CREATE INDEX IF NOT EXISTS ix_community_invites_invited_by_user_id ON public.community_invites (invited_by_user_id);
CREATE INDEX IF NOT EXISTS ix_community_join_requests_user_id ON public.community_join_requests (user_id);
CREATE INDEX IF NOT EXISTS ix_community_join_requests_resolved_by ON public.community_join_requests (resolved_by);
CREATE INDEX IF NOT EXISTS ix_community_keyword_filters_created_by ON public.community_keyword_filters (created_by);
CREATE INDEX IF NOT EXISTS ix_community_messages_community_id ON public.community_messages (community_id);
CREATE INDEX IF NOT EXISTS ix_community_poll_votes_user_id ON public.community_poll_votes (user_id);
CREATE INDEX IF NOT EXISTS ix_community_post_comments_post_id ON public.community_post_comments (post_id);
CREATE INDEX IF NOT EXISTS ix_community_post_comments_user_id ON public.community_post_comments (user_id);
CREATE INDEX IF NOT EXISTS ix_community_post_reactions_user_id ON public.community_post_reactions (user_id);
CREATE INDEX IF NOT EXISTS ix_community_post_replies_user_id ON public.community_post_replies (user_id);
CREATE INDEX IF NOT EXISTS ix_community_raid_participants_user_id ON public.community_raid_participants (user_id);
CREATE INDEX IF NOT EXISTS ix_community_raids_creator_id ON public.community_raids (creator_id);
CREATE INDEX IF NOT EXISTS ix_community_raids_community_id ON public.community_raids (community_id);
CREATE INDEX IF NOT EXISTS ix_community_raids_created_by ON public.community_raids (created_by);
CREATE INDEX IF NOT EXISTS ix_community_roles_user_id ON public.community_roles (user_id);
CREATE INDEX IF NOT EXISTS ix_community_room_bans_user_id ON public.community_room_bans (user_id);
CREATE INDEX IF NOT EXISTS ix_community_room_bans_moderator_id ON public.community_room_bans (moderator_id);
CREATE INDEX IF NOT EXISTS ix_community_room_members_user_id ON public.community_room_members (user_id);
CREATE INDEX IF NOT EXISTS ix_community_room_members_custom_role_id ON public.community_room_members (custom_role_id);
CREATE INDEX IF NOT EXISTS ix_community_room_messages_sender_id ON public.community_room_messages (sender_id);
CREATE INDEX IF NOT EXISTS ix_community_room_messages_reply_to_id ON public.community_room_messages (reply_to_id);
CREATE INDEX IF NOT EXISTS ix_community_room_messages_quote_message_id ON public.community_room_messages (quote_message_id);
CREATE INDEX IF NOT EXISTS ix_community_room_moderation_actions_moderator_id ON public.community_room_moderation_actions (moderator_id);
CREATE INDEX IF NOT EXISTS ix_community_room_moderation_actions_target_user_id ON public.community_room_moderation_actions (target_user_id);
CREATE INDEX IF NOT EXISTS ix_community_room_moderation_actions_message_id ON public.community_room_moderation_actions (message_id);
CREATE INDEX IF NOT EXISTS ix_community_room_mutes_user_id ON public.community_room_mutes (user_id);
CREATE INDEX IF NOT EXISTS ix_community_room_mutes_moderator_id ON public.community_room_mutes (moderator_id);
CREATE INDEX IF NOT EXISTS ix_community_room_reports_message_id ON public.community_room_reports (message_id);
CREATE INDEX IF NOT EXISTS ix_community_room_reports_reported_user_id ON public.community_room_reports (reported_user_id);
CREATE INDEX IF NOT EXISTS ix_community_room_reports_reporter_id ON public.community_room_reports (reporter_id);
CREATE INDEX IF NOT EXISTS ix_community_room_reports_resolved_by ON public.community_room_reports (resolved_by);
CREATE INDEX IF NOT EXISTS ix_community_room_roles_created_by ON public.community_room_roles (created_by);
CREATE INDEX IF NOT EXISTS ix_community_room_warnings_room_id ON public.community_room_warnings (room_id);
CREATE INDEX IF NOT EXISTS ix_community_room_warnings_user_id ON public.community_room_warnings (user_id);
CREATE INDEX IF NOT EXISTS ix_community_room_warnings_moderator_id ON public.community_room_warnings (moderator_id);
CREATE INDEX IF NOT EXISTS ix_community_rooms_linked_space_id ON public.community_rooms (linked_space_id);
CREATE INDEX IF NOT EXISTS ix_community_rooms_created_by ON public.community_rooms (created_by);
CREATE INDEX IF NOT EXISTS ix_community_token_scans_scanned_by ON public.community_token_scans (scanned_by);
CREATE INDEX IF NOT EXISTS ix_community_user_reputation_user_id ON public.community_user_reputation (user_id);
CREATE INDEX IF NOT EXISTS ix_community_x_spaces_user_id ON public.community_x_spaces (user_id);
CREATE INDEX IF NOT EXISTS ix_content_takedowns_target_user_id ON public.content_takedowns (target_user_id);
CREATE INDEX IF NOT EXISTS ix_content_takedowns_removed_by ON public.content_takedowns (removed_by);
CREATE INDEX IF NOT EXISTS ix_content_takedowns_restored_by ON public.content_takedowns (restored_by);
CREATE INDEX IF NOT EXISTS ix_crypto_news_reactions_news_id ON public.crypto_news_reactions (news_id);
CREATE INDEX IF NOT EXISTS ix_crypto_news_saves_news_id ON public.crypto_news_saves (news_id);
CREATE INDEX IF NOT EXISTS ix_developer_webhooks_user_id ON public.developer_webhooks (user_id);
CREATE INDEX IF NOT EXISTS ix_dm_attachments_user_id ON public.dm_attachments (user_id);
CREATE INDEX IF NOT EXISTS ix_dm_message_reactions_user_id ON public.dm_message_reactions (user_id);
CREATE INDEX IF NOT EXISTS ix_dm_reactions_user_id ON public.dm_reactions (user_id);
CREATE INDEX IF NOT EXISTS ix_dm_screenshot_events_conversation_id ON public.dm_screenshot_events (conversation_id);
CREATE INDEX IF NOT EXISTS ix_dm_screenshot_events_actor_id ON public.dm_screenshot_events (actor_id);
CREATE INDEX IF NOT EXISTS ix_dm_screenshot_events_message_id ON public.dm_screenshot_events (message_id);
CREATE INDEX IF NOT EXISTS ix_dm_typing_user_id ON public.dm_typing (user_id);
CREATE INDEX IF NOT EXISTS ix_ecosystem_events_user_id ON public.ecosystem_events (user_id);
CREATE INDEX IF NOT EXISTS ix_email_verifications_user_id ON public.email_verifications (user_id);
CREATE INDEX IF NOT EXISTS ix_enhanced_price_alerts_user_id ON public.enhanced_price_alerts (user_id);
CREATE INDEX IF NOT EXISTS ix_events_host_id ON public.events (host_id);
CREATE INDEX IF NOT EXISTS ix_events_created_by ON public.events (created_by);
CREATE INDEX IF NOT EXISTS ix_feed_cache_user_id ON public.feed_cache (user_id);
CREATE INDEX IF NOT EXISTS ix_handle_listings_handle ON public.handle_listings (handle);
CREATE INDEX IF NOT EXISTS ix_handle_listings_seller_id ON public.handle_listings (seller_id);
CREATE INDEX IF NOT EXISTS ix_handle_listings_buyer_id ON public.handle_listings (buyer_id);
CREATE INDEX IF NOT EXISTS ix_handle_transfers_handle ON public.handle_transfers (handle);
CREATE INDEX IF NOT EXISTS ix_handle_transfers_from_user_id ON public.handle_transfers (from_user_id);
CREATE INDEX IF NOT EXISTS ix_handle_transfers_to_user_id ON public.handle_transfers (to_user_id);
CREATE INDEX IF NOT EXISTS ix_handles_owner_id ON public.handles (owner_id);
CREATE INDEX IF NOT EXISTS ix_holder_rewards_required_tier_id ON public.holder_rewards (required_tier_id);
CREATE INDEX IF NOT EXISTS ix_kol_transactions_kol_wallet_id ON public.kol_transactions (kol_wallet_id);
CREATE INDEX IF NOT EXISTS ix_launch_upvotes_submission_id ON public.launch_upvotes (submission_id);
CREATE INDEX IF NOT EXISTS ix_likes_post_id ON public.likes (post_id);
CREATE INDEX IF NOT EXISTS ix_live_feed_events_related_user_id ON public.live_feed_events (related_user_id);
CREATE INDEX IF NOT EXISTS ix_live_presence_user_id ON public.live_presence (user_id);
CREATE INDEX IF NOT EXISTS ix_livekit_participants_user_id ON public.livekit_participants (user_id);
CREATE INDEX IF NOT EXISTS ix_livekit_participants_removed_by ON public.livekit_participants (removed_by);
CREATE INDEX IF NOT EXISTS ix_livekit_rooms_community_id ON public.livekit_rooms (community_id);
CREATE INDEX IF NOT EXISTS ix_lobby_members_user_id ON public.lobby_members (user_id);
CREATE INDEX IF NOT EXISTS ix_lobby_messages_lobby_id ON public.lobby_messages (lobby_id);
CREATE INDEX IF NOT EXISTS ix_lobby_messages_user_id ON public.lobby_messages (user_id);
CREATE INDEX IF NOT EXISTS ix_lobby_watchlists_lobby_id ON public.lobby_watchlists (lobby_id);
CREATE INDEX IF NOT EXISTS ix_lobby_watchlists_added_by ON public.lobby_watchlists (added_by);
CREATE INDEX IF NOT EXISTS ix_marketplace_apps_developer_id ON public.marketplace_apps (developer_id);
CREATE INDEX IF NOT EXISTS ix_message_reactions_user_id ON public.message_reactions (user_id);
CREATE INDEX IF NOT EXISTS ix_messages_reply_to_id ON public.messages (reply_to_id);
CREATE INDEX IF NOT EXISTS ix_moderation_reports_reporter_id ON public.moderation_reports (reporter_id);
CREATE INDEX IF NOT EXISTS ix_moderation_reports_assigned_to ON public.moderation_reports (assigned_to);
CREATE INDEX IF NOT EXISTS ix_moderation_reports_resolved_by ON public.moderation_reports (resolved_by);
CREATE INDEX IF NOT EXISTS ix_news_comments_external_id ON public.news_comments (external_id);
CREATE INDEX IF NOT EXISTS ix_news_comments_user_id ON public.news_comments (user_id);
CREATE INDEX IF NOT EXISTS ix_news_likes_user_id ON public.news_likes (user_id);
CREATE INDEX IF NOT EXISTS ix_news_reposts_user_id ON public.news_reposts (user_id);
CREATE INDEX IF NOT EXISTS ix_notification_digest_user_id ON public.notification_digest (user_id);
CREATE INDEX IF NOT EXISTS ix_notification_dispatch_queue_notification_id ON public.notification_dispatch_queue (notification_id);
CREATE INDEX IF NOT EXISTS ix_notification_dispatch_queue_user_id ON public.notification_dispatch_queue (user_id);
CREATE INDEX IF NOT EXISTS ix_notifications_actor_id ON public.notifications (actor_id);
CREATE INDEX IF NOT EXISTS ix_og_xp_events_user_id ON public.og_xp_events (user_id);
CREATE INDEX IF NOT EXISTS ix_paper_orders_user_id ON public.paper_orders (user_id);
CREATE INDEX IF NOT EXISTS ix_password_reset_tokens_user_id ON public.password_reset_tokens (user_id);
CREATE INDEX IF NOT EXISTS ix_platform_settings_updated_by ON public.platform_settings (updated_by);
CREATE INDEX IF NOT EXISTS ix_pnl_positions_user_id ON public.pnl_positions (user_id);
CREATE INDEX IF NOT EXISTS ix_poll_options_poll_id ON public.poll_options (poll_id);
CREATE INDEX IF NOT EXISTS ix_poll_votes_option_id ON public.poll_votes (option_id);
CREATE INDEX IF NOT EXISTS ix_poll_votes_voter_id ON public.poll_votes (voter_id);
CREATE INDEX IF NOT EXISTS ix_polls_author_id ON public.polls (author_id);
CREATE INDEX IF NOT EXISTS ix_portfolio_snapshots_user_id ON public.portfolio_snapshots (user_id);
CREATE INDEX IF NOT EXISTS ix_post_drafts_user_id ON public.post_drafts (user_id);
CREATE INDEX IF NOT EXISTS ix_post_hashtags_tag ON public.post_hashtags (tag);
CREATE INDEX IF NOT EXISTS ix_post_reports_reviewed_by ON public.post_reports (reviewed_by);
CREATE INDEX IF NOT EXISTS ix_posts_parent_post_id ON public.posts (parent_post_id);
CREATE INDEX IF NOT EXISTS ix_posts_repost_of_id ON public.posts (repost_of_id);
CREATE INDEX IF NOT EXISTS ix_posts_user_id ON public.posts (user_id);
CREATE INDEX IF NOT EXISTS ix_profiles_referred_by ON public.profiles (referred_by);
CREATE INDEX IF NOT EXISTS ix_pump_v5_submissions_approved_by ON public.pump_v5_submissions (approved_by);
CREATE INDEX IF NOT EXISTS ix_pump_v5_submissions_featured_by ON public.pump_v5_submissions (featured_by);
CREATE INDEX IF NOT EXISTS ix_raid_participants_user_id ON public.raid_participants (user_id);
CREATE INDEX IF NOT EXISTS ix_reactivation_campaigns_user_id ON public.reactivation_campaigns (user_id);
CREATE INDEX IF NOT EXISTS ix_reel_comments_user_id ON public.reel_comments (user_id);
CREATE INDEX IF NOT EXISTS ix_reel_likes_user_id ON public.reel_likes (user_id);
CREATE INDEX IF NOT EXISTS ix_reel_shares_user_id ON public.reel_shares (user_id);
CREATE INDEX IF NOT EXISTS ix_reel_views_viewer_id ON public.reel_views (viewer_id);
CREATE INDEX IF NOT EXISTS ix_referrals_code ON public.referrals (code);
CREATE INDEX IF NOT EXISTS ix_reward_claims_user_id ON public.reward_claims (user_id);
CREATE INDEX IF NOT EXISTS ix_reward_claims_mission_id ON public.reward_claims (mission_id);
CREATE INDEX IF NOT EXISTS ix_share_link_clicks_viewer_id ON public.share_link_clicks (viewer_id);
CREATE INDEX IF NOT EXISTS ix_show_follows_user_id ON public.show_follows (user_id);
CREATE INDEX IF NOT EXISTS ix_site_settings_updated_by ON public.site_settings (updated_by);
CREATE INDEX IF NOT EXISTS ix_social_messages_user_id ON public.social_messages (user_id);
CREATE INDEX IF NOT EXISTS ix_social_streams_host_id ON public.social_streams (host_id);
CREATE INDEX IF NOT EXISTS ix_social_voice_rooms_created_by ON public.social_voice_rooms (created_by);
CREATE INDEX IF NOT EXISTS ix_space_backstage_messages_sender_id ON public.space_backstage_messages (sender_id);
CREATE INDEX IF NOT EXISTS ix_space_highlights_space_id ON public.space_highlights (space_id);
CREATE INDEX IF NOT EXISTS ix_space_invites_invited_by ON public.space_invites (invited_by);
CREATE INDEX IF NOT EXISTS ix_space_messages_user_id ON public.space_messages (user_id);
CREATE INDEX IF NOT EXISTS ix_space_participant_blocks_blocked_by ON public.space_participant_blocks (blocked_by);
CREATE INDEX IF NOT EXISTS ix_space_polls_space_id ON public.space_polls (space_id);
CREATE INDEX IF NOT EXISTS ix_space_qa_questions_space_id ON public.space_qa_questions (space_id);
CREATE INDEX IF NOT EXISTS ix_space_reactions_user_id ON public.space_reactions (user_id);
CREATE INDEX IF NOT EXISTS ix_space_reports_target_user_id ON public.space_reports (target_user_id);
CREATE INDEX IF NOT EXISTS ix_space_reports_resolved_by ON public.space_reports (resolved_by);
CREATE INDEX IF NOT EXISTS ix_spaces_show_id ON public.spaces (show_id);
CREATE INDEX IF NOT EXISTS ix_speaker_requests_user_id ON public.speaker_requests (user_id);
CREATE INDEX IF NOT EXISTS ix_story_replies_story_id ON public.story_replies (story_id);
CREATE INDEX IF NOT EXISTS ix_story_replies_author_id ON public.story_replies (author_id);
CREATE INDEX IF NOT EXISTS ix_suggested_follows_suggested_user_id ON public.suggested_follows (suggested_user_id);
CREATE INDEX IF NOT EXISTS ix_support_tickets_v2_user_id ON public.support_tickets_v2 (user_id);
CREATE INDEX IF NOT EXISTS ix_support_tickets_v2_assignee_id ON public.support_tickets_v2 (assignee_id);
CREATE INDEX IF NOT EXISTS ix_team_actions_log_team_user_id ON public.team_actions_log (team_user_id);
CREATE INDEX IF NOT EXISTS ix_token_listings_listed_by ON public.token_listings (listed_by);
CREATE INDEX IF NOT EXISTS ix_trading_lobbies_created_by ON public.trading_lobbies (created_by);
CREATE INDEX IF NOT EXISTS ix_trading_lobbies_host_id ON public.trading_lobbies (host_id);
CREATE INDEX IF NOT EXISTS ix_user_badges_badge_id ON public.user_badges (badge_id);
CREATE INDEX IF NOT EXISTS ix_user_holder_status_current_tier_id ON public.user_holder_status (current_tier_id);
CREATE INDEX IF NOT EXISTS ix_user_interests_topic_slug ON public.user_interests (topic_slug);
CREATE INDEX IF NOT EXISTS ix_user_limits_updated_by ON public.user_limits (updated_by);
CREATE INDEX IF NOT EXISTS ix_user_moderation_state_updated_by ON public.user_moderation_state (updated_by);
CREATE INDEX IF NOT EXISTS ix_user_quests_quest_id ON public.user_quests (quest_id);
CREATE INDEX IF NOT EXISTS ix_user_reports_reported_by_id ON public.user_reports (reported_by_id);
CREATE INDEX IF NOT EXISTS ix_user_reports_reported_post_id ON public.user_reports (reported_post_id);
CREATE INDEX IF NOT EXISTS ix_user_reports_resolved_by_id ON public.user_reports (resolved_by_id);
CREATE INDEX IF NOT EXISTS ix_user_reward_claims_reward_id ON public.user_reward_claims (reward_id);
CREATE INDEX IF NOT EXISTS ix_user_suspensions_created_by ON public.user_suspensions (created_by);
CREATE INDEX IF NOT EXISTS ix_user_webhooks_user_id ON public.user_webhooks (user_id);
CREATE INDEX IF NOT EXISTS ix_voice_lobbies_host_id ON public.voice_lobbies (host_id);
CREATE INDEX IF NOT EXISTS ix_voice_lobby_clips_lobby_id ON public.voice_lobby_clips (lobby_id);
CREATE INDEX IF NOT EXISTS ix_voice_lobby_clips_created_by ON public.voice_lobby_clips (created_by);
CREATE INDEX IF NOT EXISTS ix_voice_lobby_events_lobby_id ON public.voice_lobby_events (lobby_id);
CREATE INDEX IF NOT EXISTS ix_voice_lobby_events_user_id ON public.voice_lobby_events (user_id);
CREATE INDEX IF NOT EXISTS ix_voice_lobby_invites_lobby_id ON public.voice_lobby_invites (lobby_id);
CREATE INDEX IF NOT EXISTS ix_voice_lobby_invites_inviter_id ON public.voice_lobby_invites (inviter_id);
CREATE INDEX IF NOT EXISTS ix_voice_lobby_invites_invitee_id ON public.voice_lobby_invites (invitee_id);
CREATE INDEX IF NOT EXISTS ix_voice_lobby_messages_user_id ON public.voice_lobby_messages (user_id);
CREATE INDEX IF NOT EXISTS ix_voice_lobby_reactions_user_id ON public.voice_lobby_reactions (user_id);
CREATE INDEX IF NOT EXISTS ix_voice_lobby_watchlist_added_by ON public.voice_lobby_watchlist (added_by);
CREATE INDEX IF NOT EXISTS ix_voice_speaker_queue_lobby_id ON public.voice_speaker_queue (lobby_id);
CREATE INDEX IF NOT EXISTS ix_voice_speaker_queue_user_id ON public.voice_speaker_queue (user_id);
CREATE INDEX IF NOT EXISTS ix_wallet_alert_events_user_id ON public.wallet_alert_events (user_id);
CREATE INDEX IF NOT EXISTS ix_wallet_alerts_user_id ON public.wallet_alerts (user_id);
CREATE INDEX IF NOT EXISTS ix_wallet_security_events_wallet_id ON public.wallet_security_events (wallet_id);
CREATE INDEX IF NOT EXISTS ix_webhooks_user_id ON public.webhooks (user_id);
CREATE INDEX IF NOT EXISTS ix_whitelabel_configs_owner_id ON public.whitelabel_configs (owner_id);

-- RLS initplan optimization (applied via DO block):
DO $$
DECLARE
  r record;
  nq text; nc text; do_q boolean; do_c boolean; stmt text; cnt int := 0;
  re1 constant text := '\(\s*select\s+(auth\.(uid|jwt|role)\(\)|current_setting\([^)]*\))\s*\)';
  re2 constant text := '(auth\.(uid|jwt|role)\(\)|current_setting\([^)]*\))';
BEGIN
  FOR r IN SELECT schemaname, tablename, policyname, qual, with_check
           FROM pg_policies WHERE schemaname='public'
  LOOP
    do_q := false; do_c := false; nq := NULL; nc := NULL;
    IF r.qual IS NOT NULL THEN
      nq := regexp_replace(regexp_replace(r.qual, re1, '\1','gi'), re2, '(select \1)','gi');
      do_q := (nq <> r.qual);
    END IF;
    IF r.with_check IS NOT NULL THEN
      nc := regexp_replace(regexp_replace(r.with_check, re1, '\1','gi'), re2, '(select \1)','gi');
      do_c := (nc <> r.with_check);
    END IF;
    IF do_q AND do_c THEN
      stmt := format('ALTER POLICY %I ON %I.%I USING (%s) WITH CHECK (%s)', r.policyname, r.schemaname, r.tablename, nq, nc);
    ELSIF do_q THEN
      stmt := format('ALTER POLICY %I ON %I.%I USING (%s)', r.policyname, r.schemaname, r.tablename, nq);
    ELSIF do_c THEN
      stmt := format('ALTER POLICY %I ON %I.%I WITH CHECK (%s)', r.policyname, r.schemaname, r.tablename, nc);
    ELSE
      CONTINUE;
    END IF;
    EXECUTE stmt;
    cnt := cnt + 1;
  END LOOP;
  RAISE NOTICE 'Updated % policies', cnt;
END $$;
