import type { StreetSegment, WorldBlockConfig } from "../types";
import { FARTCOIN_CANONICAL_MINT, OGSCAN_TOKEN_MINT } from "@/lib/og";

/** LA is a horizontal creator strip: studios, games, NFT galleries, and a central stage. */
export const LA_STREETS: StreetSegment[] = [
  { o: "h", at: 0, from: -52, to: 52, w: 7, curbA: "#ff4d9a", curbB: "#a78bfa" },
  { o: "h", at: 24, from: -46, to: 46, w: 5, curbA: "#ff8bd1", curbB: "#3de7ff" },
  { o: "h", at: -24, from: -46, to: 46, w: 5, curbA: "#f5c542", curbB: "#ff4d9a" },
  { o: "v", at: -28, from: -34, to: 34, w: 5, curbA: "#a78bfa", curbB: "#ff4d9a" },
  { o: "v", at: 0, from: -34, to: 34, w: 6, curbA: "#ff4d9a", curbB: "#f5c542" },
  { o: "v", at: 28, from: -34, to: 34, w: 5, curbA: "#3de7ff", curbB: "#ff8bd1" },
];

export const LA_TELEPORT_POINTS: Array<{ id: string; label: string; x: number; z: number; accent: string }> = [
  { id: "la-stage", label: "Creator Stage Plaza", x: 0, z: 9, accent: "#ff4d9a" },
  { id: "la-strip-west", label: "Creator Strip West", x: -34, z: 2, accent: "#a78bfa" },
  { id: "la-strip-east", label: "Creator Strip East", x: 34, z: 2, accent: "#3de7ff" },
  { id: "la-nft", label: "Melrose NFT Gallery", x: -28, z: -18, accent: "#ff8bd1" },
  { id: "la-games", label: "Arcade Backlot", x: 28, z: -18, accent: "#f5c542" },
  { id: "la-social", label: "Rooftop Social", x: 0, z: 27, accent: "#a78bfa" },
];

export const LA_BLOCK: WorldBlockConfig = {
  cityId: "la",
  name: "OrbitX City · LA Creator Strip",
  spawn: { x: 0, y: 0, z: 9 },
  bounds: { minX: -56, maxX: 56, minZ: -42, maxZ: 44 },
  districts: [
    {
      id: "la-stage",
      cityId: "la",
      kind: "creator",
      name: "Creator Stage Plaza",
      description: "Magenta-lit outdoor stage for creator drops, demos, and live events.",
      center: { x: 0, y: 0, z: 10 },
      size: { width: 24, depth: 18 },
    },
    {
      id: "la-strip-west",
      cityId: "la",
      kind: "creator",
      name: "Creator Strip West",
      description: "Studio storefronts for content teams and project marketing.",
      center: { x: -34, y: 0, z: 2 },
      size: { width: 24, depth: 24 },
    },
    {
      id: "la-strip-east",
      cityId: "la",
      kind: "advertising",
      name: "Creator Strip East",
      description: "Billboard-heavy media strip with token ads and sponsored screens.",
      center: { x: 34, y: 0, z: 2 },
      size: { width: 24, depth: 24 },
    },
    {
      id: "la-nft",
      cityId: "la",
      kind: "creator",
      name: "Melrose NFT Gallery",
      description: "NFT exhibits and collector lounges set behind the main strip.",
      center: { x: -28, y: 0, z: -22 },
      size: { width: 24, depth: 18 },
    },
    {
      id: "la-games",
      cityId: "la",
      kind: "community",
      name: "Arcade Backlot",
      description: "Games, predictions, and playable community challenges.",
      center: { x: 28, y: 0, z: -22 },
      size: { width: 24, depth: 18 },
    },
    {
      id: "la-social",
      cityId: "la",
      kind: "social",
      name: "Rooftop Social Row",
      description: "Rooftop lounges and voice rooms overlooking the creator strip.",
      center: { x: 0, y: 0, z: 28 },
      size: { width: 42, depth: 18 },
    },
  ],
  buildings: [
    {
      id: "la-b-stage",
      districtId: "la-stage",
      kind: "launch_arena",
      name: "Creator Stage",
      position: { x: 0, y: 0, z: 18 },
      size: { width: 14, height: 7, depth: 8 },
      color: "#3d1832",
      accent: "#ff4d9a",
      interaction: "launch",
      label: "STAGE",
    },
    {
      id: "la-b-plaza",
      districtId: "la-stage",
      kind: "plaza",
      name: "Premiere Plaza",
      position: { x: 0, y: 0, z: -8 },
      size: { width: 8, height: 3, depth: 8 },
      color: "#211935",
      accent: "#a78bfa",
      interaction: "community",
      label: "PLAZA",
    },
    {
      id: "la-b-studio-a",
      districtId: "la-strip-west",
      kind: "social_hub",
      name: "Creator Studio A",
      position: { x: -38, y: 0, z: 8 },
      size: { width: 10, height: 7, depth: 8 },
      color: "#2a2344",
      accent: "#a78bfa",
      interaction: "community",
      label: "STUDIO A",
    },
    {
      id: "la-b-podcast",
      districtId: "la-strip-west",
      kind: "shop",
      name: "Podcast Row",
      position: { x: -38, y: 0, z: -9 },
      size: { width: 9, height: 5.5, depth: 7 },
      color: "#381d35",
      accent: "#ff8bd1",
      interaction: "voice",
      label: "PODCAST",
    },
    {
      id: "la-b-media",
      districtId: "la-strip-east",
      kind: "ad_tower",
      name: "Media Tower",
      position: { x: 38, y: 0, z: 8 },
      size: { width: 8, height: 14, depth: 7 },
      color: "#251a38",
      accent: "#ff4d9a",
      interaction: "billboard",
      label: "MEDIA",
    },
    {
      id: "la-b-brand",
      districtId: "la-strip-east",
      kind: "shop",
      name: "Brand Collab House",
      position: { x: 38, y: 0, z: -9 },
      size: { width: 9, height: 6, depth: 7 },
      color: "#163145",
      accent: "#3de7ff",
      interaction: "community",
      label: "COLLAB",
    },
    {
      id: "la-b-nft",
      districtId: "la-nft",
      kind: "generic",
      name: "Melrose NFT Gallery",
      position: { x: -30, y: 0, z: -28 },
      size: { width: 12, height: 7.5, depth: 8 },
      color: "#402046",
      accent: "#ff8bd1",
      interaction: "nft",
      label: "NFT",
    },
    {
      id: "la-b-collectors",
      districtId: "la-nft",
      kind: "shop",
      name: "Collector Lounge",
      position: { x: -14, y: 0, z: -28 },
      size: { width: 7, height: 5, depth: 6 },
      color: "#241c3c",
      accent: "#a78bfa",
      interaction: "nft",
      label: "LOUNGE",
    },
    {
      id: "la-b-arcade",
      districtId: "la-games",
      kind: "generic",
      name: "Arcade Backlot",
      position: { x: 30, y: 0, z: -28 },
      size: { width: 12, height: 7, depth: 8 },
      color: "#3f2f12",
      accent: "#f5c542",
      interaction: "games",
      label: "ARCADE",
    },
    {
      id: "la-b-esports",
      districtId: "la-games",
      kind: "generic",
      name: "Games Arena",
      position: { x: 14, y: 0, z: -28 },
      size: { width: 8, height: 6, depth: 7 },
      color: "#173146",
      accent: "#3de7ff",
      interaction: "games",
      label: "GAMES",
    },
    {
      id: "la-b-rooftop",
      districtId: "la-social",
      kind: "social_hub",
      name: "Rooftop Social",
      position: { x: -12, y: 0, z: 31 },
      size: { width: 10, height: 8, depth: 7 },
      color: "#271f3f",
      accent: "#a78bfa",
      interaction: "voice",
      label: "ROOFTOP",
    },
    {
      id: "la-b-afterparty",
      districtId: "la-social",
      kind: "plaza",
      name: "Afterparty Deck",
      position: { x: 12, y: 0, z: 31 },
      size: { width: 10, height: 5.5, depth: 7 },
      color: "#451d36",
      accent: "#ff4d9a",
      interaction: "community",
      label: "PARTY",
    },
  ],
  billboards: [
    {
      id: "la-bb-stage",
      position: { x: -8, y: 5.2, z: 14 },
      rotationY: Math.PI / 7,
      width: 6,
      height: 3.2,
      title: "CREATOR LIVE",
      subtitle: "Drops · streams · premieres",
      accent: "#ff4d9a",
      projectName: "Creator Stage",
      tokenMint: OGSCAN_TOKEN_MINT,
      website: "https://orbitx.world",
    },
    {
      id: "la-bb-nft",
      position: { x: -24, y: 4.7, z: -16 },
      rotationY: -Math.PI * 0.18,
      width: 5.4,
      height: 3,
      title: "MELROSE NFT",
      subtitle: "Gallery openings nightly",
      accent: "#ff8bd1",
      projectName: "Melrose NFT Gallery",
    },
    {
      id: "la-bb-games",
      position: { x: 24, y: 4.7, z: -16 },
      rotationY: Math.PI * 0.18,
      width: 5.4,
      height: 3,
      title: "BACKLOT GAMES",
      subtitle: "Arcade · predictions · duels",
      accent: "#f5c542",
      projectName: "Arcade Backlot",
      tokenMint: FARTCOIN_CANONICAL_MINT,
    },
    {
      id: "la-bb-strip",
      position: { x: 42, y: 6.2, z: 1 },
      rotationY: -Math.PI / 2,
      width: 6.2,
      height: 3.4,
      title: "ORBITX LA",
      subtitle: "Creator strip ad network",
      accent: "#3de7ff",
      projectName: "Media Tower",
    },
  ],
  zones: [
    {
      id: "la-z-stage",
      kind: "launch",
      label: "Creator Stage",
      hint: "Open creator launch events and premieres",
      position: { x: 0, y: 0, z: 13 },
      radius: 5.4,
      buildingId: "la-b-stage",
    },
    {
      id: "la-z-plaza",
      kind: "community",
      label: "Premiere Plaza",
      hint: "Meet creators before the next drop",
      position: { x: 0, y: 0, z: -2 },
      radius: 4.8,
      buildingId: "la-b-plaza",
    },
    {
      id: "la-z-studio",
      kind: "community",
      label: "Creator Studio A",
      hint: "Join creator teams and collab rooms",
      position: { x: -38, y: 0, z: 13 },
      radius: 4.5,
      buildingId: "la-b-studio-a",
    },
    {
      id: "la-z-social",
      kind: "voice",
      label: "Rooftop Social",
      hint: "Enter the LA voice lounge",
      position: { x: -12, y: 0, z: 25 },
      radius: 4.5,
      buildingId: "la-b-rooftop",
    },
    {
      id: "la-z-nft",
      kind: "nft",
      label: "Melrose NFT Gallery",
      hint: "Browse NFT exhibits and collector rooms",
      position: { x: -30, y: 0, z: -21 },
      radius: 4.8,
      buildingId: "la-b-nft",
    },
    {
      id: "la-z-games",
      kind: "games",
      label: "Arcade Backlot",
      hint: "Play OrbitX games and prediction duels",
      position: { x: 30, y: 0, z: -21 },
      radius: 4.8,
      buildingId: "la-b-arcade",
    },
    {
      id: "la-z-token",
      kind: "token",
      label: "Creator Live Billboard",
      hint: "View live OrbitX token details",
      position: { x: -8, y: 0, z: 12 },
      radius: 3.5,
      tokenMint: OGSCAN_TOKEN_MINT,
    },
  ],
  landmarks: [
    {
      id: "la-creator-stage-landmark",
      modelId: "landmark-la",
      position: { x: 0, y: 0, z: 8 },
      rotationY: Math.PI,
      size: { width: 14, height: 8, depth: 6 },
      label: "CREATOR STAGE",
    },
  ],
};
