import type { StreetSegment, WorldBlockConfig } from "../types";
import { OGSCAN_TOKEN_MINT } from "@/lib/og";

/** Miami keeps the center open: boardwalk, plazas, and low pastel community spaces. */
export const MIAMI_STREETS: StreetSegment[] = [
  { o: "h", at: 28, from: -48, to: 48, w: 7, curbA: "#3de7ff", curbB: "#ff8bd1" },
  { o: "h", at: 4, from: -44, to: 44, w: 6, curbA: "#7fffd4", curbB: "#3de7ff" },
  { o: "v", at: -18, from: -38, to: 42, w: 5, curbA: "#ffd166", curbB: "#3de7ff" },
  { o: "v", at: 18, from: -38, to: 42, w: 5, curbA: "#ff8bd1", curbB: "#7fffd4" },
  { o: "h", at: -24, from: -34, to: 34, w: 5, curbA: "#a7f3d0", curbB: "#3de7ff" },
];

export const MIAMI_TELEPORT_POINTS: Array<{ id: string; label: string; x: number; z: number; accent: string }> = [
  { id: "miami-arrival", label: "Ocean Arrival Plaza", x: 0, z: 18, accent: "#3de7ff" },
  { id: "miami-boardwalk", label: "Neon Boardwalk", x: -4, z: 32, accent: "#ff8bd1" },
  { id: "miami-community", label: "Community Cabana", x: -30, z: 15, accent: "#7fffd4" },
  { id: "miami-social", label: "Social Sands", x: 24, z: 8, accent: "#3de7ff" },
  { id: "miami-market", label: "Coastal Market", x: -28, z: -18, accent: "#ffd166" },
  { id: "miami-launch", label: "Sunset Launch Pier", x: 22, z: -18, accent: "#ff8bd1" },
];

export const MIAMI_BLOCK: WorldBlockConfig = {
  cityId: "miami",
  name: "OrbitX City · Miami Coast",
  spawn: { x: 0, y: 0, z: 18 },
  bounds: { minX: -52, maxX: 52, minZ: -44, maxZ: 48 },
  districts: [
    {
      id: "miami-arrival",
      cityId: "miami",
      kind: "hq",
      name: "Ocean Arrival Plaza",
      description: "Open coastal spawn plaza with pastel OrbitX signage and beach views.",
      center: { x: 0, y: 0, z: 18 },
      size: { width: 20, depth: 18 },
    },
    {
      id: "miami-boardwalk",
      cityId: "miami",
      kind: "social",
      name: "Neon Boardwalk",
      description: "Beach-adjacent promenade for voice rooms, meetups, and live token boards.",
      center: { x: 0, y: 0, z: 34 },
      size: { width: 48, depth: 14 },
    },
    {
      id: "miami-community",
      cityId: "miami",
      kind: "community",
      name: "Community Cabanas",
      description: "DAO lounges, partner cabanas, and public community programming.",
      center: { x: -28, y: 0, z: 4 },
      size: { width: 20, depth: 24 },
    },
    {
      id: "miami-social",
      cityId: "miami",
      kind: "social",
      name: "Social Sands",
      description: "Open-air lounges and music spaces built around group hangouts.",
      center: { x: 28, y: 0, z: 4 },
      size: { width: 20, depth: 24 },
    },
    {
      id: "miami-market",
      cityId: "miami",
      kind: "meme_market",
      name: "Coastal Token Market",
      description: "Low-rise storefronts for token discovery near the marina.",
      center: { x: -24, y: 0, z: -22 },
      size: { width: 24, depth: 18 },
    },
    {
      id: "miami-launch",
      cityId: "miami",
      kind: "launch",
      name: "Sunset Launch Pier",
      description: "Outdoor launch deck with bright cyan and coral stage lighting.",
      center: { x: 24, y: 0, z: -22 },
      size: { width: 24, depth: 18 },
    },
  ],
  buildings: [
    {
      id: "miami-b-hq",
      districtId: "miami-arrival",
      kind: "hq",
      name: "Ocean Orbit HQ",
      position: { x: 0, y: 0, z: 8 },
      size: { width: 11, height: 9, depth: 7 },
      color: "#12324a",
      accent: "#3de7ff",
      interaction: "hq",
      label: "OCEAN HQ",
    },
    {
      id: "miami-b-fountain",
      districtId: "miami-arrival",
      kind: "plaza",
      name: "Cyan Fountain Plaza",
      position: { x: 0, y: 0, z: 26 },
      size: { width: 6, height: 2.4, depth: 6 },
      color: "#0e2933",
      accent: "#7fffd4",
      interaction: "voice",
      label: "PLAZA",
    },
    {
      id: "miami-b-cabana",
      districtId: "miami-community",
      kind: "social_hub",
      name: "Community Cabana",
      position: { x: -30, y: 0, z: 8 },
      size: { width: 10, height: 5, depth: 9 },
      color: "#24424a",
      accent: "#7fffd4",
      interaction: "community",
      label: "CABANA",
    },
    {
      id: "miami-b-dao",
      districtId: "miami-community",
      kind: "shop",
      name: "DAO Patio",
      position: { x: -32, y: 0, z: -7 },
      size: { width: 8, height: 4.5, depth: 7 },
      color: "#40334d",
      accent: "#ff8bd1",
      interaction: "community",
      label: "DAO",
    },
    {
      id: "miami-b-social",
      districtId: "miami-social",
      kind: "social_hub",
      name: "Social Sands Club",
      position: { x: 30, y: 0, z: 8 },
      size: { width: 10, height: 5.5, depth: 9 },
      color: "#1f3850",
      accent: "#3de7ff",
      interaction: "voice",
      label: "SOCIAL",
    },
    {
      id: "miami-b-music",
      districtId: "miami-social",
      kind: "plaza",
      name: "Open Mic Palms",
      position: { x: 32, y: 0, z: -7 },
      size: { width: 8, height: 4, depth: 7 },
      color: "#47304a",
      accent: "#ff8bd1",
      interaction: "community",
      label: "OPEN MIC",
    },
    {
      id: "miami-b-market",
      districtId: "miami-market",
      kind: "market",
      name: "Coastal Token Market",
      position: { x: -28, y: 0, z: -26 },
      size: { width: 11, height: 6, depth: 8 },
      color: "#3f3723",
      accent: "#ffd166",
      interaction: "marketplace",
      label: "MARKET",
    },
    {
      id: "miami-b-marina",
      districtId: "miami-market",
      kind: "shop",
      name: "Marina Mint Kiosk",
      position: { x: -10, y: 0, z: -28 },
      size: { width: 7, height: 4.5, depth: 6 },
      color: "#173d3b",
      accent: "#7fffd4",
      interaction: "marketplace",
      label: "MINTS",
    },
    {
      id: "miami-b-launch",
      districtId: "miami-launch",
      kind: "launch_arena",
      name: "Sunset Launch Pier",
      position: { x: 28, y: 0, z: -26 },
      size: { width: 12, height: 6.5, depth: 8 },
      color: "#4a2e38",
      accent: "#ff8bd1",
      interaction: "launch",
      label: "LAUNCH",
    },
    {
      id: "miami-b-watch",
      districtId: "miami-launch",
      kind: "ad_tower",
      name: "Lifeguard Signal Tower",
      position: { x: 10, y: 0, z: -28 },
      size: { width: 5, height: 10, depth: 5 },
      color: "#20384f",
      accent: "#3de7ff",
      interaction: "billboard",
      label: "SIGNAL",
    },
    {
      id: "miami-b-boardwalk-a",
      districtId: "miami-boardwalk",
      kind: "shop",
      name: "Pastel Juice Bar",
      position: { x: -30, y: 0, z: 38 },
      size: { width: 8, height: 4.2, depth: 6 },
      color: "#4a3545",
      accent: "#ff8bd1",
      label: "JUICE",
    },
    {
      id: "miami-b-boardwalk-b",
      districtId: "miami-boardwalk",
      kind: "plaza",
      name: "Beach DAO Stage",
      position: { x: 30, y: 0, z: 38 },
      size: { width: 9, height: 4.5, depth: 6 },
      color: "#173d45",
      accent: "#3de7ff",
      interaction: "community",
      label: "STAGE",
    },
  ],
  billboards: [
    {
      id: "miami-bb-orbitx",
      position: { x: -9, y: 4.5, z: 12 },
      rotationY: Math.PI / 5,
      width: 5.8,
      height: 3,
      title: "MIAMI COAST",
      subtitle: "OrbitX community plaza",
      accent: "#3de7ff",
      projectName: "OrbitX Miami",
      tokenMint: OGSCAN_TOKEN_MINT,
      website: "https://orbitx.world",
    },
    {
      id: "miami-bb-community",
      position: { x: -20, y: 4.2, z: 24 },
      rotationY: -Math.PI * 0.35,
      width: 5,
      height: 2.8,
      title: "CABANA DAO",
      subtitle: "Community spaces · live rooms",
      accent: "#7fffd4",
      projectName: "Community Cabanas",
    },
    {
      id: "miami-bb-launch",
      position: { x: 20, y: 4.4, z: -16 },
      rotationY: Math.PI * 0.8,
      width: 5.2,
      height: 2.9,
      title: "SUNSET LAUNCH",
      subtitle: "Open-air drops on the pier",
      accent: "#ff8bd1",
      projectName: "Sunset Launch Pier",
    },
    {
      id: "miami-bb-boardwalk",
      position: { x: 6, y: 4, z: 36 },
      rotationY: Math.PI,
      width: 6,
      height: 3,
      title: "BOARDWALK",
      subtitle: "Beach meetups · social games",
      accent: "#ffd166",
      projectName: "Neon Boardwalk",
    },
  ],
  zones: [
    {
      id: "miami-z-hq",
      kind: "hq",
      label: "Ocean Orbit HQ",
      hint: "Open the Miami world hub",
      position: { x: 0, y: 0, z: 13 },
      radius: 4.5,
      buildingId: "miami-b-hq",
    },
    {
      id: "miami-z-plaza",
      kind: "voice",
      label: "Cyan Fountain Plaza",
      hint: "Gather in the open coastal voice plaza",
      position: { x: 0, y: 0, z: 22 },
      radius: 5.5,
      buildingId: "miami-b-fountain",
    },
    {
      id: "miami-z-community",
      kind: "community",
      label: "Community Cabana",
      hint: "Meet local communities and DAO rooms",
      position: { x: -30, y: 0, z: 15 },
      radius: 5,
      buildingId: "miami-b-cabana",
    },
    {
      id: "miami-z-social",
      kind: "community",
      label: "Social Sands",
      hint: "Join coastal hangouts and creator chats",
      position: { x: 24, y: 0, z: 8 },
      radius: 5,
      buildingId: "miami-b-social",
    },
    {
      id: "miami-z-market",
      kind: "marketplace",
      label: "Coastal Token Market",
      hint: "Browse beachside token storefronts",
      position: { x: -28, y: 0, z: -20 },
      radius: 4.8,
      buildingId: "miami-b-market",
    },
    {
      id: "miami-z-launch",
      kind: "launch",
      label: "Sunset Launch Pier",
      hint: "Open the outdoor launch deck",
      position: { x: 28, y: 0, z: -20 },
      radius: 4.8,
      buildingId: "miami-b-launch",
    },
    {
      id: "miami-z-token",
      kind: "token",
      label: "Miami Coast Billboard",
      hint: "View live OrbitX token details",
      position: { x: -9, y: 0, z: 14 },
      radius: 3.5,
      tokenMint: OGSCAN_TOKEN_MINT,
    },
  ],
  landmarks: [
    {
      id: "miami-boardwalk-landmark",
      modelId: "landmark-miami",
      position: { x: -6, y: 0, z: 30 },
      rotationY: 0.2,
      size: { width: 12, height: 6, depth: 4 },
      label: "BOARDWALK",
    },
  ],
};
