import type { StreetSegment, WorldBlockConfig } from "../types";

/**
 * OrbitX NYC · Real Midtown district.
 * Building footprints projected from OpenStreetMap (© OpenStreetMap contributors, ODbL).
 * Generated by web/scripts/build-osm-midtown.mjs — do not hand-edit footprints.
 */

export const NYC_OSM_STREETS: StreetSegment[] = [
  {
    o: "v",
    at: -11.86,
    from: -64,
    to: 69,
    w: 7,
    curbA: "#17ff4d",
    curbB: "#3de7ff"
  },
  {
    o: "v",
    at: 22.4,
    from: -64,
    to: 69,
    w: 6,
    curbA: "#f5c542",
    curbB: "#ff4d9a"
  },
  {
    o: "h",
    at: 29.36,
    from: -85,
    to: 63,
    w: 6,
    curbA: "#3de7ff",
    curbB: "#a78bfa"
  },
  {
    o: "h",
    at: 1.73,
    from: -85,
    to: 63,
    w: 6,
    curbA: "#ff4d9a",
    curbB: "#17ff4d"
  },
  {
    o: "h",
    at: -25.91,
    from: -85,
    to: 63,
    w: 6,
    curbA: "#a78bfa",
    curbB: "#3de7ff"
  }
];

export const NYC_OSM_TELEPORT_POINTS = [
  {
    id: "times",
    label: "Times Square Core",
    x: -3.59,
    z: -22.45,
    accent: "#17ff4d"
  },
  {
    id: "osm-137716320",
    label: "ORBITX HQ",
    x: 11.51,
    z: 20.73,
    accent: "#17ff4d"
  },
  {
    id: "osm-266170795",
    label: "DEX STORE",
    x: 38.4,
    z: -23.63,
    accent: "#ff4d9a"
  },
  {
    id: "osm-157835453",
    label: "DEX FLOOR",
    x: -22.56,
    z: 28.69,
    accent: "#3de7ff"
  },
  {
    id: "osm-266149373",
    label: "LAUNCHPAD",
    x: -38.57,
    z: 50.87,
    accent: "#f5c542"
  },
  {
    id: "osm-163474780",
    label: "SOCIAL",
    x: -13.11,
    z: 5.82,
    accent: "#a78bfa"
  },
  {
    id: "osm-266170615",
    label: "VOICE",
    x: 23.22,
    z: -7.13,
    accent: "#ff6bcb"
  },
  {
    id: "osm-163629929",
    label: "BUY DESK",
    x: -10.56,
    z: 65.31,
    accent: "#17ff4d"
  },
  {
    id: "osm-266149338",
    label: "DEX DESK",
    x: -60.44,
    z: 41.42,
    accent: "#3de7ff"
  },
  {
    id: "osm-143858914",
    label: "COMMUNITY",
    x: -28.64,
    z: -31.96,
    accent: "#a78bfa"
  }
] as const;

export const NYC_OSM_BLOCK: WorldBlockConfig = {
  cityId: "nyc",
  name: "OrbitX City · Midtown NYC (OSM)",
  spawn: {
  x: -3.59,
  y: 0,
  z: -22.45
},
  bounds: {
  minX: -87,
  maxX: 65,
  minZ: -66,
  maxZ: 71
},
  districts: [
    {
      id: "midtown",
      cityId: "nyc",
      kind: "hq",
      name: "Times Square Midtown",
      description: "OrbitX Midtown — DEX stores, launchpad, HQ office, and social venues on real OSM footprints.",
      center: { x: 0, y: 0, z: 0 },
      size: { width: 152, depth: 137 },
    },
  ],
  buildings: [
  {
    id: "osm-163474780",
    districtId: "midtown",
    kind: "social_hub",
    name: "New York Marriott Marquis",
    position: {
      x: -26.61,
      y: 0,
      z: -12.07
    },
    size: {
      width: 38.52,
      height: 7.91,
      depth: 30.79
    },
    color: "#302820",
    accent: "#a78bfa",
    label: "SOCIAL",
    footprint: [
      {
        x: 14.026,
        z: 15.393
      },
      {
        x: 15.91,
        z: 8.978
      },
      {
        x: 17.291,
        z: 8.142
      },
      {
        x: 18.04,
        z: 7.168
      },
      {
        x: 18.456,
        z: 5.769
      },
      {
        x: 18.303,
        z: 4.335
      },
      {
        x: 17.655,
        z: 3.126
      },
      {
        x: 19.26,
        z: -2.425
      },
      {
        x: -1.765,
        z: -14.028
      },
      {
        x: -6.398,
        z: -11.551
      },
      {
        x: -10.219,
        z: -8.266
      },
      {
        x: -17.246,
        z: -10.912
      },
      {
        x: -15.85,
        z: -5.399
      },
      {
        x: -10.975,
        z: 2.301
      },
      {
        x: 11.386,
        z: 14.529
      }
    ],
    interaction: "community"
  },
  {
    id: "osm-157835453",
    districtId: "midtown",
    kind: "trading_floor",
    name: "One Astor Place",
    position: {
      x: -31.56,
      y: 0,
      z: 11.6
    },
    size: {
      width: 33.26,
      height: 6.83,
      depth: 29.18
    },
    color: "#1f2c38",
    accent: "#3de7ff",
    label: "DEX FLOOR",
    footprint: [
      {
        x: -16.632,
        z: 1.105
      },
      {
        x: -14.996,
        z: 0.263
      },
      {
        x: -14.617,
        z: -2.446
      },
      {
        x: -14.316,
        z: -2.974
      },
      {
        x: -9.144,
        z: -10.111
      },
      {
        x: -10.34,
        z: -12.011
      },
      {
        x: -7.718,
        z: -14.591
      },
      {
        x: -6.767,
        z: -13.137
      },
      {
        x: -4.464,
        z: -13.251
      },
      {
        x: 3.325,
        z: -7.52
      },
      {
        x: 5.565,
        z: -8.46
      },
      {
        x: 15.618,
        z: -2.95
      },
      {
        x: 16.632,
        z: 1.047
      },
      {
        x: 7.294,
        z: 12.156
      },
      {
        x: 7.528,
        z: 14.218
      },
      {
        x: 6.277,
        z: 14.025
      },
      {
        x: -4.39,
        z: 8.398
      },
      {
        x: -5.02,
        z: 6.142
      },
      {
        x: -13.589,
        z: 3.437
      }
    ],
    interaction: "trading"
  },
  {
    id: "osm-266149338",
    districtId: "midtown",
    kind: "trading_floor",
    name: "Times Square Building",
    position: {
      x: -60.44,
      y: 0,
      z: 26.82
    },
    size: {
      width: 35.27,
      height: 6.47,
      depth: 24.21
    },
    color: "#242b35",
    accent: "#3de7ff",
    label: "DEX DESK",
    footprint: [
      {
        x: 16.117,
        z: -1.302
      },
      {
        x: 17.432,
        z: -0.577
      },
      {
        x: 16.51,
        z: 0.691
      },
      {
        x: 15.698,
        z: 2.294
      },
      {
        x: 14.505,
        z: 3.658
      },
      {
        x: 11.119,
        z: 9.766
      },
      {
        x: 10.249,
        z: 9.285
      },
      {
        x: 8.684,
        z: 12.104
      },
      {
        x: -17.635,
        z: -2.39
      },
      {
        x: -13.021,
        z: -10.715
      },
      {
        x: -6.818,
        z: -7.299
      },
      {
        x: -1.337,
        z: -4.28
      },
      {
        x: 3,
        z: -12.104
      },
      {
        x: 7.227,
        z: -9.772
      },
      {
        x: 7.506,
        z: -10.277
      },
      {
        x: 12.631,
        z: -7.455
      },
      {
        x: 12.352,
        z: -6.95
      },
      {
        x: 17.635,
        z: -4.042
      },
      {
        x: 16.117,
        z: -1.302
      }
    ],
    interaction: "trading"
  },
  {
    id: "osm-266149373",
    districtId: "midtown",
    kind: "launch_arena",
    name: "1501 Broadway",
    position: {
      x: -38.57,
      y: 0,
      z: 35.32
    },
    size: {
      width: 26.37,
      height: 6.47,
      depth: 26.09
    },
    color: "#23302c",
    accent: "#f5c542",
    label: "LAUNCHPAD",
    footprint: [
      {
        x: -11.621,
        z: 0.782
      },
      {
        x: -10.751,
        z: 1.263
      },
      {
        x: -7.365,
        z: -4.845
      },
      {
        x: -6.171,
        z: -6.209
      },
      {
        x: -5.36,
        z: -7.812
      },
      {
        x: -4.437,
        z: -9.08
      },
      {
        x: -5.752,
        z: -9.805
      },
      {
        x: -4.235,
        z: -12.545
      },
      {
        x: -3.958,
        z: -13.045
      },
      {
        x: 5.183,
        z: -7.985
      },
      {
        x: 13.186,
        z: -3.605
      },
      {
        x: 6.809,
        z: 7.898
      },
      {
        x: 4.957,
        z: 11.256
      },
      {
        x: 3.958,
        z: 13.045
      },
      {
        x: -1.91,
        z: 9.812
      },
      {
        x: -13.186,
        z: 3.601
      },
      {
        x: -11.621,
        z: 0.782
      }
    ],
    interaction: "launch"
  },
  {
    id: "osm-137716320",
    districtId: "midtown",
    kind: "hq",
    name: "OrbitX HQ",
    position: {
      x: 11.51,
      y: 0,
      z: 6.6
    },
    size: {
      width: 27.51,
      height: 5.5,
      depth: 23.26
    },
    color: "#302820",
    accent: "#17ff4d",
    label: "ORBITX HQ",
    footprint: [
      {
        x: -5.682,
        z: -11.631
      },
      {
        x: -13.754,
        z: 3.32
      },
      {
        x: 1.812,
        z: 11.631
      },
      {
        x: 2.979,
        z: 9.351
      },
      {
        x: 3.134,
        z: 9.064
      },
      {
        x: 3.88,
        z: 7.703
      },
      {
        x: 6.199,
        z: 3.468
      },
      {
        x: 9.219,
        z: 5.085
      },
      {
        x: 12.76,
        z: -1.451
      },
      {
        x: 13.754,
        z: -3.337
      },
      {
        x: 12.563,
        z: -3.973
      },
      {
        x: 3.893,
        z: -8.615
      },
      {
        x: 3.011,
        z: -6.985
      },
      {
        x: -5.682,
        z: -11.631
      }
    ],
    interaction: "hq"
  },
  {
    id: "osm-143858914",
    districtId: "midtown",
    kind: "social_hub",
    name: "The Hotel Edison NYC",
    position: {
      x: -28.64,
      y: 0,
      z: -48.02
    },
    size: {
      width: 27.16,
      height: 7.91,
      depth: 18.12
    },
    color: "#23302c",
    accent: "#a78bfa",
    label: "COMMUNITY",
    footprint: [
      {
        x: -13.582,
        z: 7.427
      },
      {
        x: -9.018,
        z: -0.725
      },
      {
        x: -8.932,
        z: -0.881
      },
      {
        x: -7.654,
        z: -3.168
      },
      {
        x: -4.357,
        z: -9.061
      },
      {
        x: 8.244,
        z: -2.069
      },
      {
        x: 13.582,
        z: 0.909
      },
      {
        x: 9.021,
        z: 9.061
      },
      {
        x: 7.843,
        z: 8.408
      },
      {
        x: 3.698,
        z: 6.062
      },
      {
        x: -0.547,
        z: 3.741
      },
      {
        x: -6.821,
        z: 0.256
      },
      {
        x: -11.485,
        z: 8.591
      },
      {
        x: -13.582,
        z: 7.427
      }
    ],
    interaction: "community"
  },
  {
    id: "osm-163629929",
    districtId: "midtown",
    kind: "market",
    name: "1500 Broadway",
    position: {
      x: -10.56,
      y: 0,
      z: 50.8
    },
    size: {
      width: 17.05,
      height: 6.47,
      depth: 24.02
    },
    color: "#1b2433",
    accent: "#17ff4d",
    label: "BUY DESK",
    footprint: [
      {
        x: 8.524,
        z: -6.187
      },
      {
        x: -2.098,
        z: -11.976
      },
      {
        x: -3.08,
        z: -12.011
      },
      {
        x: -8.524,
        z: 6.346
      },
      {
        x: 1.623,
        z: 12.011
      },
      {
        x: 5.038,
        z: 6.004
      },
      {
        x: 2.482,
        z: 4.591
      },
      {
        x: 8.524,
        z: -6.187
      }
    ],
    interaction: "token"
  },
  {
    id: "osm-266170537",
    districtId: "midtown",
    kind: "generic",
    name: "Church of Saint Mary the Virgin",
    position: {
      x: 43.06,
      y: 0,
      z: -3.73
    },
    size: {
      width: 18.54,
      height: 6.83,
      depth: 21.54
    },
    color: "#23302c",
    accent: "#17ff4d",
    label: "NFT HALL",
    footprint: [
      {
        x: 4.154,
        z: 2.896
      },
      {
        x: 5.206,
        z: 3.477
      },
      {
        x: 4.231,
        z: 5.232
      },
      {
        x: 2.043,
        z: 9.166
      },
      {
        x: 1.153,
        z: 10.769
      },
      {
        x: -0.692,
        z: 9.729
      },
      {
        x: -3.561,
        z: 8.109
      },
      {
        x: -6.415,
        z: 6.562
      },
      {
        x: -9.269,
        z: 5.011
      },
      {
        x: -4.636,
        z: -3.321
      },
      {
        x: -3.082,
        z: -2.468
      },
      {
        x: 1.538,
        z: -10.769
      },
      {
        x: 6.36,
        z: -8.109
      },
      {
        x: 6.534,
        z: -7.315
      },
      {
        x: 6.744,
        z: -7.197
      },
      {
        x: 7.008,
        z: -7.052
      },
      {
        x: 7.219,
        z: -7.432
      },
      {
        x: 9.269,
        z: -6.303
      },
      {
        x: 8.383,
        z: -4.71
      },
      {
        x: 6.191,
        z: -0.769
      },
      {
        x: 5.163,
        z: 1.083
      },
      {
        x: 4.154,
        z: 2.896
      }
    ],
    interaction: "nft"
  },
  {
    id: "osm-266170615",
    districtId: "midtown",
    kind: "generic",
    name: "160 West 47th Street",
    position: {
      x: 25.34,
      y: 0,
      z: -20.19
    },
    size: {
      width: 21.74,
      height: 6.47,
      depth: 16.87
    },
    color: "#302820",
    accent: "#ff6bcb",
    label: "VOICE",
    footprint: [
      {
        x: -2.685,
        z: -6.429
      },
      {
        x: -0.714,
        z: -5.34
      },
      {
        x: 6.98,
        z: -1.088
      },
      {
        x: 10.87,
        z: 1.06
      },
      {
        x: 10.598,
        z: 1.551
      },
      {
        x: 6.767,
        z: 8.436
      },
      {
        x: -0.071,
        z: 4.656
      },
      {
        x: -0.588,
        z: 5.589
      },
      {
        x: -4.401,
        z: 3.485
      },
      {
        x: -9.573,
        z: 0.649
      },
      {
        x: -10.105,
        z: 0.345
      },
      {
        x: -10.87,
        z: -0.093
      },
      {
        x: -7.897,
        z: -5.441
      },
      {
        x: -6.73,
        z: -8.436
      },
      {
        x: -2.648,
        z: -6.919
      },
      {
        x: -2.685,
        z: -6.429
      }
    ],
    interaction: "voice"
  },
  {
    id: "osm-266149345",
    districtId: "midtown",
    kind: "generic",
    name: "Imperial Theatre",
    position: {
      x: -49.9,
      y: 0,
      z: -29.66
    },
    size: {
      width: 16.18,
      height: 5.5,
      depth: 19.33
    },
    color: "#302820",
    accent: "#a78bfa",
    label: "GAMES",
    footprint: [
      {
        x: 3.387,
        z: 3.988
      },
      {
        x: -1.696,
        z: 1.18
      },
      {
        x: -2.223,
        z: 2.112
      },
      {
        x: -6.42,
        z: 9.664
      },
      {
        x: -7.248,
        z: 9.221
      },
      {
        x: -8.091,
        z: 8.762
      },
      {
        x: -7.896,
        z: 8.413
      },
      {
        x: -3.353,
        z: 0.268
      },
      {
        x: -6.043,
        z: -1.231
      },
      {
        x: -1.337,
        z: -9.664
      },
      {
        x: 8.091,
        z: -4.496
      },
      {
        x: 3.387,
        z: 3.988
      }
    ],
    interaction: "games"
  },
  {
    id: "osm-266170795",
    districtId: "midtown",
    kind: "market",
    name: "20 Times Square",
    position: {
      x: 30.9,
      y: 0,
      z: -33.94
    },
    size: {
      width: 17.88,
      height: 17.25,
      depth: 15.62
    },
    color: "#23302c",
    accent: "#ff4d9a",
    label: "DEX STORE",
    footprint: [
      {
        x: 8.939,
        z: -0.453
      },
      {
        x: 7.393,
        z: 2.325
      },
      {
        x: 5.306,
        z: 6.076
      },
      {
        x: 4.341,
        z: 7.81
      },
      {
        x: -8.939,
        z: 0.435
      },
      {
        x: -4.365,
        z: -7.81
      },
      {
        x: 5.495,
        z: -2.356
      },
      {
        x: 8.939,
        z: -0.453
      }
    ],
    interaction: "marketplace"
  },
  {
    id: "osm-266170751",
    districtId: "midtown",
    kind: "generic",
    name: "Hudson Theatre",
    position: {
      x: 21.35,
      y: 0,
      z: 39.32
    },
    size: {
      width: 13.68,
      height: 5.5,
      depth: 19.93
    },
    color: "#1b2433",
    accent: "#a78bfa",
    label: "GAMES",
    footprint: [
      {
        x: 2.411,
        z: 2.28
      },
      {
        x: 1.468,
        z: 1.758
      },
      {
        x: -3.101,
        z: 9.966
      },
      {
        x: -5.054,
        z: 8.881
      },
      {
        x: -6.841,
        z: 7.886
      },
      {
        x: -6.511,
        z: 7.296
      },
      {
        x: -6.082,
        z: 6.529
      },
      {
        x: -2.854,
        z: 0.757
      },
      {
        x: -2.258,
        z: -0.307
      },
      {
        x: -4.64,
        z: -1.62
      },
      {
        x: 0.005,
        z: -9.966
      },
      {
        x: 6.841,
        z: -6.183
      },
      {
        x: 3.078,
        z: 0.577
      },
      {
        x: 3.294,
        z: 0.694
      },
      {
        x: 2.883,
        z: 1.43
      },
      {
        x: 2.411,
        z: 2.28
      }
    ],
    interaction: "games"
  },
  {
    id: "osm-266170758",
    districtId: "midtown",
    kind: "trading_floor",
    name: "Jacqueline Kennedy Onassis High School",
    position: {
      x: 46.99,
      y: 0,
      z: 21.2
    },
    size: {
      width: 18.92,
      height: 5.5,
      depth: 14.37
    },
    color: "#2a2434",
    accent: "#3de7ff",
    label: "DEX DESK",
    footprint: [
      {
        x: -9.46,
        z: 1.993
      },
      {
        x: -8.593,
        z: 0.415
      },
      {
        x: -8.538,
        z: 0.259
      },
      {
        x: -7.191,
        z: 0.978
      },
      {
        x: -5.586,
        z: 1.838
      },
      {
        x: -5.365,
        z: 1.43
      },
      {
        x: -6.219,
        z: 0.971
      },
      {
        x: -4.841,
        z: -1.589
      },
      {
        x: -3.984,
        z: -1.133
      },
      {
        x: -2.877,
        z: -3.188
      },
      {
        x: -3.955,
        z: -3.765
      },
      {
        x: -2.113,
        z: -7.185
      },
      {
        x: 3.823,
        z: -4.007
      },
      {
        x: 9.46,
        z: -0.988
      },
      {
        x: 5.059,
        z: 7.185
      },
      {
        x: 2.145,
        z: 5.624
      },
      {
        x: 4.084,
        z: 2.028
      },
      {
        x: 1.465,
        z: 0.625
      },
      {
        x: -0.345,
        z: 3.979
      },
      {
        x: 1.386,
        z: 4.905
      },
      {
        x: 0.213,
        z: 7.088
      },
      {
        x: -2.993,
        z: 5.382
      },
      {
        x: -4.614,
        z: 4.518
      },
      {
        x: -9.46,
        z: 1.993
      }
    ],
    interaction: "trading"
  },
  {
    id: "osm-266149312",
    districtId: "midtown",
    kind: "launch_arena",
    name: "Paramount Hotel",
    position: {
      x: -46.32,
      y: 0,
      z: -48.25
    },
    size: {
      width: 17.32,
      height: 7.91,
      depth: 15.31
    },
    color: "#242b35",
    accent: "#f5c542",
    label: "LAUNCHPAD",
    footprint: [
      {
        x: 8.659,
        z: -0.496
      },
      {
        x: 4.095,
        z: 7.657
      },
      {
        x: -8.659,
        z: 0.371
      },
      {
        x: -7.966,
        z: -0.855
      },
      {
        x: -5.331,
        z: -5.643
      },
      {
        x: -4.242,
        z: -7.657
      },
      {
        x: 2.379,
        z: -3.985
      },
      {
        x: 4.482,
        z: -2.817
      },
      {
        x: 8.659,
        z: -0.496
      }
    ],
    interaction: "launch"
  },
  {
    id: "osm-266170755",
    districtId: "midtown",
    kind: "generic",
    name: "Lyceum Theatre",
    position: {
      x: 19.92,
      y: 0,
      z: 12.68
    },
    size: {
      width: 13.19,
      height: 6.11,
      depth: 18.84
    },
    color: "#1f2c38",
    accent: "#a78bfa",
    label: "GAMES",
    footprint: [
      {
        x: 2.062,
        z: -0.328
      },
      {
        x: 5.026,
        z: 1.261
      },
      {
        x: 4.56,
        z: 2.124
      },
      {
        x: 0.631,
        z: 9.42
      },
      {
        x: -2.929,
        z: 7.489
      },
      {
        x: -6.597,
        z: 5.548
      },
      {
        x: -5.43,
        z: 3.268
      },
      {
        x: -5.274,
        z: 2.981
      },
      {
        x: -4.565,
        z: 3.361
      },
      {
        x: -3.83,
        z: 1.997
      },
      {
        x: -4.528,
        z: 1.62
      },
      {
        x: -2.209,
        z: -2.615
      },
      {
        x: 0.81,
        z: -0.998
      },
      {
        x: 4.352,
        z: -7.534
      },
      {
        x: 5.345,
        z: -9.42
      },
      {
        x: 6.597,
        z: -8.75
      },
      {
        x: 6.478,
        z: -8.529
      },
      {
        x: 2.286,
        z: -0.746
      },
      {
        x: 2.062,
        z: -0.328
      }
    ],
    interaction: "games"
  },
  {
    id: "osm-266170766",
    districtId: "midtown",
    kind: "launch_arena",
    name: "Tower 45",
    position: {
      x: 34.67,
      y: 0,
      z: 42.98
    },
    size: {
      width: 16.57,
      height: 6.47,
      depth: 14.43
    },
    color: "#23302c",
    accent: "#f5c542",
    label: "LAUNCHPAD",
    footprint: [
      {
        x: 4.619,
        z: 7.213
      },
      {
        x: 1.615,
        z: 5.562
      },
      {
        x: 1.138,
        z: 5.296
      },
      {
        x: -1.025,
        z: 4.097
      },
      {
        x: -6.408,
        z: 1.116
      },
      {
        x: -8.287,
        z: 0.076
      },
      {
        x: -7.502,
        z: -1.32
      },
      {
        x: -4.619,
        z: -6.463
      },
      {
        x: 5.223,
        z: -2.042
      },
      {
        x: 5.275,
        z: -1.022
      },
      {
        x: 8.287,
        z: 0.653
      },
      {
        x: 7.921,
        z: 1.295
      },
      {
        x: 7.162,
        z: 2.653
      },
      {
        x: 6.04,
        z: 4.667
      },
      {
        x: 4.893,
        z: 6.719
      }
    ],
    interaction: "launch"
  },
  {
    id: "osm-266149327",
    districtId: "midtown",
    kind: "generic",
    name: "Lunt-Fontanne Theatre",
    position: {
      x: -16.96,
      y: 0,
      z: -32.24
    },
    size: {
      width: 15.43,
      height: 6.11,
      depth: 14.76
    },
    color: "#242b35",
    accent: "#a78bfa",
    label: "GAMES",
    footprint: [
      {
        x: 7.717,
        z: -0.96
      },
      {
        x: 6.336,
        z: 1.51
      },
      {
        x: 5.221,
        z: 3.499
      },
      {
        x: 3.111,
        z: 7.275
      },
      {
        x: 3.053,
        z: 7.379
      },
      {
        x: -0.589,
        z: 5.392
      },
      {
        x: -7.717,
        z: 1.392
      },
      {
        x: -6.816,
        z: -0.218
      },
      {
        x: -7.598,
        z: -0.649
      },
      {
        x: -3.835,
        z: -7.379
      },
      {
        x: -2.657,
        z: -6.726
      },
      {
        x: 0.217,
        z: -5.126
      },
      {
        x: 7.717,
        z: -0.96
      }
    ],
    interaction: "games"
  },
  {
    id: "osm-266170769",
    districtId: "midtown",
    kind: "market",
    name: "Hotel Riu Plaza Manhattan Times Square",
    position: {
      x: 49.09,
      y: 0,
      z: -23.87
    },
    size: {
      width: 14.59,
      height: 7.91,
      depth: 13.79
    },
    color: "#242b35",
    accent: "#ff4d9a",
    label: "MEME STORE",
    footprint: [
      {
        x: 7.296,
        z: -1.366
      },
      {
        x: 2.875,
        z: 6.572
      },
      {
        x: 2.698,
        z: 6.893
      },
      {
        x: -7.296,
        z: 1.366
      },
      {
        x: -6.224,
        z: -0.558
      },
      {
        x: -4.253,
        z: -4.099
      },
      {
        x: -2.698,
        z: -6.893
      },
      {
        x: 2.29,
        z: -4.137
      },
      {
        x: 2.706,
        z: -3.905
      },
      {
        x: 7.296,
        z: -1.366
      }
    ],
    interaction: "marketplace"
  },
  {
    id: "osm-266149330",
    districtId: "midtown",
    kind: "generic",
    name: "Richard Rodgers Theatre",
    position: {
      x: -39.35,
      y: 0,
      z: -27.25
    },
    size: {
      width: 14.34,
      height: 5.5,
      depth: 13.83
    },
    color: "#2a2434",
    accent: "#a78bfa",
    label: "GAMES",
    footprint: [
      {
        x: 2.518,
        z: 6.914
      },
      {
        x: -3.988,
        z: 3.328
      },
      {
        x: -7.169,
        z: 1.57
      },
      {
        x: -2.465,
        z: -6.914
      },
      {
        x: -1.888,
        z: -6.6
      },
      {
        x: -0.534,
        z: -5.857
      },
      {
        x: 5.306,
        z: -2.665
      },
      {
        x: 7.169,
        z: -1.542
      },
      {
        x: 6.918,
        z: -1.028
      },
      {
        x: 4.797,
        z: 2.803
      },
      {
        x: 2.518,
        z: 6.914
      }
    ],
    interaction: "games"
  },
  {
    id: "osm-266149334",
    districtId: "midtown",
    kind: "generic",
    name: "Shubert Theatre",
    position: {
      x: -52.87,
      y: 0,
      z: 3.84
    },
    size: {
      width: 14.02,
      height: 6.11,
      depth: 13.92
    },
    color: "#302820",
    accent: "#a78bfa",
    label: "GAMES",
    footprint: [
      {
        x: 2.292,
        z: 6.701
      },
      {
        x: 1.945,
        z: 6.961
      },
      {
        x: 1.299,
        z: 6.916
      },
      {
        x: -6.295,
        z: 2.719
      },
      {
        x: -5.887,
        z: 1.986
      },
      {
        x: -7.009,
        z: 1.364
      },
      {
        x: -2.814,
        z: -6.173
      },
      {
        x: -2.377,
        z: -6.961
      },
      {
        x: 7.009,
        z: -1.776
      },
      {
        x: 2.972,
        z: 5.437
      },
      {
        x: 2.292,
        z: 6.701
      }
    ],
    interaction: "games"
  },
  {
    id: "osm-266170756",
    districtId: "midtown",
    kind: "market",
    name: "Millennium Hotel Broadway Times Square",
    position: {
      x: 11.97,
      y: 0,
      z: 40.45
    },
    size: {
      width: 14.24,
      height: 7.91,
      depth: 13.52
    },
    color: "#2a2434",
    accent: "#ff4d9a",
    label: "MEME STORE",
    footprint: [
      {
        x: 7.121,
        z: -1.434
      },
      {
        x: 6.526,
        z: -0.37
      },
      {
        x: 3.298,
        z: 5.403
      },
      {
        x: 2.868,
        z: 6.17
      },
      {
        x: 2.539,
        z: 6.76
      },
      {
        x: -0.71,
        z: 4.947
      },
      {
        x: -4.252,
        z: 3.016
      },
      {
        x: -7.121,
        z: 1.434
      },
      {
        x: -6.781,
        z: 0.829
      },
      {
        x: -6.341,
        z: 0.079
      },
      {
        x: -5.105,
        z: -2.135
      },
      {
        x: -4.447,
        z: -3.313
      },
      {
        x: -2.539,
        z: -6.76
      },
      {
        x: 0.062,
        z: -5.327
      },
      {
        x: 0.368,
        z: -5.157
      },
      {
        x: 4.325,
        z: -2.974
      },
      {
        x: 4.739,
        z: -2.746
      },
      {
        x: 7.121,
        z: -1.434
      }
    ],
    interaction: "marketplace"
  },
  {
    id: "osm-266149299",
    districtId: "midtown",
    kind: "generic",
    name: "Booth Theatre",
    position: {
      x: -48.58,
      y: 0,
      z: -3.98
    },
    size: {
      width: 13.32,
      height: 5.5,
      depth: 12.09
    },
    color: "#302820",
    accent: "#a78bfa",
    label: "GAMES",
    footprint: [
      {
        x: -6.661,
        z: 0.858
      },
      {
        x: -3.078,
        z: -5.587
      },
      {
        x: -1.955,
        z: -4.966
      },
      {
        x: -1.357,
        z: -6.043
      },
      {
        x: 6.3,
        z: -1.812
      },
      {
        x: 6.524,
        z: -1.456
      },
      {
        x: 6.661,
        z: -1.035
      },
      {
        x: 5.765,
        z: 0.492
      },
      {
        x: 2.725,
        z: 6.043
      },
      {
        x: -6.661,
        z: 0.858
      }
    ],
    interaction: "games"
  },
  {
    id: "osm-266149329",
    districtId: "midtown",
    kind: "generic",
    name: "Music Box Theatre",
    position: {
      x: -50.09,
      y: 0,
      z: -21.51
    },
    size: {
      width: 12.47,
      height: 7.19,
      depth: 12.09
    },
    color: "#2a2434",
    accent: "#a78bfa",
    label: "GAMES",
    footprint: [
      {
        x: 2.059,
        z: 6.047
      },
      {
        x: -4.847,
        z: 2.254
      },
      {
        x: -6.233,
        z: 1.504
      },
      {
        x: -2.036,
        z: -6.047
      },
      {
        x: 6.233,
        z: -1.473
      },
      {
        x: 4.22,
        z: 2.154
      },
      {
        x: 2.059,
        z: 6.047
      }
    ],
    interaction: "games"
  },
  {
    id: "osm-260180778",
    districtId: "midtown",
    kind: "social_hub",
    name: "Hyatt Centric Times Square",
    position: {
      x: 32.3,
      y: 0,
      z: 23.52
    },
    size: {
      width: 12.21,
      height: 7.91,
      depth: 12.25
    },
    color: "#23302c",
    accent: "#a78bfa",
    label: "COMMUNITY",
    footprint: [
      {
        x: -1.698,
        z: -6.125
      },
      {
        x: 6.104,
        z: -1.903
      },
      {
        x: 5.237,
        z: -0.325
      },
      {
        x: 2.681,
        z: 4.342
      },
      {
        x: 2.51,
        z: 4.65
      },
      {
        x: 2.347,
        z: 4.943
      },
      {
        x: 2.178,
        z: 5.244
      },
      {
        x: 1.701,
        z: 6.125
      },
      {
        x: -6.104,
        z: 1.903
      },
      {
        x: -5.622,
        z: 1.022
      },
      {
        x: -5.453,
        z: 0.719
      },
      {
        x: -5.29,
        z: 0.421
      },
      {
        x: -5.129,
        z: 0.124
      },
      {
        x: -2.563,
        z: -4.546
      },
      {
        x: -1.986,
        z: -5.6
      },
      {
        x: -1.698,
        z: -6.125
      }
    ],
    interaction: "community"
  },
  {
    id: "osm-266170765",
    districtId: "midtown",
    kind: "generic",
    name: "The Muse New York",
    position: {
      x: 38.78,
      y: 0,
      z: 16.21
    },
    size: {
      width: 11.11,
      height: 7.91,
      depth: 11.95
    },
    color: "#242b35",
    accent: "#ff6bcb",
    label: "VOICE",
    footprint: [
      {
        x: -5.556,
        z: 2.453
      },
      {
        x: -5.466,
        z: 2.283
      },
      {
        x: -1.018,
        z: -5.973
      },
      {
        x: 2.621,
        z: -4.042
      },
      {
        x: 5.556,
        z: -2.453
      },
      {
        x: 1.018,
        z: 5.973
      },
      {
        x: -0.328,
        z: 5.254
      },
      {
        x: -5.556,
        z: 2.453
      }
    ],
    interaction: "voice"
  },
  {
    id: "osm-266149309",
    districtId: "midtown",
    kind: "generic",
    name: "Church of Scientology of New York",
    position: {
      x: -34.65,
      y: 0,
      z: -41.85
    },
    size: {
      width: 10.94,
      height: 6.83,
      depth: 11.82
    },
    color: "#242b35",
    accent: "#17ff4d",
    label: "NFT HALL",
    footprint: [
      {
        x: 0.805,
        z: 5.912
      },
      {
        x: -5.469,
        z: 2.423
      },
      {
        x: -0.805,
        z: -5.912
      },
      {
        x: 5.469,
        z: -2.427
      },
      {
        x: 1.962,
        z: 3.843
      },
      {
        x: 0.805,
        z: 5.912
      }
    ],
    interaction: "nft"
  },
  {
    id: "osm-266170571",
    districtId: "midtown",
    kind: "market",
    name: "133 West 44th Street",
    position: {
      x: 23.03,
      y: 0,
      z: 46.57
    },
    size: {
      width: 9.56,
      height: 7.19,
      depth: 10.97
    },
    color: "#1f2c38",
    accent: "#17ff4d",
    label: "BUY DESK",
    footprint: [
      {
        x: 4.78,
        z: -2.724
      },
      {
        x: 4.53,
        z: -2.275
      },
      {
        x: 3.376,
        z: -0.199
      },
      {
        x: 1.513,
        z: 3.145
      },
      {
        x: 0.211,
        z: 5.484
      },
      {
        x: -1.602,
        z: 4.482
      },
      {
        x: -0.754,
        z: 2.959
      },
      {
        x: -2.229,
        z: 2.143
      },
      {
        x: -3.078,
        z: 3.667
      },
      {
        x: -4.78,
        z: 2.724
      },
      {
        x: -0.211,
        z: -5.484
      },
      {
        x: 0.733,
        z: -4.962
      },
      {
        x: 3.354,
        z: -3.511
      },
      {
        x: 4.78,
        z: -2.724
      }
    ],
    interaction: "token"
  },
  {
    id: "osm-266170583",
    districtId: "midtown",
    kind: "generic",
    name: "145 West 45th Street",
    position: {
      x: 25.38,
      y: 0,
      z: 20.11
    },
    size: {
      width: 9.87,
      height: 13.37,
      depth: 10.62
    },
    color: "#242b35",
    accent: "#17ff4d",
    label: "NFT HALL",
    footprint: [
      {
        x: -0.895,
        z: -5.309
      },
      {
        x: 4.934,
        z: -2.194
      },
      {
        x: 4.357,
        z: -1.14
      },
      {
        x: 1.791,
        z: 3.53
      },
      {
        x: 1.63,
        z: 3.827
      },
      {
        x: 1.466,
        z: 4.125
      },
      {
        x: 1.298,
        z: 4.429
      },
      {
        x: 0.816,
        z: 5.309
      },
      {
        x: -4.934,
        z: 2.19
      },
      {
        x: -4.823,
        z: 1.986
      },
      {
        x: -0.895,
        z: -5.309
      }
    ],
    interaction: "nft"
  },
  {
    id: "osm-266170601",
    districtId: "midtown",
    kind: "trading_floor",
    name: "150 West 47th Street",
    position: {
      x: 37.81,
      y: 0,
      z: -12.91
    },
    size: {
      width: 9.66,
      height: 6.83,
      depth: 10.54
    },
    color: "#23302c",
    accent: "#3de7ff",
    label: "LIVE WALL",
    footprint: [
      {
        x: 0.989,
        z: 4.852
      },
      {
        x: 0.065,
        z: 4.34
      },
      {
        x: -0.452,
        z: 5.27
      },
      {
        x: -0.9,
        z: 5.024
      },
      {
        x: -2.673,
        z: 4.043
      },
      {
        x: -3.798,
        z: 3.422
      },
      {
        x: -3.279,
        z: 2.492
      },
      {
        x: -4.831,
        z: 1.632
      },
      {
        x: -0.992,
        z: -5.27
      },
      {
        x: 4.831,
        z: -2.05
      },
      {
        x: 0.989,
        z: 4.852
      }
    ],
    interaction: "billboard"
  },
  {
    id: "osm-266170599",
    districtId: "midtown",
    kind: "market",
    name: "150 West 45th Street",
    position: {
      x: 16.84,
      y: 0,
      z: 32.32
    },
    size: {
      width: 9.02,
      height: 6.83,
      depth: 10.76
    },
    color: "#1f2c38",
    accent: "#ff4d9a",
    label: "DEX STORE",
    footprint: [
      {
        x: -0.137,
        z: 5.38
      },
      {
        x: -0.551,
        z: 5.152
      },
      {
        x: -4.509,
        z: 2.969
      },
      {
        x: 0.14,
        z: -5.38
      },
      {
        x: 3.32,
        z: -3.622
      },
      {
        x: 4.509,
        z: -2.966
      },
      {
        x: -0.137,
        z: 5.38
      }
    ],
    interaction: "marketplace"
  },
  {
    id: "osm-1317983503",
    districtId: "midtown",
    kind: "trading_floor",
    name: "SpringHill Suites",
    position: {
      x: -29.4,
      y: 0,
      z: -38.93
    },
    size: {
      width: 8.91,
      height: 7.91,
      depth: 10.71
    },
    color: "#2a2434",
    accent: "#3de7ff",
    label: "DEX DESK",
    footprint: [
      {
        x: 0.209,
        z: -5.354
      },
      {
        x: 4.455,
        z: -3.033
      },
      {
        x: 0.987,
        z: 3.233
      },
      {
        x: -0.188,
        z: 5.354
      },
      {
        x: -4.455,
        z: 2.985
      },
      {
        x: -3.298,
        z: 0.915
      },
      {
        x: 0.209,
        z: -5.354
      }
    ],
    interaction: "trading"
  },
  {
    id: "osm-266170603",
    districtId: "midtown",
    kind: "launch_arena",
    name: "151 West 46th Street",
    position: {
      x: 30.81,
      y: 0,
      z: -5.81
    },
    size: {
      width: 8.65,
      height: 7.19,
      depth: 10.55
    },
    color: "#1f2c38",
    accent: "#f5c542",
    label: "LAUNCHPAD",
    footprint: [
      {
        x: 4.325,
        z: -3.055
      },
      {
        x: -0.31,
        z: 5.277
      },
      {
        x: -4.325,
        z: 3.059
      },
      {
        x: 0.307,
        z: -5.277
      },
      {
        x: 3.2,
        z: -3.677
      },
      {
        x: 4.325,
        z: -3.055
      }
    ],
    interaction: "launch"
  },
  {
    id: "osm-266149306",
    districtId: "midtown",
    kind: "social_hub",
    name: "1557 Broadway",
    position: {
      x: -6.39,
      y: 0,
      z: -31.5
    },
    size: {
      width: 8.46,
      height: 7.55,
      depth: 9.13
    },
    color: "#1b2433",
    accent: "#a78bfa",
    label: "COMMUNITY",
    footprint: [
      {
        x: 2.593,
        z: 4.563
      },
      {
        x: -4.232,
        z: 0.77
      },
      {
        x: -2.851,
        z: -1.7
      },
      {
        x: -1.249,
        z: -4.563
      },
      {
        x: 4.232,
        z: -1.516
      },
      {
        x: 3.431,
        z: 1.454
      },
      {
        x: 2.593,
        z: 4.563
      }
    ],
    interaction: "community"
  },
  {
    id: "osm-266170544",
    districtId: "midtown",
    kind: "market",
    name: "45 Times Square Hotel",
    position: {
      x: 38.19,
      y: 0,
      z: 27.73
    },
    size: {
      width: 8.38,
      height: 7.91,
      depth: 9.07
    },
    color: "#1f2c38",
    accent: "#ff4d9a",
    label: "MEME STORE",
    footprint: [
      {
        x: 0.657,
        z: 4.536
      },
      {
        x: -1.103,
        z: 3.599
      },
      {
        x: -4.191,
        z: 1.914
      },
      {
        x: -3.714,
        z: 1.033
      },
      {
        x: -3.545,
        z: 0.732
      },
      {
        x: -3.382,
        z: 0.439
      },
      {
        x: -3.211,
        z: 0.131
      },
      {
        x: -0.655,
        z: -4.536
      },
      {
        x: 4.191,
        z: -2.01
      },
      {
        x: 0.657,
        z: 4.536
      }
    ],
    interaction: "marketplace"
  },
  {
    id: "osm-266149308",
    districtId: "midtown",
    kind: "market",
    name: "Cambria Hotel",
    position: {
      x: -15.9,
      y: 0,
      z: -42.24
    },
    size: {
      width: 7.44,
      height: 7.91,
      depth: 9.75
    },
    color: "#1f2c38",
    accent: "#ff4d9a",
    label: "MEME STORE",
    footprint: [
      {
        x: -0.843,
        z: 4.876
      },
      {
        x: -3.718,
        z: 3.276
      },
      {
        x: 0.843,
        z: -4.876
      },
      {
        x: 3.718,
        z: -3.276
      },
      {
        x: -0.843,
        z: 4.876
      }
    ],
    interaction: "marketplace"
  },
  {
    id: "osm-266170552",
    districtId: "midtown",
    kind: "generic",
    name: "115 West 45th Street",
    position: {
      x: 49.53,
      y: 0,
      z: 33.52
    },
    size: {
      width: 7.68,
      height: 6.47,
      depth: 9.26
    },
    color: "#2a2434",
    accent: "#ff6bcb",
    label: "VOICE",
    footprint: [
      {
        x: -0.076,
        z: 4.629
      },
      {
        x: -3.842,
        z: 2.625
      },
      {
        x: -0.211,
        z: -4.1
      },
      {
        x: 0.076,
        z: -4.629
      },
      {
        x: 3.842,
        z: -2.622
      },
      {
        x: 2.567,
        z: -0.263
      },
      {
        x: 1.283,
        z: 2.114
      },
      {
        x: -0.076,
        z: 4.629
      }
    ],
    interaction: "voice"
  },
  {
    id: "osm-266170628",
    districtId: "midtown",
    kind: "market",
    name: "170 West 46th Street",
    position: {
      x: 10.73,
      y: 0,
      z: -3.73
    },
    size: {
      width: 9.8,
      height: 6.83,
      depth: 6.69
    },
    color: "#242b35",
    accent: "#17ff4d",
    label: "BUY DESK",
    footprint: [
      {
        x: 3.792,
        z: 3.346
      },
      {
        x: -4.901,
        z: -1.301
      },
      {
        x: -3.789,
        z: -3.346
      },
      {
        x: 4.901,
        z: 1.301
      },
      {
        x: 4.675,
        z: 1.715
      },
      {
        x: 3.792,
        z: 3.346
      }
    ],
    interaction: "token"
  },
  {
    id: "osm-266170539",
    districtId: "midtown",
    kind: "market",
    name: "Broadway @ Times Square Hotel",
    position: {
      x: 47.79,
      y: 0,
      z: 4.25
    },
    size: {
      width: 7.15,
      height: 7.91,
      depth: 9
    },
    color: "#1f2c38",
    accent: "#ff4d9a",
    label: "MEME STORE",
    footprint: [
      {
        x: -0.482,
        z: 4.501
      },
      {
        x: -2.622,
        z: 3.313
      },
      {
        x: -3.573,
        z: 2.791
      },
      {
        x: -2.682,
        z: 1.188
      },
      {
        x: -2.126,
        z: 0.978
      },
      {
        x: -0.298,
        z: -2.314
      },
      {
        x: -0.495,
        z: -2.746
      },
      {
        x: 0.48,
        z: -4.501
      },
      {
        x: 3.573,
        z: -2.791
      },
      {
        x: 2.443,
        z: -0.76
      },
      {
        x: 2.018,
        z: -0.518
      },
      {
        x: 0.63,
        z: 1.976
      },
      {
        x: 0.669,
        z: 2.428
      },
      {
        x: -0.482,
        z: 4.501
      }
    ],
    interaction: "marketplace"
  },
  {
    id: "osm-266170757",
    districtId: "midtown",
    kind: "generic",
    name: "Night Theater District",
    position: {
      x: 27.64,
      y: 0,
      z: 37.73
    },
    size: {
      width: 6.82,
      height: 7.91,
      depth: 8.94
    },
    color: "#23302c",
    accent: "#a78bfa",
    label: "GAMES",
    footprint: [
      {
        x: -0.784,
        z: 4.472
      },
      {
        x: -3.411,
        z: 3.021
      },
      {
        x: -3,
        z: 2.285
      },
      {
        x: -2.397,
        z: 1.2
      },
      {
        x: -1.962,
        z: 1.135
      },
      {
        x: -0.112,
        z: -2.192
      },
      {
        x: -0.267,
        z: -2.624
      },
      {
        x: 0.763,
        z: -4.472
      },
      {
        x: 3.411,
        z: -3.007
      },
      {
        x: 2.823,
        z: -1.967
      },
      {
        x: 2.407,
        z: -1.218
      },
      {
        x: 2.051,
        z: -0.582
      },
      {
        x: -0.476,
        z: 3.926
      },
      {
        x: -0.784,
        z: 4.472
      }
    ],
    interaction: "games"
  },
  {
    id: "osm-266170624",
    districtId: "midtown",
    kind: "generic",
    name: "167 West 46th Street",
    position: {
      x: 14.02,
      y: 0,
      z: -11.74
    },
    size: {
      width: 8.62,
      height: 5.5,
      depth: 6.99
    },
    color: "#2a2434",
    accent: "#17ff4d",
    label: "NFT HALL",
    footprint: [
      {
        x: -4.311,
        z: -0.206
      },
      {
        x: -2.501,
        z: -3.494
      },
      {
        x: 4.311,
        z: 0.206
      },
      {
        x: 2.501,
        z: 3.494
      },
      {
        x: -4.311,
        z: -0.206
      }
    ],
    interaction: "nft"
  },
  {
    id: "osm-266170593",
    districtId: "midtown",
    kind: "trading_floor",
    name: "149 West 46th Street",
    position: {
      x: 33.7,
      y: 0,
      z: -4.21
    },
    size: {
      width: 6.41,
      height: 5.5,
      depth: 9.31
    },
    color: "#23302c",
    accent: "#3de7ff",
    label: "LIVE WALL",
    footprint: [
      {
        x: -1.431,
        z: 4.656
      },
      {
        x: -3.204,
        z: 3.675
      },
      {
        x: 1.431,
        z: -4.656
      },
      {
        x: 3.204,
        z: -3.675
      },
      {
        x: -1.431,
        z: 4.656
      }
    ],
    interaction: "billboard"
  },
  {
    id: "osm-266170608",
    districtId: "midtown",
    kind: "market",
    name: "155 West 46th Street",
    position: {
      x: 27.92,
      y: 0,
      z: -7.41
    },
    size: {
      width: 6.4,
      height: 5.75,
      depth: 9.31
    },
    color: "#242b35",
    accent: "#ff4d9a",
    label: "DEX STORE",
    footprint: [
      {
        x: -1.435,
        z: 4.655
      },
      {
        x: -3.198,
        z: 3.681
      },
      {
        x: 1.435,
        z: -4.655
      },
      {
        x: 3.198,
        z: -3.681
      },
      {
        x: -1.435,
        z: 4.655
      }
    ],
    interaction: "marketplace"
  },
  {
    id: "osm-266170600",
    districtId: "midtown",
    kind: "trading_floor",
    name: "150 West 46th Street",
    position: {
      x: 25.55,
      y: 0,
      z: 8.54
    },
    size: {
      width: 6.69,
      height: 6.83,
      depth: 8.78
    },
    color: "#2a2434",
    accent: "#3de7ff",
    label: "DEX DESK",
    footprint: [
      {
        x: 0.119,
        z: 2.928
      },
      {
        x: -0.516,
        z: 2.589
      },
      {
        x: -1.486,
        z: 4.389
      },
      {
        x: -3.344,
        z: 3.394
      },
      {
        x: 0.848,
        z: -4.389
      },
      {
        x: 3.344,
        z: -3.055
      },
      {
        x: 0.119,
        z: 2.928
      }
    ],
    interaction: "trading"
  },
  {
    id: "osm-266170542",
    districtId: "midtown",
    kind: "launch_arena",
    name: "Dervish",
    position: {
      x: 41.44,
      y: 0,
      z: -10.81
    },
    size: {
      width: 6.32,
      height: 5.5,
      depth: 9.23
    },
    color: "#1f2c38",
    accent: "#f5c542",
    label: "LAUNCHPAD",
    footprint: [
      {
        x: -1.459,
        z: 4.617
      },
      {
        x: -3.013,
        z: 3.764
      },
      {
        x: -3.161,
        z: 3.681
      },
      {
        x: -2.642,
        z: 2.751
      },
      {
        x: 1.2,
        z: -4.15
      },
      {
        x: 1.461,
        z: -4.617
      },
      {
        x: 2.341,
        z: -4.137
      },
      {
        x: 3.161,
        z: -3.684
      },
      {
        x: -1.459,
        z: 4.617
      }
    ],
    interaction: "launch"
  },
  {
    id: "osm-266170540",
    districtId: "midtown",
    kind: "social_hub",
    name: "Connolly's",
    position: {
      x: 43.79,
      y: 0,
      z: 30.8
    },
    size: {
      width: 6.84,
      height: 5.5,
      depth: 8.43
    },
    color: "#1b2433",
    accent: "#a78bfa",
    label: "COMMUNITY",
    footprint: [
      {
        x: -0.212,
        z: 4.216
      },
      {
        x: -2.254,
        z: 3.128
      },
      {
        x: -3.419,
        z: 2.506
      },
      {
        x: 0.212,
        z: -4.216
      },
      {
        x: 3.419,
        z: -2.51
      },
      {
        x: 2.154,
        z: -0.171
      },
      {
        x: 1.806,
        z: 0.478
      },
      {
        x: 1.416,
        z: 1.2
      },
      {
        x: 1.058,
        z: 1.867
      },
      {
        x: -0.212,
        z: 4.216
      }
    ],
    interaction: "community"
  },
  {
    id: "osm-266170587",
    districtId: "midtown",
    kind: "generic",
    name: "147 West 46th Street",
    position: {
      x: 35.35,
      y: 0,
      z: -3.3
    },
    size: {
      width: 6.15,
      height: 7.55,
      depth: 9.17
    },
    color: "#302820",
    accent: "#ff6bcb",
    label: "VOICE",
    footprint: [
      {
        x: 3.076,
        z: -3.746
      },
      {
        x: -1.556,
        z: 4.586
      },
      {
        x: -3.076,
        z: 3.746
      },
      {
        x: 1.559,
        z: -4.586
      },
      {
        x: 2.007,
        z: -4.34
      },
      {
        x: 2.929,
        z: -3.829
      },
      {
        x: 3.076,
        z: -3.746
      }
    ],
    interaction: "voice"
  },
  {
    id: "osm-266170573",
    districtId: "midtown",
    kind: "market",
    name: "136 West 46th Street",
    position: {
      x: 33.58,
      y: 0,
      z: 13.31
    },
    size: {
      width: 5.78,
      height: 5.5,
      depth: 8.97
    },
    color: "#23302c",
    accent: "#17ff4d",
    label: "BUY DESK",
    footprint: [
      {
        x: -1.556,
        z: 4.486
      },
      {
        x: -2.892,
        z: 3.77
      },
      {
        x: -2.394,
        z: 2.845
      },
      {
        x: 1.395,
        z: -4.192
      },
      {
        x: 1.553,
        z: -4.486
      },
      {
        x: 2.892,
        z: -3.77
      },
      {
        x: -1.556,
        z: 4.486
      }
    ],
    interaction: "token"
  },
  {
    id: "osm-266170759",
    districtId: "midtown",
    kind: "generic",
    name: "Amor Loco",
    position: {
      x: 34.89,
      y: 0,
      z: 14.02
    },
    size: {
      width: 5.74,
      height: 5.5,
      depth: 8.95
    },
    color: "#23302c",
    accent: "#17ff4d",
    label: "NFT HALL",
    footprint: [
      {
        x: -1.576,
        z: 4.475
      },
      {
        x: -2.872,
        z: 3.781
      },
      {
        x: 1.576,
        z: -4.475
      },
      {
        x: 2.277,
        z: -4.116
      },
      {
        x: 2.872,
        z: -3.781
      },
      {
        x: -1.576,
        z: 4.475
      }
    ],
    interaction: "nft"
  }
],
  billboards: [
    {
      id: "bb-osm-orbitx",
      position: { x: -6, y: 5.2, z: 2 },
      rotationY: 0.35,
      width: 5.8,
      height: 3.1,
      title: "ORBITX",
      subtitle: "Real Midtown · live markets",
      accent: "#17ff4d",
      projectName: "OrbitX",
      website: "https://orbitx.world",
    },
    {
      id: "bb-osm-broadway",
      position: { x: 7, y: 5, z: -3 },
      rotationY: -0.45,
      width: 5.4,
      height: 2.9,
      title: "BROADWAY",
      subtitle: "OSM footprints · walk-in venues",
      accent: "#3de7ff",
      projectName: "Midtown NYC",
    },
  ],
  zones: [
  {
    id: "z-osm-163474780",
    kind: "community",
    label: "SOCIAL",
    hint: "Community · social feed & chat",
    position: {
      x: -13.11,
      y: 0,
      z: 5.52
    },
    radius: 5.5,
    buildingId: "osm-163474780"
  },
  {
    id: "z-osm-157835453",
    kind: "trading",
    label: "DEX FLOOR",
    hint: "Trading floor · live screener",
    position: {
      x: -24.06,
      y: 0,
      z: 28.39
    },
    radius: 5.5,
    buildingId: "osm-157835453"
  },
  {
    id: "z-osm-266149338",
    kind: "trading",
    label: "DEX DESK",
    hint: "Trading floor · live screener",
    position: {
      x: -60.44,
      y: 0,
      z: 41.13
    },
    radius: 5.5,
    buildingId: "osm-266149338"
  },
  {
    id: "z-osm-266149373",
    kind: "launch",
    label: "LAUNCHPAD",
    hint: "Launchpad · new tokens",
    position: {
      x: -38.57,
      y: 0,
      z: 50.57
    },
    radius: 5.5,
    buildingId: "osm-266149373"
  },
  {
    id: "z-osm-137716320",
    kind: "hq",
    label: "ORBITX HQ",
    hint: "OrbitX HQ · DEX, launchpad, social",
    position: {
      x: 11.51,
      y: 0,
      z: 20.43
    },
    radius: 5.5,
    buildingId: "osm-137716320"
  },
  {
    id: "z-osm-143858914",
    kind: "community",
    label: "COMMUNITY",
    hint: "Community · social feed & chat",
    position: {
      x: -28.64,
      y: 0,
      z: -32.26
    },
    radius: 5.5,
    buildingId: "osm-143858914"
  },
  {
    id: "z-osm-163629929",
    kind: "token",
    label: "BUY DESK",
    hint: "Token buy desk · Jupiter swap",
    position: {
      x: -10.56,
      y: 0,
      z: 65.01
    },
    radius: 5.5,
    buildingId: "osm-163629929"
  },
  {
    id: "z-osm-266170537",
    kind: "nft",
    label: "NFT HALL",
    hint: "NFT gallery",
    position: {
      x: 45.96,
      y: 0,
      z: 10.02
    },
    radius: 5.5,
    buildingId: "osm-266170537"
  },
  {
    id: "z-osm-266170615",
    kind: "voice",
    label: "VOICE",
    hint: "Voice plaza · live talk",
    position: {
      x: 23.22,
      y: 0,
      z: -7.43
    },
    radius: 5.5,
    buildingId: "osm-266170615"
  },
  {
    id: "z-osm-266149345",
    kind: "games",
    label: "GAMES",
    hint: "Games district",
    position: {
      x: -47.65,
      y: 0,
      z: -13.9
    },
    radius: 5.5,
    buildingId: "osm-266149345"
  },
  {
    id: "z-osm-266170795",
    kind: "marketplace",
    label: "DEX STORE",
    hint: "Meme Market · live DEX store",
    position: {
      x: 38.4,
      y: 0,
      z: -23.93
    },
    radius: 5.467,
    buildingId: "osm-266170795"
  },
  {
    id: "z-osm-266170751",
    kind: "games",
    label: "GAMES",
    hint: "Games district",
    position: {
      x: 23.47,
      y: 0,
      z: 53.61
    },
    radius: 4.787999999999999,
    buildingId: "osm-266170751"
  },
  {
    id: "z-osm-266170758",
    kind: "trading",
    label: "DEX DESK",
    hint: "Trading floor · live screener",
    position: {
      x: 55.99,
      y: 0,
      z: 30.58
    },
    radius: 5.0295,
    buildingId: "osm-266170758"
  },
  {
    id: "z-osm-266149312",
    kind: "launch",
    label: "LAUNCHPAD",
    hint: "Launchpad · new tokens",
    position: {
      x: -56.46,
      y: 0,
      z: -41.11
    },
    radius: 5.3585,
    buildingId: "osm-266149312"
  },
  {
    id: "z-osm-266170755",
    kind: "games",
    label: "GAMES",
    hint: "Games district",
    position: {
      x: 17.02,
      y: 0,
      z: 25.08
    },
    radius: 4.616499999999999,
    buildingId: "osm-266170755"
  },
  {
    id: "z-osm-266170766",
    kind: "launch",
    label: "LAUNCHPAD",
    hint: "Launchpad · new tokens",
    position: {
      x: 34.67,
      y: 0,
      z: 52.39
    },
    radius: 5.0504999999999995,
    buildingId: "osm-266170766"
  },
  {
    id: "z-osm-266149327",
    kind: "games",
    label: "GAMES",
    hint: "Games district",
    position: {
      x: -4.96,
      y: 0,
      z: -22.66
    },
    radius: 5.1659999999999995,
    buildingId: "osm-266149327"
  },
  {
    id: "z-osm-266170769",
    kind: "marketplace",
    label: "MEME STORE",
    hint: "Meme Market · live DEX store",
    position: {
      x: 53.59,
      y: 0,
      z: -14.78
    },
    radius: 4.826499999999999,
    buildingId: "osm-266170769"
  },
  {
    id: "z-osm-266149330",
    kind: "games",
    label: "GAMES",
    hint: "Games district",
    position: {
      x: -47.14,
      y: 0,
      z: -13.64
    },
    radius: 4.8405,
    buildingId: "osm-266149330"
  },
  {
    id: "z-osm-266149334",
    kind: "games",
    label: "GAMES",
    hint: "Games district",
    position: {
      x: -52.87,
      y: 0,
      z: 13
    },
    radius: 4.872,
    buildingId: "osm-266149334"
  },
  {
    id: "z-osm-266170756",
    kind: "marketplace",
    label: "MEME STORE",
    hint: "Meme Market · live DEX store",
    position: {
      x: 11.97,
      y: 0,
      z: 49.41
    },
    radius: 4.731999999999999,
    buildingId: "osm-266170756"
  },
  {
    id: "z-osm-266149299",
    kind: "games",
    label: "GAMES",
    hint: "Games district",
    position: {
      x: -50.91,
      y: 0,
      z: 12.96
    },
    radius: 4.2315,
    buildingId: "osm-266149299"
  },
  {
    id: "z-osm-266149329",
    kind: "games",
    label: "GAMES",
    hint: "Games district",
    position: {
      x: -50.09,
      y: 0,
      z: -13.27
    },
    radius: 4.2315,
    buildingId: "osm-266149329"
  },
  {
    id: "z-osm-260180778",
    kind: "community",
    label: "COMMUNITY",
    hint: "Community · social feed & chat",
    position: {
      x: 32.3,
      y: 0,
      z: 31.84
    },
    radius: 4.2735,
    buildingId: "osm-260180778"
  },
  {
    id: "z-osm-266170765",
    kind: "voice",
    label: "VOICE",
    hint: "Voice plaza · live talk",
    position: {
      x: 36.06,
      y: 0,
      z: 34.53
    },
    radius: 3.8884999999999996,
    buildingId: "osm-266170765"
  },
  {
    id: "z-osm-266149309",
    kind: "nft",
    label: "NFT HALL",
    hint: "NFT gallery",
    position: {
      x: -30.75,
      y: 0,
      z: -31.49
    },
    radius: 3.8289999999999997,
    buildingId: "osm-266149309"
  },
  {
    id: "z-osm-266170571",
    kind: "token",
    label: "BUY DESK",
    hint: "Token buy desk · Jupiter swap",
    position: {
      x: 23.03,
      y: 0,
      z: 54.26
    },
    radius: 3.346,
    buildingId: "osm-266170571"
  },
  {
    id: "z-osm-266170583",
    kind: "nft",
    label: "NFT HALL",
    hint: "NFT gallery",
    position: {
      x: 29.62,
      y: 0,
      z: 31.86
    },
    radius: 3.4544999999999995,
    buildingId: "osm-266170583"
  },
  {
    id: "z-osm-266170601",
    kind: "billboard",
    label: "LIVE WALL",
    hint: "Live OrbitX data",
    position: {
      x: 32.56,
      y: 0,
      z: 3.65
    },
    radius: 3.381,
    buildingId: "osm-266170601"
  },
  {
    id: "z-osm-266170599",
    kind: "marketplace",
    label: "DEX STORE",
    hint: "Meme Market · live DEX store",
    position: {
      x: 11.59,
      y: 0,
      z: 48.99
    },
    radius: 3.2,
    buildingId: "osm-266170599"
  },
  {
    id: "z-osm-1317983503",
    kind: "trading",
    label: "DEX DESK",
    hint: "Trading floor · live screener",
    position: {
      x: -29.4,
      y: 0,
      z: -31.38
    },
    radius: 3.2,
    buildingId: "osm-1317983503"
  },
  {
    id: "z-osm-266170603",
    kind: "launch",
    label: "LAUNCHPAD",
    hint: "Launchpad · new tokens",
    position: {
      x: 30.81,
      y: 0,
      z: 1.67
    },
    radius: 3.2,
    buildingId: "osm-266170603"
  },
  {
    id: "z-osm-266149306",
    kind: "community",
    label: "COMMUNITY",
    hint: "Community · social feed & chat",
    position: {
      x: -3.39,
      y: 0,
      z: -24.73
    },
    radius: 3.2,
    buildingId: "osm-266149306"
  },
  {
    id: "z-osm-266170544",
    kind: "marketplace",
    label: "MEME STORE",
    hint: "Meme Market · live DEX store",
    position: {
      x: 38.19,
      y: 0,
      z: 34.47
    },
    radius: 3.2,
    buildingId: "osm-266170544"
  },
  {
    id: "z-osm-266149308",
    kind: "marketplace",
    label: "MEME STORE",
    hint: "Meme Market · live DEX store",
    position: {
      x: -9.54,
      y: 0,
      z: -41.53
    },
    radius: 3.2,
    buildingId: "osm-266149308"
  },
  {
    id: "z-osm-266170552",
    kind: "voice",
    label: "VOICE",
    hint: "Voice plaza · live talk",
    position: {
      x: 49.53,
      y: 0,
      z: 40.35
    },
    radius: 3.2,
    buildingId: "osm-266170552"
  },
  {
    id: "z-osm-266170628",
    kind: "token",
    label: "BUY DESK",
    hint: "Token buy desk · Jupiter swap",
    position: {
      x: 8.01,
      y: 0,
      z: -8.33
    },
    radius: 3.2,
    buildingId: "osm-266170628"
  },
  {
    id: "z-osm-266170539",
    kind: "marketplace",
    label: "MEME STORE",
    hint: "Meme Market · live DEX store",
    position: {
      x: 47.79,
      y: 0,
      z: 10.95
    },
    radius: 3.2,
    buildingId: "osm-266170539"
  },
  {
    id: "z-osm-266170757",
    kind: "games",
    label: "GAMES",
    hint: "Games district",
    position: {
      x: 29.58,
      y: 0,
      z: 51.64
    },
    radius: 3.2,
    buildingId: "osm-266170757"
  },
  {
    id: "z-osm-266170624",
    kind: "nft",
    label: "NFT HALL",
    hint: "NFT gallery",
    position: {
      x: 16.92,
      y: 0,
      z: -6.82
    },
    radius: 3.2,
    buildingId: "osm-266170624"
  },
  {
    id: "z-osm-266170593",
    kind: "billboard",
    label: "LIVE WALL",
    hint: "Live OrbitX data",
    position: {
      x: 32.2,
      y: 0,
      z: 5.24
    },
    radius: 3.2,
    buildingId: "osm-266170593"
  },
  {
    id: "z-osm-266170608",
    kind: "marketplace",
    label: "DEX STORE",
    hint: "Meme Market · live DEX store",
    position: {
      x: 29.42,
      y: 0,
      z: 2.04
    },
    radius: 3.2,
    buildingId: "osm-266170608"
  },
  {
    id: "z-osm-266170600",
    kind: "trading",
    label: "DEX DESK",
    hint: "Trading floor · live screener",
    position: {
      x: 30.8,
      y: 0,
      z: 6.04
    },
    radius: 3.2,
    buildingId: "osm-266170600"
  },
  {
    id: "z-osm-266170542",
    kind: "launch",
    label: "LAUNCHPAD",
    hint: "Launchpad · new tokens",
    position: {
      x: 31.05,
      y: 0,
      z: 2
    },
    radius: 3.2,
    buildingId: "osm-266170542"
  },
  {
    id: "z-osm-266170540",
    kind: "community",
    label: "COMMUNITY",
    hint: "Community · social feed & chat",
    position: {
      x: 45.29,
      y: 0,
      z: 39.81
    },
    radius: 3.2,
    buildingId: "osm-266170540"
  },
  {
    id: "z-osm-266170587",
    kind: "voice",
    label: "VOICE",
    hint: "Voice plaza · live talk",
    position: {
      x: 32.45,
      y: 0,
      z: 4.26
    },
    radius: 3.2,
    buildingId: "osm-266170587"
  },
  {
    id: "z-osm-266170573",
    kind: "token",
    label: "BUY DESK",
    hint: "Token buy desk · Jupiter swap",
    position: {
      x: 30.47,
      y: 0,
      z: 31.59
    },
    radius: 3.2,
    buildingId: "osm-266170573"
  },
  {
    id: "z-osm-266170759",
    kind: "nft",
    label: "NFT HALL",
    hint: "NFT gallery",
    position: {
      x: 24.5,
      y: 0,
      z: 26.69
    },
    radius: 3.2,
    buildingId: "osm-266170759"
  }
],
};

export const OSM_ATTRIBUTION =
  "Map data © OpenStreetMap contributors (ODbL). Midtown NYC footprints.";
